# Generated by Django 5.2.15 on 2026-06-22 20:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_tenant_prefs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(help_text='The JSON key stored in custom_fields, e.g. owner_team.', max_length=64)),
                ('label', models.CharField(help_text='Human-friendly name shown in forms.', max_length=128)),
                ('type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text (multi-line)'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('url', 'URL'), ('select', 'Selection'), ('multiselect', 'Multiple selection')], default='text', max_length=16)),
                ('applies_to', models.JSONField(blank=True, default=list, help_text='Model slugs this field attaches to (see CUSTOMIZABLE_MODELS).')),
                ('choices', models.JSONField(blank=True, default=list, help_text='Allowed options for select / multiselect fields.')),
                ('required', models.BooleanField(default=False)),
                ('default', models.CharField(blank=True, default='', help_text='Default value, stored as text and coerced by type.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('weight', models.IntegerField(default=0, help_text='Display order, low → high.')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='core.tenant')),
            ],
            options={
                'ordering': ['weight', 'label'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key'), name='uniq_customfield_tenant_key')],
            },
        ),
    ]
