# Generated by Django 5.2.15 on 2026-06-30 07:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_deploymentsettings_device_field_visibility'),
        ('customization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(help_text='Stable reference, unique within the tenant.', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('weight', models.IntegerField(default=0, help_text='Section order, low → high.')),
                ('collapsed', models.BooleanField(default=False, help_text='Start collapsed on detail pages.')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_groups', to='core.tenant')),
            ],
            options={
                'ordering': ['weight', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customfield',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional section this field is shown under.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='customization.customfieldgroup'),
        ),
        migrations.AddConstraint(
            model_name='customfieldgroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_cfgroup_tenant_slug'),
        ),
    ]
