# Generated by Django 5.2.15 on 2026-07-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0002_customfieldgroup_customfield_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='related_model',
            field=models.CharField(blank=True, default='', help_text='Object fields: the reference-model slug the value points at (see customization.object_registry).', max_length=32),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text (multi-line)'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('url', 'URL'), ('select', 'Selection'), ('multiselect', 'Multiple selection'), ('object', 'Object reference')], default='text', max_length=16),
        ),
    ]
