# Generated by Django 5.2.15 on 2026-07-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0003_customfield_related_model_alter_customfield_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='scope_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Optional structured visibility/reference scope rules.'),
        ),
    ]
