# Generated by Django 5.2.15 on 2026-07-15 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_devicetype_owning_site_iprole_owning_site_and_more'),
        ('customization', '0004_customfield_scope_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='owning_site',
            field=models.ForeignKey(blank=True, help_text='Set = local to that site (enhanced site separation); empty = global to the tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.site'),
        ),
        migrations.AddField(
            model_name='customfieldgroup',
            name='owning_site',
            field=models.ForeignKey(blank=True, help_text='Set = local to that site (enhanced site separation); empty = global to the tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.site'),
        ),
    ]
