# Generated by Django 5.2.16 on 2026-09-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0005_customfield_owning_site_customfieldgroup_owning_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='hidden',
            field=models.BooleanField(default=False, help_text="Keep the value but don't show it in the UI."),
        ),
    ]
