# Generated by Django 5.2.15 on 2026-06-23 21:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_deploymentsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=8)),
                ('object_type', models.CharField(help_text='Which model the rule applies to.', max_length=20)),
                ('check_type', models.CharField(choices=[('required', 'Field must be set'), ('forbidden', 'Field must be empty'), ('regex', 'Field must match a pattern'), ('required_tag', 'Must carry a tag'), ('required_cf', 'Custom field must be set')], max_length=16)),
                ('field', models.CharField(blank=True, default='', max_length=64)),
                ('pattern', models.CharField(blank=True, default='', max_length=255)),
                ('tag', models.CharField(blank=True, default='', max_length=100)),
                ('cf_key', models.CharField(blank=True, default='', max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_rules', to='core.tenant')),
            ],
            options={
                'ordering': ['object_type', 'name'],
                'indexes': [models.Index(fields=['tenant', 'enabled'], name='compliance__tenant__27b91b_idx')],
            },
        ),
    ]
