# Generated by Django 5.2.15 on 2026-07-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancerule',
            name='remediation',
            field=models.TextField(blank=True, default='', help_text='Markdown remediation guide shown alongside violations.'),
        ),
    ]
