# Generated by Django 5.2.16 on 2026-10-10 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0201_rack_max_power_w'),
        ('compliance', '0002_compliancerule_remediation'),
        ('core', '0060_tenantsettings_capacity_thresholds'),
    ]

    operations = [
        migrations.CreateModel(
            name='EolSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('source_urls', models.JSONField(blank=True, default=dict)),
                ('warning_days', models.PositiveSmallIntegerField(default=180, help_text='End of life within this many days reads as Support ending.')),
                ('last_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('last_refresh_status', models.CharField(blank=True, default='', max_length=8)),
                ('last_refresh_error', models.TextField(blank=True, default='')),
                ('last_refresh_via', models.CharField(blank=True, default='', max_length=8)),
            ],
            options={
                'verbose_name': 'end-of-life settings',
                'verbose_name_plural': 'end-of-life settings',
            },
        ),
        migrations.AddField(
            model_name='compliancerule',
            name='eol_fail_on',
            field=models.CharField(blank=True, choices=[('eol', 'End of life'), ('ending', 'Support ending or ended'), ('unknown', 'No end-of-life data')], db_default='', default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='compliancerule',
            name='check_type',
            field=models.CharField(choices=[('required', 'Field must be set'), ('forbidden', 'Field must be empty'), ('regex', 'Field must match a pattern'), ('required_tag', 'Must carry a tag'), ('required_cf', 'Custom field must be set'), ('eol_status', 'End-of-life status')], max_length=16),
        ),
        migrations.CreateModel(
            name='EolProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('releases', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['source', 'name'],
                'constraints': [models.UniqueConstraint(fields=('source', 'name'), name='uniq_eolproduct_source_name')],
            },
        ),
        migrations.CreateModel(
            name='EolMapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=32)),
                ('product', models.CharField(max_length=128)),
                ('cycle', models.CharField(max_length=64)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('support_until', models.DateField(blank=True, null=True)),
                ('eol_date', models.DateField(blank=True, null=True)),
                ('eol_reached', models.BooleanField(blank=True, null=True)),
                ('lts', models.BooleanField(default=False)),
                ('latest_version', models.CharField(blank=True, default='', max_length=64)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('missing', models.BooleanField(default=False)),
                ('platform', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eol_mapping', to='api.platform')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eol_mappings', to='core.tenant')),
            ],
            options={
                'ordering': ['product', 'cycle'],
                'indexes': [models.Index(fields=['source', 'product'], name='compliance__source_9bc631_idx')],
            },
        ),
    ]
