# Generated by Django 5.2.16 on 2026-09-08 21:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_api', '0023_ldapgroupmapping_grants_superuser'),
        ('core', '0049_deploymentsettings_upgrade_notes_done'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allowed_types', models.JSONField(blank=True, default=list)),
                ('max_rows', models.PositiveIntegerField(default=50)),
                ('log_retention_days', models.PositiveIntegerField(default=30)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_settings', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'agent settings',
            },
        ),
        migrations.CreateModel(
            name='AgentCall',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_name', models.CharField(blank=True, default='', max_length=128)),
                ('client', models.CharField(blank=True, default='', max_length=120)),
                ('tool', models.CharField(max_length=64)),
                ('object_type', models.CharField(blank=True, default='', max_length=64)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('rows', models.IntegerField(default=0)),
                ('wrote', models.BooleanField(default=False)),
                ('ms', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_calls', to='core.tenant')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth_api.apitoken')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='agents_agen_tenant__2854ce_idx'), models.Index(fields=['tool', '-created_at'], name='agents_agen_tool_7302b1_idx')],
            },
        ),
    ]
