# Generated by Django 5.2.15 on 2026-06-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='prefs',
            field=models.JSONField(blank=True, default=dict, help_text='Tenant-wide admin-set defaults: page size override, default IP status / role, gateway role, etc. Users can still override on their own UserProfile.prefs.'),
        ),
    ]
