# Generated by Django 5.2.15 on 2026-06-23 16:08

import monitoring.secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tenant_prefs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=False, help_text='When off, email channels are skipped (other transports unaffected).')),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_security', models.CharField(choices=[('none', 'None'), ('starttls', 'STARTTLS'), ('ssl', 'SSL/TLS')], default='starttls', max_length=8)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('secrets', monitoring.secrets.EncryptedJSONField(blank=True, default=dict)),
                ('email_from', models.CharField(blank=True, default='', help_text='From header, e.g. "Danbyte Alerts <alerts@acme.com>".', max_length=255)),
                ('public_base_url', models.CharField(blank=True, default='', help_text='Public URL of this install, used to deep-link alerts in messages.', max_length=255)),
                ('webhook_timeout', models.PositiveSmallIntegerField(default=5, help_text='Seconds to wait for Slack/Teams/PagerDuty/webhook POSTs.')),
                ('outbound_proxy', models.CharField(blank=True, default='', help_text='Optional HTTP(S) proxy for outbound webhooks, e.g. http://proxy:3128.', max_length=255)),
            ],
            options={
                'verbose_name': 'deployment settings',
                'verbose_name_plural': 'deployment settings',
            },
        ),
    ]
