# Generated by Django 5.2.15 on 2026-06-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deploymentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='changelog_retention_days',
            field=models.PositiveSmallIntegerField(default=730, help_text='Days to keep change-log / audit entries before pruning. 0 = keep forever.'),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='deployment_name',
            field=models.CharField(blank=True, default='', help_text='Display name for this install, shown in the browser title. Blank = "Danbyte".', max_length=100),
        ),
    ]
