# Generated by Django 5.2.15 on 2026-06-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='ldap_attr_email',
            field=models.CharField(blank=True, default='mail', max_length=64),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='ldap_attr_first_name',
            field=models.CharField(blank=True, default='givenName', max_length=64),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='ldap_attr_last_name',
            field=models.CharField(blank=True, default='sn', max_length=64),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='ldap_bind_dn',
            field=models.CharField(blank=True, default='', help_text='Service account that may search the directory, e.g. CN=danbyte,OU=Service,DC=acme,DC=local.', max_length=255),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='ldap_enabled',
            field=models.BooleanField(default=False, help_text='When on, users can authenticate against the directory below.'),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='ldap_group_search_base',
            field=models.CharField(blank=True, default='', help_text='Base DN to search for groups, e.g. OU=Groups,DC=acme,DC=local.', max_length=255),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='ldap_group_type',
            field=models.CharField(choices=[('ad', 'Active Directory (nested)'), ('group_of_names', 'groupOfNames (OpenLDAP)'), ('posix', 'POSIX groups')], default='ad', max_length=16),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='ldap_ignore_cert',
            field=models.BooleanField(default=False, help_text='Skip TLS certificate validation (lab use only).'),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='ldap_require_group',
            field=models.CharField(blank=True, default='', help_text='Optional group DN a user must belong to in order to sign in.', max_length=255),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='ldap_server_uri',
            field=models.CharField(blank=True, default='', help_text='e.g. ldaps://dc01.acme.local or ldap://dc01.acme.local', max_length=255),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='ldap_start_tls',
            field=models.BooleanField(default=False, help_text='Upgrade a plain ldap:// connection with StartTLS.'),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='ldap_user_search_base',
            field=models.CharField(blank=True, default='', help_text='Base DN to search for users, e.g. OU=Users,DC=acme,DC=local.', max_length=255),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='ldap_user_search_filter',
            field=models.CharField(blank=True, default='(sAMAccountName=%(user)s)', help_text='%(user)s is replaced with the login name.', max_length=255),
        ),
    ]
