# Generated by Django 5.2.15 on 2026-06-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_deploymentsettings_ldap_attr_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='allow_public_share_links',
            field=models.BooleanField(default=False, help_text='When on, users may generate expiring read-only links that show a single object without logging in.'),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='allow_site_editor_delegation',
            field=models.BooleanField(default=False, help_text='When on, a site editor (local IT) may invite their own viewers to the site(s) they edit — without a global admin.'),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='public_share_max_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Maximum lifetime (days) for a public share link. Creators may choose any expiry up to this cap.'),
        ),
    ]
