# Generated by Django 5.2.15 on 2026-06-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_deploymentsettings_allow_public_share_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='config_drift_enabled',
            field=models.BooleanField(default=False, help_text='When on, Danbyte periodically dispatches a config-drift run to every enabled automation target.'),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='config_drift_interval_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Minimum minutes between scheduled config-drift dispatches.'),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='config_drift_last_run',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last scheduled config-drift dispatch.', null=True),
        ),
    ]
