# Generated by Django 5.2.15 on 2026-06-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_deploymentsettings_config_drift_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='device_field_visibility',
            field=models.JSONField(blank=True, default=dict, help_text='Maps optional built-in device field keys → bool. Controls whether each optional field is shown on the device form/detail. Unset keys fall back to server-side defaults.'),
        ),
    ]
