# Generated by Django 5.2.15 on 2026-07-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tenantgroup_tenant_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='auto_update_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='release_repo_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='update_channel',
            field=models.CharField(choices=[('stable', 'Stable only'), ('any', 'Any (incl. prerelease)')], default='stable', max_length=8),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='update_window_days',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='update_window_end',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='update_window_start',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
