# Generated by Django 5.2.15 on 2026-07-08 17:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_deploymentsettings_auto_update_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['folder__weight', 'folder__name', 'weight', 'label']},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BookmarkFolder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('weight', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.bookmarkfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['weight', 'name'],
            },
        ),
        migrations.AddField(
            model_name='bookmark',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='core.bookmarkfolder'),
        ),
        migrations.AddConstraint(
            model_name='bookmarkfolder',
            constraint=models.UniqueConstraint(fields=('user', 'parent', 'name'), name='uniq_user_bookmark_folder_name'),
        ),
    ]
