# Generated by Django 5.2.15 on 2026-07-11 15:36

import django.db.models.deletion
import monitoring.secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_bookmark_options_bookmark_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('override_email', models.BooleanField(default=False)),
                ('override_ldap', models.BooleanField(default=False)),
                ('override_ui', models.BooleanField(default=False)),
                ('override_sharing', models.BooleanField(default=False)),
                ('email_enabled', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_security', models.CharField(choices=[('none', 'None'), ('starttls', 'STARTTLS'), ('ssl', 'SSL/TLS')], default='starttls', max_length=8)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('email_from', models.CharField(blank=True, default='', max_length=255)),
                ('device_field_visibility', models.JSONField(blank=True, default=dict)),
                ('human_ids_enabled', models.BooleanField(default=True)),
                ('allow_site_editor_delegation', models.BooleanField(default=False)),
                ('allow_public_share_links', models.BooleanField(default=False)),
                ('public_share_max_days', models.PositiveSmallIntegerField(default=30)),
                ('ldap_enabled', models.BooleanField(default=False)),
                ('ldap_server_uri', models.CharField(blank=True, default='', max_length=255)),
                ('ldap_start_tls', models.BooleanField(default=False)),
                ('ldap_ignore_cert', models.BooleanField(default=False)),
                ('ldap_bind_dn', models.CharField(blank=True, default='', max_length=255)),
                ('ldap_user_search_base', models.CharField(blank=True, default='', max_length=255)),
                ('ldap_user_search_filter', models.CharField(blank=True, default='(sAMAccountName=%(user)s)', max_length=255)),
                ('ldap_attr_first_name', models.CharField(blank=True, default='givenName', max_length=64)),
                ('ldap_attr_last_name', models.CharField(blank=True, default='sn', max_length=64)),
                ('ldap_attr_email', models.CharField(blank=True, default='mail', max_length=64)),
                ('ldap_group_search_base', models.CharField(blank=True, default='', max_length=255)),
                ('ldap_group_type', models.CharField(choices=[('ad', 'Active Directory (nested)'), ('group_of_names', 'groupOfNames (OpenLDAP)'), ('posix', 'POSIX groups')], default='ad', max_length=16)),
                ('ldap_require_group', models.CharField(blank=True, default='', max_length=255)),
                ('ldap_login_domains', models.JSONField(blank=True, default=list)),
                ('secrets', monitoring.secrets.EncryptedJSONField(blank=True, default=dict)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.tenant')),
            ],
            options={
                'verbose_name': 'tenant settings',
                'verbose_name_plural': 'tenant settings',
            },
        ),
    ]
