# Generated by Django 5.2.15 on 2026-07-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tenantsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentsettings',
            name='deployment_name',
            field=models.CharField(blank=True, default='', help_text='Display name for this install — the app name shown in the sidebar header, the browser tab title, and the login page. Blank = "Danbyte".', max_length=100),
        ),
    ]
