# Generated by Django 5.2.15 on 2026-07-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_deploymentsettings_deployment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='floorplan_popover_fields',
            field=models.JSONField(blank=True, default=list, help_text='Ordered field keys shown in the floor-plan tile popover. Empty = the server-side default set.'),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='floorplan_popover_tile_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Per-tile-type popover field lists, keyed by tile-type slug. A slug that is ABSENT inherits floorplan_popover_fields — only store a list for types that genuinely differ.'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='floorplan_popover_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='floorplan_popover_tile_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
