# Generated by Django 5.2.15 on 2026-07-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_deploymentsettings_floorplan_popover_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='override_floorplan_popover',
            field=models.BooleanField(default=False),
        ),
    ]
