# Generated by Django 5.2.15 on 2026-07-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_tenantsettings_override_floorplan_popover'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='allow_site_settings',
            field=models.BooleanField(default=False, help_text="When on, site admins (site editors, or holders of a sitesettings grant) may manage their own site's settings — e.g. email delivery."),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='enhanced_site_separation',
            field=models.BooleanField(default=False, help_text='When on, each site behaves like a mini-tenant for site-scoped users: pickers only offer their sites, new objects default there, and catalog entries they create are local to their site. Cross-site users and admins are unaffected.'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='allow_site_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='enhanced_site_separation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='override_separation',
            field=models.BooleanField(default=False),
        ),
    ]
