# Generated by Django 5.2.15 on 2026-07-15 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_devicetype_owning_site_iprole_owning_site_and_more'),
        ('core', '0018_deploymentsettings_allow_site_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='owning_site',
            field=models.ForeignKey(blank=True, help_text='Set = local to that site (enhanced site separation); empty = global to the tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.site'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_tag_tenant_slug', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_tag_tenant_name', nulls_distinct=False),
        ),
    ]
