# Generated by Django 5.2.15 on 2026-07-15 21:48

import django.db.models.deletion
import monitoring.secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_devicetype_owning_site_iprole_owning_site_and_more'),
        ('core', '0020_tag_tenant_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('override_email', models.BooleanField(default=False)),
                ('email_enabled', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_security', models.CharField(choices=[('none', 'None'), ('starttls', 'STARTTLS'), ('ssl', 'SSL/TLS')], default='starttls', max_length=8)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('email_from', models.CharField(blank=True, default='', max_length=255)),
                ('secrets', monitoring.secrets.EncryptedJSONField(blank=True, default=dict)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='api.site')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
