# Generated by Django 5.2.15 on 2026-07-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='ssrf_allowlist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
