# Generated by Django 5.2.15 on 2026-07-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_deploymentsettings_ssrf_allowlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='map_tile_attribution',
            field=models.CharField(blank=True, default='', help_text='Attribution HTML shown on the map (required by most tile providers). Blank = the OpenStreetMap attribution.', max_length=512),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='map_tile_url',
            field=models.URLField(blank=True, default='', help_text="Raster tile URL template with {z}/{x}/{y} placeholders. Blank = OpenStreetMap's standard tiles."),
        ),
    ]
