# Generated by Django 5.2.15 on 2026-07-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_deploymentsettings_map_tile_attribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='map_satellite_attribution',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='map_satellite_url',
            field=models.URLField(blank=True, default='', help_text='Satellite tile URL template ({z}/{x}/{y} or {z}/{y}/{x}). Blank = Esri World Imagery.'),
        ),
    ]
