# Generated by Django 5.2.15 on 2026-07-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_deploymentsettings_map_satellite_attribution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploymentsettings',
            name='allow_public_share_links',
        ),
        migrations.RemoveField(
            model_name='deploymentsettings',
            name='public_share_max_days',
        ),
        migrations.RemoveField(
            model_name='tenantsettings',
            name='allow_public_share_links',
        ),
        migrations.RemoveField(
            model_name='tenantsettings',
            name='public_share_max_days',
        ),
    ]
