# Generated by Django 5.2.15 on 2026-07-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_deploymentsettings_allow_public_share_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='disable_update_check',
            field=models.BooleanField(default=False),
        ),
    ]
