# Generated by Django 5.2.15 on 2026-07-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_deploymentsettings_disable_update_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='date_format',
            field=models.CharField(choices=[('YYYY-MM-DD', '2026-01-31 (ISO)'), ('DD.MM.YYYY', '31.01.2026'), ('DD/MM/YYYY', '31/01/2026'), ('MM/DD/YYYY', '01/31/2026'), ('DD MMM YYYY', '31 Jan 2026')], default='YYYY-MM-DD', help_text='How the UI renders calendar dates by default.', max_length=16),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='display_timezone',
            field=models.CharField(blank=True, default='', help_text="IANA timezone (e.g. Europe/Copenhagen) the UI renders times in. Blank = the server's TIME_ZONE.", max_length=64),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='time_style',
            field=models.CharField(choices=[('24h', '24-hour (14:30)'), ('12h', '12-hour (2:30 PM)')], default='24h', help_text='24-hour or 12-hour AM/PM clock for rendered times.', max_length=4),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='date_format',
            field=models.CharField(choices=[('YYYY-MM-DD', '2026-01-31 (ISO)'), ('DD.MM.YYYY', '31.01.2026'), ('DD/MM/YYYY', '31/01/2026'), ('MM/DD/YYYY', '01/31/2026'), ('DD MMM YYYY', '31 Jan 2026')], default='YYYY-MM-DD', max_length=16),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='display_timezone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='override_datetime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='time_style',
            field=models.CharField(choices=[('24h', '24-hour (14:30)'), ('12h', '12-hour (2:30 PM)')], default='24h', max_length=4),
        ),
    ]
