# Generated by Django 5.2.15 on 2026-07-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_deploymentsettings_date_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Custom browser-tab icon for this install. Blank = the default Danbyte icon. A small square PNG/ICO works best.', null=True, upload_to='branding/'),
        ),
    ]
