# Generated by Django 5.2.15 on 2026-07-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_deploymentsettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='digest_enabled',
            field=models.BooleanField(default=False, help_text='Email a periodic monitoring/status digest to the recipients below.'),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='digest_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='weekly', max_length=8),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='digest_recipients',
            field=models.TextField(blank=True, default='', help_text='Digest recipients — comma/newline-separated email addresses.'),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='digest_weekday',
            field=models.PositiveSmallIntegerField(default=0, help_text='Day to send the weekly digest (0=Monday … 6=Sunday).'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='digest_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='digest_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='weekly', max_length=8),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='digest_last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='digest_recipients',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='digest_weekday',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='override_digest',
            field=models.BooleanField(default=False),
        ),
    ]
