# Generated by Django 5.2.15 on 2026-07-21 12:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_deploymentsettings_digest_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(help_text="Task key, e.g. 'digest'.", max_length=64)),
                ('label', models.CharField(help_text='Human task name.', max_length=120)),
                ('status', models.CharField(choices=[('running', 'Running'), ('ok', 'OK'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='running', max_length=8)),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['name', '-started_at'], name='core_schedu_name_47dbc7_idx')],
            },
        ),
    ]
