# Generated by Django 5.2.15 on 2026-07-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_scheduledrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='rq_workers',
            field=models.PositiveSmallIntegerField(default=8),
        ),
    ]
