# Generated by Django 5.2.15 on 2026-07-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_deploymentsettings_rq_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='secrets_provider',
            field=models.CharField(blank=True, choices=[('', 'Disabled'), ('local', 'Local (encrypted)'), ('vault', 'Vault / OpenBao')], default='', help_text='Where issuance private keys (CSR, ACME) are stored. Blank leaves those features disabled.', max_length=16),
        ),
    ]
