# Generated by Django 5.2.15 on 2026-07-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_deploymentsettings_secrets_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='vault_addr',
            field=models.CharField(blank=True, default='', help_text='Vault/OpenBao base URL, e.g. https://vault.danbyte.lan:8200.', max_length=255),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='vault_mount',
            field=models.CharField(blank=True, default='danbyte', help_text='KV v2 mount path secrets are written under.', max_length=64),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='vault_verify_tls',
            field=models.BooleanField(default=True),
        ),
    ]
