# Generated by Django 5.2.16 on 2026-07-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_deploymentsettings_vault_addr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='onboarding_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
