# Generated by Django 5.2.16 on 2026-08-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_tenantsettings_onboarding_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='ssh_terminal_enabled',
            field=models.BooleanField(default=False, help_text="Allow the in-browser SSH terminal. Off by default: enabling it lets holders of the device 'connect' verb open a shell to a device through Danbyte. Sessions verify the host key and are audited."),
        ),
    ]
