# Generated by Django 5.2.16 on 2026-08-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_deploymentsettings_ssh_terminal_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='session_idle_timeout_minutes',
            field=models.PositiveIntegerField(default=120, help_text='Log inactive users out after this many minutes. 0 = no idle timeout. Default 120 (2 hours).'),
        ),
    ]
