# Generated by Django 5.2.16 on 2026-08-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_deploymentsettings_session_idle_timeout_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='cert_digest_enabled',
            field=models.BooleanField(default=False, help_text='Email a periodic certificate-expiry digest, separate from the monitoring digest.'),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='cert_digest_recipients',
            field=models.TextField(blank=True, default='', help_text='Certificate-digest recipients. Blank uses the digest recipients above.'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='cert_digest_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='cert_digest_last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='cert_digest_recipients',
            field=models.TextField(blank=True, default=''),
        ),
    ]
