# Generated by Django 5.2.16 on 2026-08-13 16:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_deploymentsettings_cert_digest_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('query', models.JSONField(blank=True, default=dict)),
                ('shared', models.BooleanField(default=False, help_text='Visible to everyone in this tenant, not just you.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to='core.tenant')),
            ],
            options={
                'ordering': ['object_type', 'name'],
                'indexes': [models.Index(fields=['tenant', 'object_type'], name='core_savedf_tenant__35b55b_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'object_type', 'created_by', 'name'), name='uniq_saved_filter_name_per_owner')],
            },
        ),
    ]
