# Generated by Django 5.2.16 on 2026-08-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='component_popover_fields',
            field=models.JSONField(blank=True, default=list, help_text='Ordered field keys shown when hovering a port on a device faceplate. Empty = built-in defaults (name, type, state, VLAN, live, IPs).'),
        ),
    ]
