# Generated by Django 5.2.16 on 2026-08-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_deploymentsettings_component_popover_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='hide_update_badge',
            field=models.BooleanField(default=False),
        ),
    ]
