# Generated by Django 5.2.16 on 2026-08-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_deploymentsettings_hide_update_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='default_dashboard_widgets',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
