# Generated by Django 5.2.16 on 2026-08-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_tenantsettings_default_dashboard_widgets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentsettings',
            name='allow_site_editor_delegation',
            field=models.BooleanField(default=False, help_text='When on, a site editor (local IT) may invite their own viewers to the site(s) they edit - without a global admin.'),
        ),
        migrations.AlterField(
            model_name='deploymentsettings',
            name='allow_site_settings',
            field=models.BooleanField(default=False, help_text="When on, site admins (site editors, or holders of a sitesettings grant) may manage their own site's settings - e.g. email delivery."),
        ),
        migrations.AlterField(
            model_name='deploymentsettings',
            name='deployment_name',
            field=models.CharField(blank=True, default='', help_text='Display name for this install - the app name shown in the sidebar header, the browser tab title, and the login page. Blank = "Danbyte".', max_length=100),
        ),
        migrations.AlterField(
            model_name='deploymentsettings',
            name='digest_recipients',
            field=models.TextField(blank=True, default='', help_text='Digest recipients - comma/newline-separated email addresses.'),
        ),
        migrations.AlterField(
            model_name='deploymentsettings',
            name='floorplan_popover_tile_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Per-tile-type popover field lists, keyed by tile-type slug. A slug that is ABSENT inherits floorplan_popover_fields - only store a list for types that genuinely differ.'),
        ),
        migrations.AlterField(
            model_name='deploymentsettings',
            name='human_ids_enabled',
            field=models.BooleanField(default=True, help_text="When on, objects expose a short per-tenant sequential number (numid) alongside their UUID - e.g. so a cable physically tagged '27' maps to cable #27. Numbers are namespaced per tenant, so each tenant counts from 1 independently."),
        ),
    ]
