# Generated by Django 5.2.16 on 2026-08-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_text_hyphens'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='login_logo',
            field=models.ImageField(blank=True, help_text='Custom logo shown on the login page. Blank = the Danbyte logo. A wide transparent PNG works best.', null=True, upload_to='branding/'),
        ),
    ]
