# Generated by Django 5.2.16 on 2026-08-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_login_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='hide_local_login',
            field=models.BooleanField(default=False, help_text='Hide the username/password form on the login page when SSO providers exist. Local and LDAP sign-in stay reachable via a link.'),
        ),
    ]
