# Generated by Django 5.2.16 on 2026-09-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_hide_local_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='faceplate_mark_connected_lit',
            field=models.BooleanField(default=False, help_text='Faceplates and photo ports light up ports marked connected like cabled ones.'),
        ),
    ]
