# Generated by Django 5.2.16 on 2026-09-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_deploymentsettings_faceplate_group_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentsettings',
            name='secrets_provider',
            field=models.CharField(blank=True, default='', help_text='Where issuance private keys (CSR, ACME) are stored. Blank leaves those features disabled.', max_length=32),
        ),
    ]
