# Generated by Django 5.2.16 on 2026-09-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_deploymentsettings_upgrade_notes_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='ai_base_url',
            field=models.CharField(blank=True, default='', help_text="Blank uses the provider's own endpoint; set it for a gateway or a local model server.", max_length=255),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='ai_model',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='ai_provider',
            field=models.CharField(blank=True, default='', help_text='anthropic, openai (any OpenAI-compatible API) or local. Blank leaves the in-app assistant unconfigured.', max_length=16),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='ai_verify_tls',
            field=models.BooleanField(default=True),
        ),
    ]
