# Generated by Django 5.2.16 on 2026-09-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_deploymentsettings_ai_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='azure_authority',
            field=models.CharField(blank=True, default='', help_text='Sign-in endpoint. Blank uses login.microsoftonline.com; set it for Azure Government or another sovereign cloud.', max_length=255),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='azure_client_id',
            field=models.CharField(blank=True, default='', help_text='Application (client) ID of the app registration.', max_length=64),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='azure_directory_id',
            field=models.CharField(blank=True, default='', help_text='Entra ID directory (tenant) ID the app registration lives in.', max_length=64),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='azure_vault_url',
            field=models.CharField(blank=True, default='', help_text='Key Vault URL, e.g. https://kv-danbyte.vault.azure.net.', max_length=255),
        ),
    ]
