# Generated by Django 5.2.16 on 2026-09-12 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_deploymentsettings_azure_authority_and_more'),
        ('monitoring', '0093_fast_lane'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('none', 'Not managed here'), ('upload', 'Uploaded'), ('self-signed', 'Self-signed'), ('acme', 'ACME')], default='none', max_length=16)),
                ('auto_renew', models.BooleanField(default=True)),
                ('names', models.JSONField(blank=True, default=list)),
                ('dropped_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('dropped_at', models.DateTimeField(blank=True, null=True)),
                ('dropped_reason', models.CharField(blank=True, default='', max_length=200)),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitoring.issuer')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitoring.certificaterequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'site certificate',
            },
        ),
    ]
