# Generated by Django 5.2.16 on 2026-09-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_sitecertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='faceplate_port_label_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Text colour of the port labels (#rrggbb).', max_length=7),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='faceplate_port_labels',
            field=models.CharField(blank=True, choices=[('', 'Off'), ('interface', 'Port label'), ('cable', 'Cable label'), ('peer_device', 'Far-end device'), ('peer_port', 'Far-end port label')], default='', help_text='What faceplates, photo panels and the 3D room print inside each port marker; blank prints nothing.', max_length=16),
        ),
    ]
