# Generated by Django 5.2.16 on 2026-09-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_faceplate_port_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='log_retention_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Days to keep rotated log files in the log directory. 0 = keep forever.'),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='upgrade_backups_keep',
            field=models.PositiveSmallIntegerField(default=3, help_text='Before-upgrade backups and code rollback archives to keep. Older ones are deleted after each upgrade and daily.'),
        ),
    ]
