# Generated by Django 5.2.16 on 2026-09-24 07:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0054_housekeeping_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('visibility', models.CharField(choices=[('private', 'Only me'), ('tenant', 'Everyone in the tenant'), ('groups', 'Chosen groups')], default='private', max_length=8)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('frame', models.CharField(choices=[('24h', '24 hours'), ('7d', '7 days'), ('30d', '30 days'), ('90d', '90 days')], default='7d', max_length=4)),
                ('refresh_seconds', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, related_name='dashboards', to='auth.group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'owner'], name='core_dashbo_tenant__470a5e_idx')],
            },
        ),
    ]
