# Generated by Django 5.2.16 on 2026-09-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_dashboards'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='topology_card_fields',
            field=models.JSONField(blank=True, default=None, help_text='Ordered field keys a topology Diagram card shows under the device name. Null = the built-in default; an empty list = name only.', null=True),
        ),
        migrations.AddField(
            model_name='deploymentsettings',
            name='topology_card_role_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Per-role card-line lists keyed role:<slug>. A role that is ABSENT inherits topology_card_fields; an empty list = name only.'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='override_topology_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='topology_card_fields',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='topology_card_role_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
