# Generated by Django 5.2.16 on 2026-09-30 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0183_ip_monitoring_exclude_reset'),
        ('core', '0056_topology_card_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='default_topology_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.topologyview'),
        ),
    ]
