# Generated by Django 5.2.16 on 2026-10-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_tenantsettings_default_topology_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsettings',
            name='port_count_virtual',
            field=models.BooleanField(db_default=False, default=False, help_text='Port utilization counts virtual interfaces (SVIs, LAGs, loopbacks, tunnels) as ports.'),
        ),
    ]
