# Generated by Django 5.2.16 on 2026-10-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_deploymentsettings_port_count_virtual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentsettings',
            name='faceplate_port_label_color',
            field=models.CharField(blank=True, db_default='#ffffff', default='#ffffff', help_text='Text colour of the port labels (#rrggbb).', max_length=7),
        ),
        migrations.AlterField(
            model_name='deploymentsettings',
            name='faceplate_port_labels',
            field=models.CharField(blank=True, choices=[('', 'Off'), ('interface', 'Port label'), ('cable', 'Cable label'), ('peer_device', 'Far-end device'), ('peer_port', 'Far-end port label')], db_default='', default='', help_text='What faceplates, photo panels and the 3D room print inside each port marker; blank prints nothing.', max_length=16),
        ),
        migrations.AlterField(
            model_name='deploymentsettings',
            name='log_retention_days',
            field=models.PositiveSmallIntegerField(db_default=30, default=30, help_text='Days to keep rotated log files in the log directory. 0 = keep forever.'),
        ),
        migrations.AlterField(
            model_name='deploymentsettings',
            name='topology_card_role_overrides',
            field=models.JSONField(blank=True, db_default=models.Value({}, models.JSONField()), default=dict, help_text='Per-role card-line lists keyed role:<slug>. A role that is ABSENT inherits topology_card_fields; an empty list = name only.'),
        ),
        migrations.AlterField(
            model_name='deploymentsettings',
            name='upgrade_backups_keep',
            field=models.PositiveSmallIntegerField(db_default=3, default=3, help_text='Before-upgrade backups and code rollback archives to keep. Older ones are deleted after each upgrade and daily.'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='override_topology_card',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='topology_card_role_overrides',
            field=models.JSONField(blank=True, db_default=models.Value({}, models.JSONField()), default=dict),
        ),
    ]
