# Generated by Django 5.2.16 on 2026-10-10 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_upgrade_db_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='capacity_critical_pct',
            field=models.PositiveSmallIntegerField(db_default=95, default=95, help_text='Above this share a rack is full.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='capacity_warn_pct',
            field=models.PositiveSmallIntegerField(db_default=80, default=80, help_text='Above this share of capacity a rack is filling up.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
