# Generated by Django 5.2.15 on 2026-06-14 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_id', models.CharField(help_text="The data-cols-table-id slug, e.g. 'prefix-ips'.", max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, help_text='NULL = this row is a tenant-wide default published by an admin.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['table_id', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'tenant', 'table_id'), name='uniq_pref_user_tenant_table', nulls_distinct=False)],
            },
        ),
    ]
