# Generated by Django 5.2.15 on 2026-06-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_userpreference'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tenants',
            field=models.ManyToManyField(blank=True, help_text='Tenants this user can switch to and operate within. Admins and superusers ignore this list — they see every tenant. Empty list on a reader/custom user means no tenant access at all.', related_name='users', to='core.tenant'),
        ),
    ]
