# Generated by Django 5.2.15 on 2026-06-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_userprofile_tenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='prefs',
            field=models.JSONField(blank=True, default=dict, help_text='Free-form user preferences blob (theme, density, default page size, confirm-before-delete, etc.). The settings page writes here; UI code reads via auth_api.user_prefs.get().'),
        ),
    ]
