# Generated by Django 5.2.15 on 2026-06-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0004_userprofile_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='forced',
            field=models.BooleanField(default=False, help_text="Only meaningful on a tenant-default row (user=NULL). When True the layout is locked: users can't override it, their own row is ignored, and the UI disables the column controls. Ignored on a per-user row."),
        ),
    ]
