# Generated by Django 5.2.15 on 2026-06-24 21:35

import django.db.models.deletion
import monitoring.secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_api', '0005_userpreference_forced'),
        ('core', '0005_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth_source',
            field=models.CharField(choices=[('local', 'Local'), ('ldap', 'LDAP')], default='local', help_text='Where this account authenticates. LDAP accounts are auto-provisioned on first login.', max_length=8),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mfa_email',
            field=models.BooleanField(default=True, help_text='Allow email one-time codes as a second factor.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mfa_totp_confirmed',
            field=models.BooleanField(default=False, help_text='The user has set up and verified an authenticator app.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='require_mfa',
            field=models.BooleanField(default=False, help_text='Force a second factor (email code or authenticator) at login.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secrets',
            field=monitoring.secrets.EncryptedJSONField(blank=True, default=dict, help_text='Encrypted-at-rest blob — currently the TOTP secret.'),
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('built_in', models.BooleanField(default=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group')),
            ],
            options={
                'ordering': ['group__name'],
            },
        ),
        migrations.CreateModel(
            name='ObjectPermission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('object_types', models.JSONField(default=list, help_text='Object-type slugs this permission covers (see object_types registry).')),
                ('actions', models.JSONField(default=list, help_text='Subset of [view, add, change, delete].')),
                ('constraints', models.JSONField(blank=True, help_text="Queryset filter limiting which rows. A dict, or a list of dicts OR'd together. Null/empty = all rows.", null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='object_permissions', to='auth.group')),
                ('tenants', models.ManyToManyField(blank=True, help_text='Tenants this permission applies within. Empty = every tenant the user can access.', related_name='object_permissions', to='core.tenant')),
                ('users', models.ManyToManyField(blank=True, related_name='object_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
