# Generated by Django 5.2.15 on 2026-06-24 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_api', '0007_seed_rbac'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPGroupMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ldap_group_dn', models.CharField(help_text='Full DN of the directory group, e.g. CN=Network Admins,OU=Groups,DC=acme,DC=local.', max_length=512, unique=True)),
                ('ldap_group_cn', models.CharField(blank=True, default='', help_text='Common name, for display only.', max_length=255)),
                ('group', models.ForeignKey(help_text='The Danbyte group whose permissions members receive.', on_delete=django.db.models.deletion.CASCADE, related_name='ldap_mappings', to='auth.group')),
            ],
            options={
                'ordering': ['ldap_group_cn', 'ldap_group_dn'],
            },
        ),
    ]
