# Generated by Django 5.2.15 on 2026-06-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_ipaddress_site_prefix_auto_assign_site_and_more'),
        ('auth_api', '0009_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectpermission',
            name='sites',
            field=models.ManyToManyField(blank=True, help_text='Sites this permission is scoped to. Empty = all sites. Only object types with a site (device, prefix, IP, rack, …) are narrowed; types without a site ignore it.', related_name='object_permissions', to='api.site'),
        ),
    ]
