# Generated by Django 5.2.15 on 2026-06-27 09:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def generate_share_token():
    # Historical placeholder — the PublicShareLink model was removed (the
    # public-share feature was deleted); this default is never invoked, it only
    # needs to exist so this already-applied migration still imports.
    return ""


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0010_objectpermission_sites'),
        ('core', '0007_deploymentsettings_allow_public_share_links_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicShareLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, default=generate_share_token, editable=False, max_length=64, unique=True)),
                ('object_type', models.CharField(max_length=64)),
                ('object_id', models.UUIDField()),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_links', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
