# Generated by Django 5.2.15 on 2026-06-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0011_publicsharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicsharelink',
            name='snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicsharelink',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
