# Generated by Django 5.2.15 on 2026-07-11 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_api', '0012_publicsharelink_snapshot_and_more'),
        ('core', '0014_tenantsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapgroupmapping',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ldap_group_mappings', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ldap_source_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='ldapgroupmapping',
            name='ldap_group_dn',
            field=models.CharField(help_text='Full DN of the directory group, e.g. CN=Network Admins,OU=Groups,DC=acme,DC=local.', max_length=512),
        ),
        migrations.AddConstraint(
            model_name='ldapgroupmapping',
            constraint=models.UniqueConstraint(fields=('tenant', 'ldap_group_dn'), name='uniq_ldap_mapping_tenant_dn', nulls_distinct=False),
        ),
    ]
