# Generated by Django 5.2.15 on 2026-07-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0013_ldapgroupmapping_tenant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicShareLink',
        ),
    ]
