# Generated by Django 5.2.16 on 2026-08-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0014_delete_publicsharelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectpermission',
            name='actions',
            field=models.JSONField(default=list, help_text='Subset of [view, add, change, delete, connect, reveal].'),
        ),
    ]
