# Generated by Django 5.2.16 on 2026-08-01 14:57

import django.db.models.deletion
import monitoring.secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_api', '0015_alter_objectpermission_actions'),
        ('core', '0035_deploymentsettings_ssh_terminal_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Shown on the login button.', max_length=120)),
                ('slug', models.SlugField(help_text='URL-safe id used in the callback path; stable once created.', max_length=64, unique=True)),
                ('protocol', models.CharField(choices=[('oidc', 'OpenID Connect'), ('saml', 'SAML 2.0')], max_length=8)),
                ('enabled', models.BooleanField(default=True)),
                ('oidc_issuer', models.CharField(blank=True, default='', help_text='Issuer URL; its /.well-known/openid-configuration is read. For Entra: https://login.microsoftonline.com/<tenant-id>/v2.0', max_length=255)),
                ('oidc_client_id', models.CharField(blank=True, default='', max_length=255)),
                ('oidc_scopes', models.CharField(blank=True, default='openid email profile', max_length=255)),
                ('saml_idp_entity_id', models.CharField(blank=True, default='', max_length=255)),
                ('saml_idp_sso_url', models.CharField(blank=True, default='', max_length=255)),
                ('saml_idp_x509', models.TextField(blank=True, default='')),
                ('claim_email', models.CharField(blank=True, default='email', max_length=64)),
                ('claim_username', models.CharField(blank=True, default='preferred_username', max_length=64)),
                ('claim_first_name', models.CharField(blank=True, default='given_name', max_length=64)),
                ('claim_last_name', models.CharField(blank=True, default='family_name', max_length=64)),
                ('claim_groups', models.CharField(blank=True, default='groups', max_length=64)),
                ('jit_provisioning', models.BooleanField(default=True, help_text='Create users on first login. Off = only pre-created users may sign in; unknown users are refused.')),
                ('secrets', monitoring.secrets.EncryptedJSONField(blank=True, default=dict)),
                ('default_tenant', models.ForeignKey(blank=True, help_text="Tenant a JIT-created user is granted access to. Defaults to this provider's tenant when it is tenant-scoped.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.tenant')),
                ('tenant', models.ForeignKey(blank=True, help_text='NULL = available to everyone (deployment-wide).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identity_providers', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SsoGroupMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idp_group', models.CharField(help_text='The group/role value the IdP asserts (name or object id).', max_length=512)),
                ('group', models.ForeignKey(help_text='The Danbyte group whose permissions members receive.', on_delete=django.db.models.deletion.CASCADE, related_name='sso_mappings', to='auth.group')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_mappings', to='auth_api.identityprovider')),
            ],
            options={
                'ordering': ['idp_group'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'idp_group'), name='uniq_sso_mapping_provider_group')],
            },
        ),
    ]
