# Generated by Django 5.2.16 on 2026-08-01 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_api', '0016_identityprovider_ssogroupmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprovider',
            name='default_group',
            field=models.ForeignKey(blank=True, help_text="Baseline Danbyte group every user of this provider gets on login (in addition to any group mappings), so a new SSO user isn't left with no access. Leave empty to grant nothing but the mappings.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.group'),
        ),
    ]
