# Generated by Django 5.2.16 on 2026-08-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0017_identityprovider_default_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprovider',
            name='saml_idp_metadata_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
