# Generated by Django 5.2.16 on 2026-08-01 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0018_identityprovider_saml_idp_metadata_url'),
        ('core', '0035_deploymentsettings_ssh_terminal_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SamlLoginState',
            fields=[
                ('request_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sso_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth_api.identityprovider'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sso_subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='auth_source',
            field=models.CharField(choices=[('local', 'Local'), ('ldap', 'LDAP'), ('sso', 'SSO')], default='local', help_text='Where this account authenticates. LDAP/SSO accounts are auto-provisioned on first login.', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('sso_subject__gt', '')), fields=('sso_provider', 'sso_subject'), name='uniq_sso_provider_subject'),
        ),
        migrations.AddField(
            model_name='samlloginstate',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth_api.identityprovider'),
        ),
        migrations.AddIndex(
            model_name='samlloginstate',
            index=models.Index(fields=['created_at'], name='auth_api_sa_created_1aa9d7_idx'),
        ),
    ]
