# Generated by Django 5.2.16 on 2026-08-19 21:34

import monitoring.secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0019_samlloginstate_userprofile_sso_provider_and_more'),
        ('core', '0043_text_hyphens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader - view only'), ('admin', 'Admin - full access'), ('custom', 'Custom - pick permissions')], default='reader', help_text='Reader can only view data. Admin can do everything. Custom uses the per-permission list below.', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='secrets',
            field=monitoring.secrets.EncryptedJSONField(blank=True, default=dict, help_text='Encrypted-at-rest blob - currently the TOTP secret.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tenants',
            field=models.ManyToManyField(blank=True, help_text='Tenants this user can switch to and operate within. Admins and superusers ignore this list - they see every tenant. Empty list on a reader/custom user means no tenant access at all.', related_name='users', to='core.tenant'),
        ),
    ]
