# Generated by Django 5.2.16 on 2026-08-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0020_text_hyphens'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssogroupmapping',
            name='grants_superuser',
            field=models.BooleanField(default=False, help_text='Members of this IdP group become Danbyte superusers on login. Grant-only: removal from the group never strips the flag - revoke manually on the user. Ignored (with a log warning) on tenant-scoped providers.'),
        ),
    ]
