# Generated by Django 5.2.16 on 2026-09-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0021_ssogroupmapping_grants_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='kind',
            field=models.CharField(choices=[('user', 'User'), ('run', 'Run')], default='user', max_length=8),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='scope',
            field=models.CharField(choices=[('full', 'Full'), ('read', 'Read only')], default='full', max_length=8),
        ),
    ]
