# Generated by Django 5.2.16 on 2026-09-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0022_apitoken_scope_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapgroupmapping',
            name='grants_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
