# Generated by Django 5.2.16 on 2026-10-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0026_split_kept_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='totp_last_used_step',
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
    ]
