# Generated by Django 5.2.15 on 2026-07-21 07:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0028_deploymentsettings_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plugin_slug', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plugin_configs', to='core.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'plugin_slug'), name='uniq_pluginconfig_tenant_slug', nulls_distinct=False)],
            },
        ),
    ]
