# Generated by Django 5.2.15 on 2026-06-14 19:02

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='cable',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cables', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='device',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='device',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_types', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.devicetype'),
        ),
        migrations.AddField(
            model_name='interface',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='api.device'),
        ),
        migrations.AddField(
            model_name='interface',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='cable',
            name='from_interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cables_from', to='api.interface'),
        ),
        migrations.AddField(
            model_name='cable',
            name='to_interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cables_to', to='api.interface'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='prefix',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='prefix',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefixes', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='prefix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='api.prefix'),
        ),
        migrations.AddField(
            model_name='site',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='site',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='prefix',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefixes', to='api.site'),
        ),
        migrations.AddField(
            model_name='device',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.site'),
        ),
        migrations.AddField(
            model_name='vlan',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.site'),
        ),
        migrations.AddField(
            model_name='vlan',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='vlan',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlans', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='prefix',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefixes', to='api.vlan'),
        ),
        migrations.AddField(
            model_name='interface',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vlan'),
        ),
        migrations.AddField(
            model_name='vrf',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vrfs', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='site',
            name='vrfs',
            field=models.ManyToManyField(blank=True, help_text='Which VRFs operate at this site. Documentation only — not enforced.', related_name='sites', to='api.vrf'),
        ),
        migrations.AddField(
            model_name='prefix',
            name='vrf',
            field=models.ForeignKey(blank=True, help_text='Routing context. NULL = Global VRF.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prefixes', to='api.vrf'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='vrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ip_addresses', to='api.vrf'),
        ),
        migrations.AlterUniqueTogether(
            name='devicetype',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['tenant', 'name'], name='api_device_tenant__855a62_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['tenant', 'device_type'], name='api_device_tenant__761d85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='vlan',
            unique_together={('tenant', 'vlan_id')},
        ),
        migrations.AlterUniqueTogether(
            name='interface',
            unique_together={('device', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='vrf',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='prefix',
            index=models.Index(fields=['tenant', 'status'], name='api_prefix_tenant__fbd674_idx'),
        ),
        migrations.AddIndex(
            model_name='prefix',
            index=models.Index(fields=['tenant', 'site'], name='api_prefix_tenant__b5b11d_idx'),
        ),
        migrations.AddIndex(
            model_name='prefix',
            index=models.Index(fields=['tenant', 'vrf'], name='api_prefix_tenant__b0fe22_idx'),
        ),
        migrations.AddConstraint(
            model_name='prefix',
            constraint=models.UniqueConstraint(fields=('tenant', 'vrf', 'cidr'), name='uniq_prefix_tenant_vrf_cidr', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='ipaddress',
            constraint=models.UniqueConstraint(fields=('tenant', 'vrf', 'ip_address'), name='uniq_ip_tenant_vrf_addr', nulls_distinct=False),
        ),
    ]
