# Generated by Django 5.2.15 on 2026-06-22 15:54

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_devices'),
        ('core', '0002_tenant_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='routetarget',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='User-defined custom fields'),
        ),
        migrations.AddField(
            model_name='routetarget',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='vrf',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='User-defined custom fields'),
        ),
        migrations.AddField(
            model_name='vrf',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
    ]
