# Generated by Django 5.2.15 on 2026-06-22 22:23
# Hand-edited: reordered so the old from/to FKs survive until after
# CableTermination exists, with a pre-flight check + data conversion before they
# are dropped.

import django.db.models.deletion
import taggit.managers
import uuid
from collections import Counter

from django.db import migrations, models


def convert_cables_to_terminations(apps, schema_editor):
    """Turn each binary Cable (from_interface ↔ to_interface) into two
    CableTermination rows (A = from, B = to). Fails loud if any interface
    terminates more than one cable — that violates the one-cable-per-port rule
    and must be resolved by hand first."""
    Cable = apps.get_model("api", "Cable")
    CableTermination = apps.get_model("api", "CableTermination")

    rows = list(Cable.objects.all().only("id", "from_interface_id", "to_interface_id"))
    counts = Counter()
    for c in rows:
        if c.from_interface_id:
            counts[c.from_interface_id] += 1
        if c.to_interface_id:
            counts[c.to_interface_id] += 1
    dups = [iid for iid, n in counts.items() if n > 1]
    if dups:
        raise RuntimeError(
            f"Cannot migrate cabling: {len(dups)} interface(s) terminate more "
            f"than one cable, which the new one-cable-per-port model forbids. "
            f"Offending interface ids: {', '.join(str(d) for d in dups[:10])}"
            f"{' …' if len(dups) > 10 else ''}. Remove the duplicate cabling, "
            f"then re-run the migration."
        )

    terms = []
    for c in rows:
        if c.from_interface_id:
            terms.append(CableTermination(cable_id=c.id, end="A", interface_id=c.from_interface_id))
        if c.to_interface_id and c.to_interface_id != c.from_interface_id:
            terms.append(CableTermination(cable_id=c.id, end="B", interface_id=c.to_interface_id))
    CableTermination.objects.bulk_create(terms)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_routetarget_custom_fields_routetarget_tags_and_more'),
        ('core', '0002_tenant_prefs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cable',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='cable',
            name='color',
            field=models.CharField(blank=True, default='', help_text="Optional 7-char hex — the physical cable's color.", max_length=7),
        ),
        migrations.AddField(
            model_name='cable',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cable',
            name='length_unit',
            field=models.CharField(blank=True, choices=[('m', 'Meters'), ('cm', 'Centimeters'), ('ft', 'Feet'), ('in', 'Inches')], default='m', max_length=2),
        ),
        migrations.AddField(
            model_name='cable',
            name='status',
            field=models.CharField(choices=[('connected', 'Connected'), ('planned', 'Planned'), ('decommissioning', 'Decommissioning')], default='connected', max_length=20),
        ),
        migrations.AddField(
            model_name='cable',
            name='type',
            field=models.CharField(blank=True, help_text='Free-form medium, e.g. cat6 / dac / smf / mmf.', max_length=64),
        ),
        migrations.CreateModel(
            name='RearPort',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('positions', models.PositiveSmallIntegerField(default=1, help_text='Number of strands / front-port positions.')),
                ('type', models.CharField(blank=True, max_length=64)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rear_ports', to='api.device')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('device', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FrontPort',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('rear_port_position', models.PositiveSmallIntegerField(default=1)),
                ('type', models.CharField(blank=True, max_length=64)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='front_ports', to='api.device')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('rear_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='front_ports', to='api.rearport')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CableTermination',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('end', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminations', to='api.cable')),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminations', to='api.interface')),
                ('front_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminations', to='api.frontport')),
                ('rear_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminations', to='api.rearport')),
            ],
            options={
                'ordering': ['end'],
            },
        ),
        migrations.AddConstraint(
            model_name='frontport',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='uniq_frontport_device_name'),
        ),
        migrations.AddConstraint(
            model_name='frontport',
            constraint=models.UniqueConstraint(fields=('rear_port', 'rear_port_position'), name='uniq_frontport_rear_position'),
        ),
        migrations.AddIndex(
            model_name='cabletermination',
            index=models.Index(fields=['cable', 'end'], name='api_cablete_cable_i_d7243c_idx'),
        ),
        migrations.AddConstraint(
            model_name='cabletermination',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('front_port__isnull', True), ('interface__isnull', False), ('rear_port__isnull', True)), models.Q(('front_port__isnull', False), ('interface__isnull', True), ('rear_port__isnull', True)), models.Q(('front_port__isnull', True), ('interface__isnull', True), ('rear_port__isnull', False)), _connector='OR'), name='cabletermination_exactly_one_point'),
        ),
        migrations.AddConstraint(
            model_name='cabletermination',
            constraint=models.UniqueConstraint(condition=models.Q(('interface__isnull', False)), fields=('interface',), name='uniq_termination_interface'),
        ),
        migrations.AddConstraint(
            model_name='cabletermination',
            constraint=models.UniqueConstraint(condition=models.Q(('front_port__isnull', False)), fields=('front_port',), name='uniq_termination_front_port'),
        ),
        migrations.AddConstraint(
            model_name='cabletermination',
            constraint=models.UniqueConstraint(condition=models.Q(('rear_port__isnull', False)), fields=('rear_port',), name='uniq_termination_rear_port'),
        ),
        # Convert existing binary cables → terminations (needs from/to still present).
        migrations.RunPython(convert_cables_to_terminations, migrations.RunPython.noop),
        # Only now drop the legacy FKs.
        migrations.RemoveField(
            model_name='cable',
            name='from_interface',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='to_interface',
        ),
    ]
