# Generated by Django 5.2.15 on 2026-06-22 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_cable_options_remove_cable_from_interface_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='mac_address',
            field=models.CharField(blank=True, help_text='Layer-2 hardware address, e.g. 00:1b:44:11:3a:b7.', max_length=17),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='assigned_interface',
            field=models.ForeignKey(blank=True, help_text="Specific interface this IP is bound to. Setting it also keeps assigned_device in sync with the interface's device.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_addresses', to='api.interface'),
        ),
    ]
