# Generated by Django 5.2.15 on 2026-06-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_interface_mac_address_ipaddress_assigned_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='mac_address',
            field=models.CharField(blank=True, help_text="Hardware address paired with this IP — e.g. a DHCP reservation. Independent of the interface's own MAC.", max_length=17),
        ),
    ]
