# Generated by Django 5.2.15 on 2026-06-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_ipaddress_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='discovered',
            field=models.BooleanField(default=False, help_text='Auto-created by subnet discovery (vs. entered by a user). Only discovered IPs are eligible for stale auto-cleanup.'),
        ),
        migrations.AddField(
            model_name='prefix',
            name='auto_discover',
            field=models.BooleanField(default=False, help_text='Opt in to periodic ICMP discovery — responders not yet recorded are auto-created as IPs (see monitoring settings).'),
        ),
    ]
