# Generated by Django 5.2.15 on 2026-06-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_ipaddress_discovered_prefix_auto_discover'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='flap_exclude',
            field=models.BooleanField(default=False, help_text="Exclude this IP from the flapping monitor — for a known noisy host you don't want flagged."),
        ),
    ]
