# Generated by Django 5.2.15 on 2026-06-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_ipaddress_flap_exclude'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefix',
            name='last_discovered_at',
            field=models.DateTimeField(blank=True, help_text='Last time discovery swept this prefix. Engine-set; gates the discovery interval.', null=True),
        ),
    ]
