# Generated by Django 5.2.15 on 2026-06-24 16:16

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_virtualmachine'),
        ('core', '0005_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='assigned_vm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_addresses', to='api.virtualmachine'),
        ),
        migrations.CreateModel(
            name='VMInterface',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('mtu', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='api.virtualmachine')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='assigned_vm_interface',
            field=models.ForeignKey(blank=True, help_text='Specific VM interface this IP is bound to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_addresses', to='api.vminterface'),
        ),
        migrations.AddConstraint(
            model_name='vminterface',
            constraint=models.UniqueConstraint(fields=('vm', 'name'), name='uniq_vminterface_vm_name'),
        ),
    ]
