# Generated by Django 5.2.15 on 2026-06-24 17:19

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_ipaddress_assigned_vm_vminterface_and_more'),
        ('core', '0005_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='face',
            field=models.CharField(blank=True, choices=[('front', 'Front'), ('rear', 'Rear')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='device',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Lowest rack unit (U) this device occupies.', null=True),
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('facility_id', models.CharField(blank=True, default='', help_text="The rack's ID in the facility (e.g. row/position label).", max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('reserved', 'Reserved'), ('available', 'Available'), ('deprecated', 'Deprecated')], default='active', max_length=20)),
                ('width', models.PositiveSmallIntegerField(choices=[(10, '10"'), (19, '19"'), (21, '21"'), (23, '23"')], default=19, help_text='Rail-to-rail width, inches.')),
                ('u_height', models.PositiveSmallIntegerField(default=42, help_text='Height in rack units (U).')),
                ('starting_unit', models.PositiveSmallIntegerField(default=1, help_text='Number of the bottom unit.')),
                ('desc_units', models.BooleanField(default=False, help_text='Number units top-to-bottom instead of bottom-up.')),
                ('description', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='racks', to='api.site')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='core.tenant')),
            ],
            options={
                'ordering': ['site__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='api.rack'),
        ),
        migrations.CreateModel(
            name='RackRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_roles', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='rack',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racks', to='api.rackrole'),
        ),
        migrations.AddConstraint(
            model_name='rackrole',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_rackrole_tenant_slug'),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='uniq_rack_site_name'),
        ),
    ]
