# Generated by Django 5.2.15 on 2026-06-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='front_image',
            field=models.ImageField(blank=True, help_text='Front rack-face image, rendered in rack elevations.', null=True, upload_to='device-type-images/'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='rear_image',
            field=models.ImageField(blank=True, help_text='Rear rack-face image, rendered in rack elevations.', null=True, upload_to='device-type-images/'),
        ),
    ]
