# Generated by Django 5.2.15 on 2026-06-24 18:31

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_devicetype_front_image_devicetype_rear_image'),
        ('core', '0005_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPRange',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_address', models.GenericIPAddressField()),
                ('end_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('reserved', 'Reserved'), ('deprecated', 'Deprecated')], default='active', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('role', models.ForeignKey(blank=True, help_text='Optional functional role (DHCP pool, NAT, …).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_ranges', to='api.iprole')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_ranges', to='core.tenant')),
                ('vrf', models.ForeignKey(blank=True, help_text='Routing context. NULL = Global VRF.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ip_ranges', to='api.vrf')),
            ],
            options={
                'ordering': ['start_address'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='api_iprange_tenant__8bc3ac_idx'), models.Index(fields=['tenant', 'vrf'], name='api_iprange_tenant__a85a6a_idx')],
            },
        ),
    ]
