# Generated by Django 5.2.15 on 2026-06-24 18:40

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_iprange'),
        ('core', '0005_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='RIR',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('is_private', models.BooleanField(default=False, help_text='Private / non-globally-routed space (RFC1918, ULA, …).')),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rirs', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Aggregate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefix', models.CharField(help_text='e.g. 10.0.0.0/8 or 2001:db8::/32', max_length=43)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='core.tenant')),
                ('rir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aggregates', to='api.rir')),
            ],
            options={
                'ordering': ['prefix'],
            },
        ),
        migrations.AddConstraint(
            model_name='rir',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_rir_tenant_slug'),
        ),
        migrations.AddIndex(
            model_name='aggregate',
            index=models.Index(fields=['tenant', 'rir'], name='api_aggrega_tenant__766d23_idx'),
        ),
        migrations.AddConstraint(
            model_name='aggregate',
            constraint=models.UniqueConstraint(fields=('tenant', 'prefix'), name='uniq_aggregate_tenant_prefix'),
        ),
    ]
