# Generated by Django 5.2.15 on 2026-06-24 18:47

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rir_aggregate_rir_uniq_rir_tenant_slug_and_more'),
        ('core', '0005_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASN',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asn', models.PositiveBigIntegerField(help_text='1…4294967295 (32-bit).')),
                ('description', models.TextField(blank=True)),
                ('rir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asns', to='api.rir')),
                ('sites', models.ManyToManyField(blank=True, related_name='asns', to='api.site')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asns', to='core.tenant')),
            ],
            options={
                'ordering': ['asn'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'asn'), name='uniq_asn_tenant_asn')],
            },
        ),
    ]
