# Generated by Django 5.2.15 on 2026-06-24 18:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_asn'),
        ('core', '0005_bookmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vlan',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='VLANGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('min_vid', models.PositiveSmallIntegerField(default=1, help_text='Lowest VID allowed in this group (1–4094).')),
                ('max_vid', models.PositiveSmallIntegerField(default=4094, help_text='Highest VID allowed in this group (1–4094).')),
                ('description', models.TextField(blank=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlan_groups', to='api.cluster')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlan_groups', to='api.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlan_groups', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vlan',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional VLAN group — scopes VID uniqueness.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlans', to='api.vlangroup'),
        ),
        migrations.AddConstraint(
            model_name='vlan',
            constraint=models.UniqueConstraint(fields=('tenant', 'group', 'vlan_id'), name='uniq_vlan_tenant_group_vid', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='vlangroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_vlangroup_tenant_slug'),
        ),
    ]
