# Generated by Django 5.2.15 on 2026-06-24 19:00

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_vlan_unique_together_vlangroup_vlan_group_and_more'),
        ('core', '0005_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='FHRPGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('protocol', models.CharField(choices=[('vrrp2', 'VRRPv2'), ('vrrp3', 'VRRPv3'), ('hsrp', 'HSRP'), ('glbp', 'GLBP'), ('carp', 'CARP')], max_length=8)),
                ('group_id', models.PositiveSmallIntegerField(help_text='Group / VRID number (0–255 for VRRP/HSRP).')),
                ('auth_type', models.CharField(blank=True, choices=[('', 'None'), ('plaintext', 'Plaintext'), ('md5', 'MD5')], default='', max_length=16)),
                ('auth_key', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fhrp_groups', to='core.tenant')),
                ('virtual_ip', models.ForeignKey(blank=True, help_text='The shared virtual IP this group answers on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fhrp_groups', to='api.ipaddress')),
            ],
            options={
                'ordering': ['protocol', 'group_id'],
            },
        ),
        migrations.CreateModel(
            name='FHRPGroupAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Election priority (higher wins).')),
                ('fhrp_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.fhrpgroup')),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fhrp_assignments', to='api.interface')),
                ('vm_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fhrp_assignments', to='api.vminterface')),
            ],
            options={
                'ordering': ['-priority'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('interface__isnull', False), ('vm_interface__isnull', True)), models.Q(('interface__isnull', True), ('vm_interface__isnull', False)), _connector='OR'), name='fhrp_assignment_exactly_one_target'), models.UniqueConstraint(fields=('fhrp_group', 'interface'), name='uniq_fhrp_group_interface'), models.UniqueConstraint(fields=('fhrp_group', 'vm_interface'), name='uniq_fhrp_group_vm_interface')],
            },
        ),
    ]
