# Generated by Django 5.2.15 on 2026-06-24 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_contactgroup_contact_contactrole_contactassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iprange',
            name='prefix',
            field=models.ForeignKey(blank=True, help_text='Optional parent prefix this range carves out of.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_ranges', to='api.prefix'),
        ),
    ]
