# Generated by Django 5.2.15 on 2026-06-25 06:20

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_iprange_prefix'),
        ('core', '0006_deploymentsettings_ldap_attr_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('description', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuit_types', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('account', models.CharField(blank=True, default='', help_text='Account number with this provider.', max_length=64)),
                ('portal_url', models.URLField(blank=True, default='')),
                ('noc_email', models.EmailField(blank=True, default='', max_length=254)),
                ('noc_phone', models.CharField(blank=True, default='', max_length=64)),
                ('comments', models.TextField(blank=True, default='')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cid', models.CharField(help_text='Circuit ID from the provider.', max_length=128)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('provisioning', 'Provisioning'), ('active', 'Active'), ('offline', 'Offline'), ('deprovisioning', 'Deprovisioning'), ('decommissioned', 'Decommissioned')], default='active', max_length=20)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('commit_rate_kbps', models.PositiveIntegerField(blank=True, help_text='Committed information rate, in kbps.', null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('comments', models.TextField(blank=True, default='')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuits', to='core.tenant')),
                ('termination_a_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circuits_a', to='api.site')),
                ('termination_z_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circuits_z', to='api.site')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='circuits', to='api.circuittype')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circuits', to='api.provider')),
            ],
            options={
                'ordering': ['cid'],
            },
        ),
        migrations.AddConstraint(
            model_name='circuittype',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_circuittype_tenant_slug'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_provider_tenant_slug'),
        ),
        migrations.AddConstraint(
            model_name='circuit',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider', 'cid'), name='uniq_circuit_tenant_provider_cid'),
        ),
    ]
