# Generated by Django 5.2.15 on 2026-06-25 15:19

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_circuittype_provider_circuit_and_more'),
        ('core', '0006_deploymentsettings_ldap_attr_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerPanel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('comments', models.TextField(blank=True, default='')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='power_panels', to='api.site')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_panels', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PowerFeed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('offline', 'Offline'), ('failed', 'Failed')], default='active', max_length=16)),
                ('type', models.CharField(choices=[('primary', 'Primary'), ('redundant', 'Redundant')], default='primary', max_length=16)),
                ('supply', models.CharField(choices=[('ac', 'AC'), ('dc', 'DC')], default='ac', max_length=4)),
                ('phase', models.CharField(choices=[('single', 'Single phase'), ('three', 'Three phase')], default='single', max_length=8)),
                ('voltage', models.IntegerField(blank=True, help_text='Volts.', null=True)),
                ('amperage', models.PositiveIntegerField(blank=True, help_text='Amps.', null=True)),
                ('max_utilization', models.PositiveSmallIntegerField(default=80, help_text='Maximum draw before over-utilised, as a percent.')),
                ('comments', models.TextField(blank=True, default='')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_feeds', to='api.rack')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_feeds', to='core.tenant')),
                ('power_panel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='power_feeds', to='api.powerpanel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='powerpanel',
            constraint=models.UniqueConstraint(fields=('tenant', 'site', 'name'), name='uniq_powerpanel_tenant_site_name'),
        ),
        migrations.AddConstraint(
            model_name='powerfeed',
            constraint=models.UniqueConstraint(fields=('tenant', 'power_panel', 'name'), name='uniq_powerfeed_tenant_panel_name'),
        ),
    ]
