# Generated by Django 5.2.15 on 2026-06-25 15:45

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_powerpanel_powerfeed_and_more'),
        ('core', '0006_deploymentsettings_ldap_attr_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WirelessLANGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wireless_lan_groups', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WirelessLAN',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ssid', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reserved', 'Reserved'), ('disabled', 'Disabled'), ('deprecated', 'Deprecated')], default='active', max_length=16)),
                ('auth_type', models.CharField(blank=True, choices=[('open', 'Open'), ('wep', 'WEP'), ('wpa-personal', 'WPA Personal (PSK)'), ('wpa-enterprise', 'WPA Enterprise')], default='', max_length=16)),
                ('auth_cipher', models.CharField(blank=True, choices=[('auto', 'Auto'), ('tkip', 'TKIP'), ('aes', 'AES')], default='', max_length=8)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('comments', models.TextField(blank=True, default='')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wireless_lans', to='core.tenant')),
                ('vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wireless_lans', to='api.vlan')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wireless_lans', to='api.wirelesslangroup')),
            ],
            options={
                'ordering': ['ssid'],
            },
        ),
        migrations.AddConstraint(
            model_name='wirelesslangroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_wlangroup_tenant_slug'),
        ),
    ]
