# Generated by Django 5.2.15 on 2026-06-25 15:54

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_wirelesslangroup_wirelesslan_and_more'),
        ('core', '0006_deploymentsettings_ldap_attr_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPSecProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('ike_version', models.PositiveSmallIntegerField(choices=[(1, 'IKEv1'), (2, 'IKEv2')], default=2)),
                ('encryption', models.CharField(choices=[('aes-128-cbc', 'AES-128-CBC'), ('aes-192-cbc', 'AES-192-CBC'), ('aes-256-cbc', 'AES-256-CBC'), ('aes-128-gcm', 'AES-128-GCM'), ('aes-256-gcm', 'AES-256-GCM'), ('3des-cbc', '3DES-CBC')], default='aes-256-cbc', max_length=16)),
                ('authentication', models.CharField(choices=[('hmac-sha1', 'HMAC-SHA1'), ('hmac-sha256', 'HMAC-SHA256'), ('hmac-sha384', 'HMAC-SHA384'), ('hmac-sha512', 'HMAC-SHA512'), ('hmac-md5', 'HMAC-MD5')], default='hmac-sha256', max_length=16)),
                ('dh_group', models.PositiveSmallIntegerField(default=14, help_text='Diffie-Hellman group number (e.g. 14, 19, 20).')),
                ('pfs_group', models.PositiveSmallIntegerField(blank=True, help_text='Perfect-forward-secrecy DH group; blank to disable.', null=True)),
                ('sa_lifetime', models.PositiveIntegerField(blank=True, help_text='Security-association lifetime, seconds.', null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipsec_profiles', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TunnelGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tunnel_groups', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tunnel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('encapsulation', models.CharField(choices=[('ipsec-tunnel', 'IPSec — Tunnel'), ('ipsec-transport', 'IPSec — Transport'), ('gre', 'GRE'), ('ip-ip', 'IP-in-IP'), ('wireguard', 'WireGuard')], default='ipsec-tunnel', max_length=20)),
                ('tunnel_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('comments', models.TextField(blank=True, default='')),
                ('ipsec_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tunnels', to='api.ipsecprofile')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tunnels', to='core.tenant')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tunnels', to='api.tunnelgroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='ipsecprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_ipsecprofile_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='tunnelgroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_tunnelgroup_tenant_slug'),
        ),
        migrations.AddConstraint(
            model_name='tunnel',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_tunnel_tenant_name'),
        ),
    ]
