# Generated by Django 5.2.15 on 2026-06-25 19:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_region_site_region_location_and_more'),
        ('core', '0006_deploymentsettings_ldap_attr_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigContext',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('weight', models.PositiveIntegerField(default=1000, help_text='Merge order — higher weight wins on conflicts.')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('device_roles', models.ManyToManyField(blank=True, related_name='config_contexts', to='api.devicerole')),
                ('platforms', models.ManyToManyField(blank=True, related_name='config_contexts', to='api.platform')),
                ('regions', models.ManyToManyField(blank=True, related_name='config_contexts', to='api.region')),
                ('sites', models.ManyToManyField(blank=True, related_name='config_contexts', to='api.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_contexts', to='core.tenant')),
            ],
            options={
                'ordering': ['weight', 'name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_configcontext_tenant_name')],
            },
        ),
    ]
