# Generated by Django 5.2.15 on 2026-06-25 22:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_configcontext'),
        ('core', '0006_deploymentsettings_ldap_attr_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('object_type', models.CharField(help_text='Object-type slug this renders (see the RBAC registry).', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('template_code', models.TextField(help_text='Jinja2 source. Context: `objects` (and `queryset`) — the objects of this type in the active tenant.')),
                ('mime_type', models.CharField(blank=True, default='text/plain', max_length=64)),
                ('file_extension', models.CharField(blank=True, default='txt', max_length=16)),
                ('as_attachment', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_templates', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_exporttemplate_tenant_name')],
            },
        ),
    ]
