# Generated by Django 5.2.15 on 2026-06-26 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_exporttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The interface this one nests under (e.g. ae1.100 → ae1, or a LAG member → its aggregate). Must be on the same device.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.interface'),
        ),
        migrations.AddField(
            model_name='interface',
            name='virtual',
            field=models.BooleanField(default=False, help_text='A logical interface with no physical port — sub-interface, LAG/aggregate, loopback, tunnel, VLAN interface.'),
        ),
    ]
