# Generated by Django 5.2.15 on 2026-06-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_interface_parent_interface_virtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='bridge',
            field=models.ForeignKey(blank=True, help_text='The bridge interface this one belongs to. Same device.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bridge_members', to='api.interface'),
        ),
        migrations.AddField(
            model_name='interface',
            name='lag',
            field=models.ForeignKey(blank=True, help_text='The link-aggregation (LAG/aggregate) interface this one is a member of, e.g. a physical port → ae1. Same device.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lag_members', to='api.interface'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The interface this one nests under (e.g. a sub-interface ae1.100 → ae1). Must be on the same device.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.interface'),
        ),
    ]
