# Generated by Django 5.2.15 on 2026-06-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_interface_bridge_interface_lag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='type',
            field=models.CharField(blank=True, choices=[('virtual', 'Virtual'), ('bridge', 'Bridge'), ('lag', 'Link Aggregation Group (LAG)'), ('100base-tx', '100BASE-TX (10/100ME)'), ('100base-t1', '100BASE-T1 (10/100ME single-pair)'), ('100base-fx', '100BASE-FX (10/100ME fiber)'), ('1000base-t', '1000BASE-T (1GE)'), ('2.5gbase-t', '2.5GBASE-T (2.5GE)'), ('5gbase-t', '5GBASE-T (5GE)'), ('10gbase-t', '10GBASE-T (10GE)'), ('10gbase-cx4', '10GBASE-CX4 (10GE)'), ('1000base-x-gbic', 'GBIC (1GE)'), ('1000base-x-sfp', 'SFP (1GE)'), ('10gbase-x-sfpp', 'SFP+ (10GE)'), ('10gbase-x-xfp', 'XFP (10GE)'), ('10gbase-x-x2', 'X2 (10GE)'), ('10gbase-x-xenpak', 'XENPAK (10GE)'), ('25gbase-x-sfp28', 'SFP28 (25GE)'), ('50gbase-x-sfp56', 'SFP56 (50GE)'), ('40gbase-x-qsfpp', 'QSFP+ (40GE)'), ('100gbase-x-qsfp28', 'QSFP28 (100GE)'), ('100gbase-x-qsfpdd', 'QSFP-DD (100GE)'), ('100gbase-x-cfp', 'CFP (100GE)'), ('100gbase-x-cfp2', 'CFP2 (100GE)'), ('100gbase-x-cfp4', 'CFP4 (100GE)'), ('100gbase-x-cpak', 'Cisco CPAK (100GE)'), ('100gbase-x-dsfp', 'DSFP (100GE)'), ('100gbase-x-sfpdd', 'SFP-DD (100GE)'), ('200gbase-x-cfp2', 'CFP2 (200GE)'), ('200gbase-x-qsfp56', 'QSFP56 (200GE)'), ('200gbase-x-qsfpdd', 'QSFP-DD (200GE)'), ('400gbase-x-qsfp112', 'QSFP112 (400GE)'), ('400gbase-x-qsfpdd', 'QSFP-DD (400GE)'), ('400gbase-x-osfp', 'OSFP (400GE)'), ('800gbase-x-qsfpdd', 'QSFP-DD (800GE)'), ('800gbase-x-osfp', 'OSFP (800GE)'), ('ieee802.11a', 'IEEE 802.11a'), ('ieee802.11g', 'IEEE 802.11b/g'), ('ieee802.11n', 'IEEE 802.11n'), ('ieee802.11ac', 'IEEE 802.11ac'), ('ieee802.11ad', 'IEEE 802.11ad'), ('ieee802.11ax', 'IEEE 802.11ax (Wi-Fi 6)'), ('ieee802.11ay', 'IEEE 802.11ay'), ('ieee802.15.1', 'IEEE 802.15.1 (Bluetooth)'), ('gsm', 'GSM'), ('cdma', 'CDMA'), ('lte', 'LTE'), ('1gfc-sfp', 'SFP (1GFC)'), ('2gfc-sfp', 'SFP (2GFC)'), ('4gfc-sfp', 'SFP (4GFC)'), ('8gfc-sfpp', 'SFP+ (8GFC)'), ('16gfc-sfpp', 'SFP+ (16GFC)'), ('32gfc-sfp28', 'SFP28 (32GFC)'), ('64gfc-qsfpp', 'QSFP+ (64GFC)'), ('128gfc-qsfp28', 'QSFP28 (128GFC)'), ('infiniband-sdr', 'InfiniBand SDR'), ('infiniband-ddr', 'InfiniBand DDR'), ('infiniband-qdr', 'InfiniBand QDR'), ('infiniband-fdr', 'InfiniBand FDR'), ('infiniband-edr', 'InfiniBand EDR'), ('infiniband-hdr', 'InfiniBand HDR'), ('infiniband-ndr', 'InfiniBand NDR'), ('t1', 'T1 (1.544 Mbps)'), ('e1', 'E1 (2.048 Mbps)'), ('t3', 'T3 (45 Mbps)'), ('e3', 'E3 (34 Mbps)'), ('xdsl', 'xDSL'), ('gpon', 'GPON (2.5 Gbps / 1.25 Gbps)'), ('xg-pon', 'XG-PON (10 Gbps / 2.5 Gbps)'), ('xgs-pon', 'XGS-PON (10 Gbps)'), ('ng-pon2', 'NG-PON2 (TWDM-PON)'), ('epon', 'EPON (1 Gbps)'), ('10g-epon', '10G-EPON (10 Gbps)'), ('other', 'Other')], default='', help_text='Physical/logical media type, e.g. 10gbase-x-sfpp.', max_length=64),
        ),
        migrations.AlterField(
            model_name='cable',
            name='type',
            field=models.CharField(blank=True, choices=[('cat3', 'CAT3'), ('cat5', 'CAT5'), ('cat5e', 'CAT5e'), ('cat6', 'CAT6'), ('cat6a', 'CAT6a'), ('cat7', 'CAT7'), ('cat7a', 'CAT7a'), ('cat8', 'CAT8'), ('dac-active', 'Direct Attach Copper (Active)'), ('dac-passive', 'Direct Attach Copper (Passive)'), ('mrj21-trunk', 'MRJ21 Trunk'), ('coaxial', 'Coaxial'), ('mmf', 'Multimode Fiber'), ('mmf-om1', 'Multimode Fiber (OM1)'), ('mmf-om2', 'Multimode Fiber (OM2)'), ('mmf-om3', 'Multimode Fiber (OM3)'), ('mmf-om4', 'Multimode Fiber (OM4)'), ('mmf-om5', 'Multimode Fiber (OM5)'), ('smf', 'Singlemode Fiber'), ('smf-os1', 'Singlemode Fiber (OS1)'), ('smf-os2', 'Singlemode Fiber (OS2)'), ('aoc', 'Active Optical Cabling (AOC)'), ('power', 'Power')], help_text='Cable medium, e.g. cat6 / dac-passive / smf-os2 / mmf-om4.', max_length=64),
        ),
    ]
