# Generated by Django 5.2.15 on 2026-06-27 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_interface_type_alter_cable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='site',
            field=models.ForeignKey(blank=True, help_text="Site this IP belongs to. Auto-filled from the prefix when the prefix has 'assign IPs to site' on; otherwise set/cleared by hand.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_addresses', to='api.site'),
        ),
        migrations.AddField(
            model_name='prefix',
            name='auto_assign_site',
            field=models.BooleanField(default=False, help_text="When on, IPs created in this prefix inherit the prefix's site (so site-scoped users/filters pick them up)."),
        ),
        migrations.AddField(
            model_name='prefix',
            name='location',
            field=models.ForeignKey(blank=True, help_text="Location this range belongs to. Sets the prefix's site to the location's site automatically.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefixes', to='api.location'),
        ),
    ]
