# Generated by Django 5.2.15 on 2026-06-28 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_servicetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='oob_ip',
            field=models.ForeignKey(blank=True, help_text='Out-of-band / management IP for this device. Pick from IPs already assigned to this device.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oob_for', to='api.ipaddress'),
        ),
        migrations.AddField(
            model_name='device',
            name='secondary_ip',
            field=models.ForeignKey(blank=True, help_text='Secondary IP for this device. Pick from IPs already assigned to this device.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_for', to='api.ipaddress'),
        ),
    ]
