# Generated by Django 5.2.15 on 2026-06-28 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_device_oob_ip_device_secondary_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='airflow',
            field=models.CharField(blank=True, choices=[('front-to-rear', 'Front to rear'), ('rear-to-front', 'Rear to front'), ('left-to-right', 'Left to right'), ('right-to-left', 'Right to left'), ('passive', 'Passive'), ('mixed', 'Mixed')], default='', help_text='Direction of cooling airflow through the chassis.', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='cluster',
            field=models.ForeignKey(blank=True, help_text='Compute / virtualisation cluster this device belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='api.cluster'),
        ),
        migrations.AddField(
            model_name='device',
            name='comments',
            field=models.TextField(blank=True, default='', help_text='Long-form notes (separate from the short description).'),
        ),
        migrations.AddField(
            model_name='device',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude (decimal degrees).', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Physical location within the site (building / floor / room).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='api.location'),
        ),
        migrations.AddField(
            model_name='device',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude (decimal degrees).', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='devicerole',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='User-defined custom fields'),
        ),
    ]
