# Generated by Django 5.2.15 on 2026-06-30 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_numid'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='mode',
            field=models.CharField(blank=True, choices=[('access', 'Access'), ('tagged', 'Tagged (trunk)'), ('tagged-all', 'Tagged (all VLANs)')], default='', help_text='802.1Q mode. Access = untagged only; Tagged = a trunk carrying tagged_vlans (+ the untagged native VLAN).', max_length=16),
        ),
        migrations.AddField(
            model_name='interface',
            name='tagged_vlans',
            field=models.ManyToManyField(blank=True, help_text='Tagged VLANs carried on a trunk (mode = tagged).', related_name='tagged_interfaces', to='api.vlan'),
        ),
        migrations.AddField(
            model_name='interface',
            name='vrf',
            field=models.ForeignKey(blank=True, help_text='The VRF this interface routes in. Lets the same IP exist on interfaces in different VRFs without colliding.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interfaces', to='api.vrf'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='vlan',
            field=models.ForeignKey(blank=True, help_text='Untagged / access (native) VLAN.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vlan'),
        ),
    ]
