# Generated by Django 5.2.15 on 2026-06-30 21:41

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_interface_mode_interface_tagged_vlans_interface_vrf_and_more'),
        ('core', '0010_deploymentsettings_human_ids_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='MACAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mac_address', models.CharField(help_text='48-bit MAC, colon-separated lowercase.', max_length=17)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('assigned_interface', models.ForeignKey(blank=True, help_text='The interface that bears this MAC, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mac_addresses', to='api.interface')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mac_addresses', to='core.tenant')),
            ],
            options={
                'ordering': ['mac_address'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'mac_address', 'assigned_interface'), name='uniq_macaddress_tenant_addr_iface', nulls_distinct=False)],
            },
        ),
    ]
