# Generated by Django 5.2.15 on 2026-07-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_alter_cable_type_alter_interface_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="rack_side",
            field=models.CharField(
                blank=True,
                choices=[("left", "Left"), ("right", "Right")],
                default="",
                help_text="Which half of the U a half-width device occupies (the device type's rack_width must be 'half'). Blank for full-width devices.",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="devicetype",
            name="rack_width",
            field=models.CharField(
                choices=[("full", "Full width"), ("half", "Half width")],
                default="full",
                help_text="Horizontal footprint in the rack. Half-width gear (e.g. a half-U ToR switch like the Mellanox SN2010) mounts two side-by-side in the same U.",
                max_length=4,
            ),
        ),
    ]
