# Generated by Django 5.2.15 on 2026-07-02 20:43

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_circuit_terminations_data'),
        ('core', '0011_tenantgroup_tenant_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.contactgroup'),
        ),
        migrations.AddField(
            model_name='device',
            name='config_template',
            field=models.ForeignKey(blank=True, help_text="Config template for this device. Falls back to the role's, then the platform's, when unset.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.exporttemplate'),
        ),
        migrations.AddField(
            model_name='device',
            name='vc_position',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Member id within the stack (0–255, unique per chassis).', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='vc_priority',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Master-election priority within the stack.', null=True),
        ),
        migrations.AddField(
            model_name='devicerole',
            name='config_template',
            field=models.ForeignKey(blank=True, help_text='Default config template for devices with this role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.exporttemplate'),
        ),
        migrations.AddField(
            model_name='platform',
            name='config_template',
            field=models.ForeignKey(blank=True, help_text='Default config template for devices on this platform.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.exporttemplate'),
        ),
        migrations.AddField(
            model_name='vminterface',
            name='mode',
            field=models.CharField(blank=True, choices=[('access', 'Access'), ('tagged', 'Tagged (trunk)'), ('tagged-all', 'Tagged (all VLANs)')], default='', help_text='802.1Q mode. Access = untagged only; Tagged = a trunk carrying tagged_vlans (+ the untagged native VLAN).', max_length=16),
        ),
        migrations.AddField(
            model_name='vminterface',
            name='tagged_vlans',
            field=models.ManyToManyField(blank=True, help_text='Tagged VLANs carried on a trunk (mode = tagged).', related_name='tagged_vm_interfaces', to='api.vlan'),
        ),
        migrations.AddField(
            model_name='vminterface',
            name='vlan',
            field=models.ForeignKey(blank=True, help_text='Untagged / access (native) VLAN.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vm_interfaces', to='api.vlan'),
        ),
        migrations.AddField(
            model_name='vminterface',
            name='vrf',
            field=models.ForeignKey(blank=True, help_text='The VRF this interface routes in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vm_interfaces', to='api.vrf'),
        ),
        migrations.CreateModel(
            name='L2VPN',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('type', models.CharField(choices=[('vxlan', 'VXLAN'), ('vxlan-evpn', 'VXLAN-EVPN'), ('mpls-evpn', 'MPLS-EVPN'), ('pbb-evpn', 'PBB-EVPN'), ('vpws', 'VPWS'), ('vpls', 'VPLS'), ('epl', 'EPL'), ('evpl', 'EVPL'), ('spb', 'SPB'), ('trill', 'TRILL')], max_length=16)),
                ('identifier', models.BigIntegerField(blank=True, help_text='Overlay identifier — VNI / VC-ID.', null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('comments', models.TextField(blank=True, default='')),
                ('export_targets', models.ManyToManyField(blank=True, related_name='exporting_l2vpns', to='api.routetarget')),
                ('import_targets', models.ManyToManyField(blank=True, related_name='importing_l2vpns', to='api.routetarget')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='l2vpns', to='api.status')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l2vpns', to='core.tenant')),
            ],
            options={
                'verbose_name': 'L2VPN',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='L2VPNTermination',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='l2vpn_terminations', to='api.interface')),
                ('l2vpn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminations', to='api.l2vpn')),
                ('vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='l2vpn_terminations', to='api.vlan')),
                ('vm_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='l2vpn_terminations', to='api.vminterface')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualChassis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('domain', models.CharField(blank=True, default='', help_text='Stack/VC domain identifier, where the platform has one.', max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('comments', models.TextField(blank=True, default='')),
                ('master', models.ForeignKey(blank=True, help_text='The member acting as stack master, if designated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.device')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_chassis', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'virtual chassis',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='virtual_chassis',
            field=models.ForeignKey(blank=True, help_text='The switch stack this device is a member of.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='api.virtualchassis'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('vc_position__isnull', False), ('virtual_chassis__isnull', False)), fields=('virtual_chassis', 'vc_position'), name='uniq_device_vc_position'),
        ),
        migrations.AddConstraint(
            model_name='l2vpn',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_l2vpn_tenant_slug'),
        ),
        migrations.AddConstraint(
            model_name='l2vpntermination',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('interface__isnull', True), ('vlan__isnull', False), ('vm_interface__isnull', True)), models.Q(('interface__isnull', False), ('vlan__isnull', True), ('vm_interface__isnull', True)), models.Q(('interface__isnull', True), ('vlan__isnull', True), ('vm_interface__isnull', False)), _connector='OR'), name='l2vpntermination_exactly_one_endpoint'),
        ),
        migrations.AddConstraint(
            model_name='l2vpntermination',
            constraint=models.UniqueConstraint(condition=models.Q(('vlan__isnull', False)), fields=('vlan',), name='uniq_l2vpntermination_vlan'),
        ),
        migrations.AddConstraint(
            model_name='l2vpntermination',
            constraint=models.UniqueConstraint(condition=models.Q(('interface__isnull', False)), fields=('interface',), name='uniq_l2vpntermination_interface'),
        ),
        migrations.AddConstraint(
            model_name='l2vpntermination',
            constraint=models.UniqueConstraint(condition=models.Q(('vm_interface__isnull', False)), fields=('vm_interface',), name='uniq_l2vpntermination_vm_interface'),
        ),
        migrations.AddConstraint(
            model_name='virtualchassis',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_virtualchassis_tenant_name'),
        ),
    ]
