# Generated by Django 5.2.15 on 2026-07-03 14:42

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_contactgroup_parent_device_config_template_and_more'),
        ('core', '0011_tenantgroup_tenant_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='faceplate',
            field=models.JSONField(blank=True, default=None, help_text="Saved front-panel layout (v1 doc: groups of port slots referencing component-template names). Null = automatic layout computed from the device's interfaces.", null=True),
        ),
        migrations.CreateModel(
            name='AuxPort',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(blank=True, choices=[('USB', [('usb-a', 'USB Type A'), ('usb-b', 'USB Type B'), ('usb-c', 'USB Type C'), ('usb-mini-b', 'USB Mini B'), ('usb-micro-b', 'USB Micro B')]), ('Video', [('hdmi', 'HDMI'), ('mini-hdmi', 'Mini HDMI'), ('vga', 'VGA (DE-15)'), ('dvi', 'DVI'), ('displayport', 'DisplayPort'), ('mini-displayport', 'Mini DisplayPort')]), ('Storage', [('sd', 'SD card'), ('microsd', 'microSD card')]), ('Other', [('rj11', 'RJ11'), ('audio-3.5mm', 'Audio 3.5 mm'), ('grounding', 'Grounding lug'), ('other', 'Other')])], default='', max_length=32)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aux_ports', to='api.device')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('device', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AuxPortTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(blank=True, choices=[('USB', [('usb-a', 'USB Type A'), ('usb-b', 'USB Type B'), ('usb-c', 'USB Type C'), ('usb-mini-b', 'USB Mini B'), ('usb-micro-b', 'USB Micro B')]), ('Video', [('hdmi', 'HDMI'), ('mini-hdmi', 'Mini HDMI'), ('vga', 'VGA (DE-15)'), ('dvi', 'DVI'), ('displayport', 'DisplayPort'), ('mini-displayport', 'Mini DisplayPort')]), ('Storage', [('sd', 'SD card'), ('microsd', 'microSD card')]), ('Other', [('rj11', 'RJ11'), ('audio-3.5mm', 'Audio 3.5 mm'), ('grounding', 'Grounding lug'), ('other', 'Other')])], default='', max_length=32)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aux_port_templates', to='api.devicetype')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('device_type', 'name')},
            },
        ),
    ]
