# Generated by Django 5.2.15 on 2026-07-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_devicetype_faceplate_auxport_auxporttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='airflow',
            field=models.CharField(blank=True, choices=[('front-to-rear', 'Front to rear'), ('rear-to-front', 'Rear to front'), ('left-to-right', 'Left to right'), ('right-to-left', 'Right to left'), ('passive', 'Passive'), ('mixed', 'Mixed')], default='', help_text='Default cooling airflow direction for this hardware.', max_length=50),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='is_full_depth',
            field=models.BooleanField(default=True, help_text='Occupies both the front and rear rack faces. Full-depth devices show hatched on the opposite face in elevations.'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Chassis weight (see weight_unit).', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('g', 'g'), ('lb', 'lb'), ('oz', 'oz')], default='', max_length=8),
        ),
    ]
