# Generated by Django 5.2.15 on 2026-07-03 20:46

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_devicetype_airflow_devicetype_is_full_depth_and_more'),
        ('core', '0011_tenantgroup_tenant_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleBay',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('position', models.CharField(blank=True, default='', help_text='Value {module} resolves to in installed port names.', max_length=32)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_bays', to='api.device')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('device', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ModuleType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('part_number', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_types', to='api.manufacturer')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_types', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, default='', max_length=255)),
                ('asset_tag', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.device')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('module_bay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module', to='api.modulebay')),
                ('module_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='api.moduletype')),
            ],
            options={
                'ordering': ['module_bay__name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleBayTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.CharField(blank=True, default='', help_text='Value {module} resolves to in installed port names (e.g. 1).', max_length=32)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_bay_templates', to='api.devicetype')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('device_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ModuleInterfaceTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(blank=True, choices=[('Virtual', [('virtual', 'Virtual'), ('bridge', 'Bridge'), ('lag', 'Link Aggregation Group (LAG)')]), ('Fast Ethernet (100M)', [('100base-tx', '100BASE-TX (10/100ME)'), ('100base-t1', '100BASE-T1 (10/100ME single-pair)'), ('100base-fx', '100BASE-FX (10/100ME fiber)'), ('100base-lfx', '100BASE-LFX (10/100ME fiber)')]), ('Gigabit Ethernet (1G)', [('1000base-t', '1000BASE-T (1GE)'), ('1000base-tx', '1000BASE-TX (1GE)'), ('1000base-sx', '1000BASE-SX (1GE)'), ('1000base-lx', '1000BASE-LX (1GE)'), ('1000base-lx10', '1000BASE-LX10/LH (1GE)'), ('1000base-lsx', '1000BASE-LSX (1GE)'), ('1000base-ex', '1000BASE-EX (1GE)'), ('1000base-zx', '1000BASE-ZX (1GE)'), ('1000base-bx10-d', '1000BASE-BX10-D (1GE BiDi Down)'), ('1000base-bx10-u', '1000BASE-BX10-U (1GE BiDi Up)'), ('1000base-cx', '1000BASE-CX (1GE DAC)'), ('1000base-cwdm', '1000BASE-CWDM (1GE)'), ('1000base-dwdm', '1000BASE-DWDM (1GE)')]), ('2.5 / 5 Gigabit Ethernet', [('2.5gbase-t', '2.5GBASE-T (2.5GE)'), ('5gbase-t', '5GBASE-T (5GE)')]), ('10 Gigabit Ethernet', [('10gbase-t', '10GBASE-T (10GE)'), ('10gbase-cx4', '10GBASE-CX4 (10GE DAC)'), ('10gbase-cu', '10GBASE-CU (10GE DAC passive twinax)'), ('10gbase-sr', '10GBASE-SR (10GE)'), ('10gbase-lr', '10GBASE-LR (10GE)'), ('10gbase-lrm', '10GBASE-LRM (10GE)'), ('10gbase-lx4', '10GBASE-LX4 (10GE)'), ('10gbase-er', '10GBASE-ER (10GE)'), ('10gbase-zr', '10GBASE-ZR (10GE)'), ('10gbase-br-d', '10GBASE-BR-D (10GE BiDi Down)'), ('10gbase-br-u', '10GBASE-BR-U (10GE BiDi Up)')]), ('25 Gigabit Ethernet', [('25gbase-t', '25GBASE-T (25GE)'), ('25gbase-cr', '25GBASE-CR (25GE DAC)'), ('25gbase-sr', '25GBASE-SR (25GE)'), ('25gbase-lr', '25GBASE-LR (25GE)'), ('25gbase-er', '25GBASE-ER (25GE)')]), ('40 Gigabit Ethernet', [('40gbase-cr4', '40GBASE-CR4 (40GE DAC)'), ('40gbase-sr4', '40GBASE-SR4 (40GE)'), ('40gbase-sr4-bd', '40GBASE-SR4 (40GE BiDi)'), ('40gbase-lr4', '40GBASE-LR4 (40GE)'), ('40gbase-fr4', '40GBASE-FR4 (40GE)'), ('40gbase-er4', '40GBASE-ER4 (40GE)')]), ('50 Gigabit Ethernet', [('50gbase-cr', '50GBASE-CR (50GE DAC)'), ('50gbase-sr', '50GBASE-SR (50GE)'), ('50gbase-fr', '50GBASE-FR (50GE)'), ('50gbase-lr', '50GBASE-LR (50GE)'), ('50gbase-er', '50GBASE-ER (50GE)')]), ('100 Gigabit Ethernet', [('100gbase-cr1', '100GBASE-CR1 (100GE DAC)'), ('100gbase-cr2', '100GBASE-CR2 (100GE DAC)'), ('100gbase-cr4', '100GBASE-CR4 (100GE DAC)'), ('100gbase-cr10', '100GBASE-CR10 (100GE DAC)'), ('100gbase-sr1', '100GBASE-SR1 (100GE)'), ('100gbase-sr1.2', '100GBASE-SR1.2 (100GE BiDi)'), ('100gbase-sr2', '100GBASE-SR2 (100GE)'), ('100gbase-sr4', '100GBASE-SR4 (100GE)'), ('100gbase-sr10', '100GBASE-SR10 (100GE)'), ('100gbase-dr', '100GBASE-DR (100GE)'), ('100gbase-fr1', '100GBASE-FR1 (100GE)'), ('100gbase-lr1', '100GBASE-LR1 (100GE)'), ('100gbase-lr4', '100GBASE-LR4 (100GE)'), ('100gbase-er4', '100GBASE-ER4 (100GE)'), ('100gbase-cwdm4', '100GBASE-CWDM4 (100GE)'), ('100gbase-zr', '100GBASE-ZR (100GE)')]), ('200 Gigabit Ethernet', [('200gbase-cr2', '200GBASE-CR2 (200GE DAC)'), ('200gbase-cr4', '200GBASE-CR4 (200GE DAC)'), ('200gbase-sr2', '200GBASE-SR2 (200GE)'), ('200gbase-sr4', '200GBASE-SR4 (200GE)'), ('200gbase-vr2', '200GBASE-VR2 (200GE)'), ('200gbase-dr4', '200GBASE-DR4 (200GE)'), ('200gbase-fr4', '200GBASE-FR4 (200GE)'), ('200gbase-lr4', '200GBASE-LR4 (200GE)'), ('200gbase-er4', '200GBASE-ER4 (200GE)')]), ('400 Gigabit Ethernet', [('400gbase-cr4', '400GBASE-CR4 (400GE DAC)'), ('400gbase-sr4', '400GBASE-SR4 (400GE)'), ('400gbase-sr4_2', '400GBASE-SR4.2 (400GE BiDi)'), ('400gbase-sr8', '400GBASE-SR8 (400GE)'), ('400gbase-sr16', '400GBASE-SR16 (400GE)'), ('400gbase-vr4', '400GBASE-VR4 (400GE)'), ('400gbase-dr4', '400GBASE-DR4 (400GE)'), ('400gbase-fr4', '400GBASE-FR4 (400GE)'), ('400gbase-fr8', '400GBASE-FR8 (400GE)'), ('400gbase-lr4', '400GBASE-LR4 (400GE)'), ('400gbase-lr8', '400GBASE-LR8 (400GE)'), ('400gbase-er8', '400GBASE-ER8 (400GE)'), ('400gbase-zr', '400GBASE-ZR (400GE)')]), ('800 Gigabit Ethernet', [('800gbase-cr8', '800GBASE-CR8 (800GE DAC)'), ('800gbase-sr8', '800GBASE-SR8 (800GE)'), ('800gbase-vr8', '800GBASE-VR8 (800GE)'), ('800gbase-dr8', '800GBASE-DR8 (800GE)')]), ('1.6 Terabit Ethernet', [('1.6tbase-cr8', '1.6TBASE-CR8 (1.6TE DAC)'), ('1.6tbase-dr8', '1.6TBASE-DR8 (1.6TE)'), ('1.6tbase-dr8-2', '1.6TBASE-DR8-2 (1.6TE)')]), ('Ethernet (pluggable transceivers)', [('100base-x-sfp', 'SFP (100ME)'), ('1000base-x-gbic', 'GBIC (1GE)'), ('1000base-x-sfp', 'SFP (1GE)'), ('2.5gbase-x-sfp', 'SFP (2.5GE)'), ('10gbase-x-sfpp', 'SFP+ (10GE)'), ('10gbase-x-xfp', 'XFP (10GE)'), ('10gbase-x-x2', 'X2 (10GE)'), ('10gbase-x-xenpak', 'XENPAK (10GE)'), ('25gbase-x-sfp28', 'SFP28 (25GE)'), ('40gbase-x-qsfpp', 'QSFP+ (40GE)'), ('50gbase-x-qsfp28', 'QSFP28 (50GE)'), ('50gbase-x-sfp56', 'SFP56 (50GE)'), ('100gbase-x-cfp', 'CFP (100GE)'), ('100gbase-x-cfp2', 'CFP2 (100GE)'), ('100gbase-x-cfp4', 'CFP4 (100GE)'), ('100gbase-x-cxp', 'CXP (100GE)'), ('100gbase-x-cpak', 'Cisco CPAK (100GE)'), ('100gbase-x-dsfp', 'DSFP (100GE)'), ('100gbase-x-sfpdd', 'SFP-DD (100GE)'), ('100gbase-x-qsfp28', 'QSFP28 (100GE)'), ('100gbase-x-qsfpdd', 'QSFP-DD (100GE)'), ('200gbase-x-cfp2', 'CFP2 (200GE)'), ('200gbase-x-qsfp56', 'QSFP56 (200GE)'), ('200gbase-x-qsfpdd', 'QSFP-DD (200GE)'), ('400gbase-x-cfp2', 'CFP2 (400GE)'), ('400gbase-x-cfp8', 'CFP8 (400GE)'), ('400gbase-x-cdfp', 'CDFP (400GE)'), ('400gbase-x-qsfp112', 'QSFP112 (400GE)'), ('400gbase-x-qsfpdd', 'QSFP-DD (400GE)'), ('400gbase-x-osfp', 'OSFP (400GE)'), ('400gbase-x-osfp-rhs', 'OSFP-RHS (400GE)'), ('800gbase-x-qsfpdd', 'QSFP-DD (800GE)'), ('800gbase-x-osfp', 'OSFP (800GE)'), ('1.6tbase-x-osfp1600', 'OSFP1600 (1.6TE)'), ('1.6tbase-x-osfp1600-rhs', 'OSFP1600-RHS (1.6TE)'), ('1.6tbase-x-qsfpdd1600', 'QSFP-DD1600 (1.6TE)')]), ('Ethernet (backplane)', [('1000base-kx', '1000BASE-KX (1GE)'), ('2.5gbase-kx', '2.5GBASE-KX (2.5GE)'), ('5gbase-kr', '5GBASE-KR (5GE)'), ('10gbase-kr', '10GBASE-KR (10GE)'), ('10gbase-kx4', '10GBASE-KX4 (10GE)'), ('25gbase-kr', '25GBASE-KR (25GE)'), ('40gbase-kr4', '40GBASE-KR4 (40GE)'), ('50gbase-kr', '50GBASE-KR (50GE)'), ('100gbase-kp4', '100GBASE-KP4 (100GE)'), ('100gbase-kr2', '100GBASE-KR2 (100GE)'), ('100gbase-kr4', '100GBASE-KR4 (100GE)'), ('1.6tbase-kr8', '1.6TBASE-KR8 (1.6TE)')]), ('Wireless', [('ieee802.11a', 'IEEE 802.11a'), ('ieee802.11g', 'IEEE 802.11b/g'), ('ieee802.11n', 'IEEE 802.11n (Wi-Fi 4)'), ('ieee802.11ac', 'IEEE 802.11ac (Wi-Fi 5)'), ('ieee802.11ad', 'IEEE 802.11ad (WiGig)'), ('ieee802.11ax', 'IEEE 802.11ax (Wi-Fi 6)'), ('ieee802.11ay', 'IEEE 802.11ay (WiGig)'), ('ieee802.11be', 'IEEE 802.11be (Wi-Fi 7)'), ('ieee802.15.1', 'IEEE 802.15.1 (Bluetooth)'), ('ieee802.15.4', 'IEEE 802.15.4 (LR-WPAN)'), ('other-wireless', 'Other (wireless)')]), ('Cellular', [('gsm', 'GSM'), ('cdma', 'CDMA'), ('lte', 'LTE'), ('4g', '4G'), ('5g', '5G')]), ('SONET / SDH', [('sonet-oc3', 'OC-3 / STM-1'), ('sonet-oc12', 'OC-12 / STM-4'), ('sonet-oc48', 'OC-48 / STM-16'), ('sonet-oc192', 'OC-192 / STM-64'), ('sonet-oc768', 'OC-768 / STM-256'), ('sonet-oc1920', 'OC-1920 / STM-640'), ('sonet-oc3840', 'OC-3840 / STM-1280')]), ('Fibre Channel', [('1gfc-sfp', 'SFP (1GFC)'), ('2gfc-sfp', 'SFP (2GFC)'), ('4gfc-sfp', 'SFP (4GFC)'), ('8gfc-sfpp', 'SFP+ (8GFC)'), ('16gfc-sfpp', 'SFP+ (16GFC)'), ('32gfc-sfpp', 'SFP+ (32GFC)'), ('32gfc-sfp28', 'SFP28 (32GFC)'), ('64gfc-sfpp', 'SFP+ (64GFC)'), ('64gfc-sfpdd', 'SFP-DD (64GFC)'), ('64gfc-qsfpp', 'QSFP+ (64GFC)'), ('128gfc-qsfp28', 'QSFP28 (128GFC)')]), ('InfiniBand', [('infiniband-sdr', 'InfiniBand SDR (2 Gbps)'), ('infiniband-ddr', 'InfiniBand DDR (4 Gbps)'), ('infiniband-qdr', 'InfiniBand QDR (8 Gbps)'), ('infiniband-fdr10', 'InfiniBand FDR10 (10 Gbps)'), ('infiniband-fdr', 'InfiniBand FDR (13.5 Gbps)'), ('infiniband-edr', 'InfiniBand EDR (25 Gbps)'), ('infiniband-hdr', 'InfiniBand HDR (50 Gbps)'), ('infiniband-ndr', 'InfiniBand NDR (100 Gbps)'), ('infiniband-xdr', 'InfiniBand XDR (250 Gbps)')]), ('Serial / WAN', [('t1', 'T1 (1.544 Mbps)'), ('e1', 'E1 (2.048 Mbps)'), ('t3', 'T3 (45 Mbps)'), ('e3', 'E3 (34 Mbps)')]), ('Broadband (DSL / coax)', [('xdsl', 'xDSL'), ('docsis', 'DOCSIS'), ('moca', 'MoCA')]), ('PON', [('bpon', 'BPON (622 Mbps / 155 Mbps)'), ('epon', 'EPON (1 Gbps)'), ('10g-epon', '10G-EPON (10 Gbps)'), ('gpon', 'GPON (2.5 Gbps / 1.25 Gbps)'), ('xg-pon', 'XG-PON (10 Gbps / 2.5 Gbps)'), ('xgs-pon', 'XGS-PON (10 Gbps)'), ('ng-pon2', 'NG-PON2 (TWDM-PON)'), ('25g-pon', '25G-PON (25 Gbps)'), ('50g-pon', '50G-PON (50 Gbps)')]), ('Stacking', [('cisco-stackwise', 'Cisco StackWise'), ('cisco-stackwise-plus', 'Cisco StackWise Plus'), ('cisco-flexstack', 'Cisco FlexStack'), ('cisco-flexstack-plus', 'Cisco FlexStack Plus'), ('cisco-stackwise-80', 'Cisco StackWise-80'), ('cisco-stackwise-160', 'Cisco StackWise-160'), ('cisco-stackwise-320', 'Cisco StackWise-320'), ('cisco-stackwise-480', 'Cisco StackWise-480'), ('cisco-stackwise-1t', 'Cisco StackWise-1T'), ('juniper-vcp', 'Juniper VCP'), ('extreme-summitstack', 'Extreme SummitStack'), ('extreme-summitstack-128', 'Extreme SummitStack-128'), ('extreme-summitstack-256', 'Extreme SummitStack-256'), ('extreme-summitstack-512', 'Extreme SummitStack-512')]), ('Other', [('other', 'Other')])], default='', help_text='Media type slug, e.g. 10gbase-x-sfpp.', max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('mgmt_only', models.BooleanField(default=False)),
                ('module_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_templates', to='api.moduletype')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('module_type', 'name')},
            },
        ),
    ]
