# Generated by Django 5.2.15 on 2026-07-03 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_modulebay_moduletype_module_modulebaytemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Physical location within the site (building / floor / room).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racks', to='api.location'),
        ),
    ]
