# Generated by Django 5.2.15 on 2026-07-03 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_rack_location'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cabletermination',
            name='cabletermination_exactly_one_point',
        ),
        migrations.AddField(
            model_name='cabletermination',
            name='aux_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminations', to='api.auxport'),
        ),
        migrations.AddConstraint(
            model_name='cabletermination',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('aux_port__isnull', True), ('console_port__isnull', True), ('console_server_port__isnull', True), ('front_port__isnull', True), ('interface__isnull', False), ('power_feed__isnull', True), ('power_outlet__isnull', True), ('power_port__isnull', True), ('rear_port__isnull', True)), models.Q(('aux_port__isnull', True), ('console_port__isnull', True), ('console_server_port__isnull', True), ('front_port__isnull', False), ('interface__isnull', True), ('power_feed__isnull', True), ('power_outlet__isnull', True), ('power_port__isnull', True), ('rear_port__isnull', True)), models.Q(('aux_port__isnull', True), ('console_port__isnull', True), ('console_server_port__isnull', True), ('front_port__isnull', True), ('interface__isnull', True), ('power_feed__isnull', True), ('power_outlet__isnull', True), ('power_port__isnull', True), ('rear_port__isnull', False)), models.Q(('aux_port__isnull', True), ('console_port__isnull', False), ('console_server_port__isnull', True), ('front_port__isnull', True), ('interface__isnull', True), ('power_feed__isnull', True), ('power_outlet__isnull', True), ('power_port__isnull', True), ('rear_port__isnull', True)), models.Q(('aux_port__isnull', True), ('console_port__isnull', True), ('console_server_port__isnull', False), ('front_port__isnull', True), ('interface__isnull', True), ('power_feed__isnull', True), ('power_outlet__isnull', True), ('power_port__isnull', True), ('rear_port__isnull', True)), models.Q(('aux_port__isnull', True), ('console_port__isnull', True), ('console_server_port__isnull', True), ('front_port__isnull', True), ('interface__isnull', True), ('power_feed__isnull', True), ('power_outlet__isnull', True), ('power_port__isnull', False), ('rear_port__isnull', True)), models.Q(('aux_port__isnull', True), ('console_port__isnull', True), ('console_server_port__isnull', True), ('front_port__isnull', True), ('interface__isnull', True), ('power_feed__isnull', True), ('power_outlet__isnull', False), ('power_port__isnull', True), ('rear_port__isnull', True)), models.Q(('aux_port__isnull', True), ('console_port__isnull', True), ('console_server_port__isnull', True), ('front_port__isnull', True), ('interface__isnull', True), ('power_feed__isnull', False), ('power_outlet__isnull', True), ('power_port__isnull', True), ('rear_port__isnull', True)), models.Q(('aux_port__isnull', False), ('console_port__isnull', True), ('console_server_port__isnull', True), ('front_port__isnull', True), ('interface__isnull', True), ('power_feed__isnull', True), ('power_outlet__isnull', True), ('power_port__isnull', True), ('rear_port__isnull', True)), _connector='OR'), name='cabletermination_exactly_one_point'),
        ),
        migrations.AddConstraint(
            model_name='cabletermination',
            constraint=models.UniqueConstraint(condition=models.Q(('aux_port__isnull', False)), fields=('aux_port',), name='uniq_termination_aux_port'),
        ),
    ]
