# Generated by Django 5.2.15 on 2026-07-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_remove_cabletermination_cabletermination_exactly_one_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='max_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Load budget (see max_weight_unit) — what the rack/floor is rated to carry. Devices sum against it via their type's weight.", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='rack',
            name='max_weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('g', 'g'), ('lb', 'lb'), ('oz', 'oz')], default='', max_length=8),
        ),
    ]
