# Generated by Django 5.2.15 on 2026-07-03 22:29

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_rack_max_weight_rack_max_weight_unit'),
        ('core', '0011_tenantgroup_tenant_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='exclude_from_utilization',
            field=models.BooleanField(default=False, help_text="Don't count devices of this type toward rack space utilisation (blanking panels, cable management)."),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='subdevice_role',
            field=models.CharField(blank=True, choices=[('parent', 'Parent'), ('child', 'Child')], default='', help_text="Parent = chassis with device bays; child = installs into a parent's bay (blade / FEX). Blank for ordinary hardware.", max_length=8),
        ),
        migrations.CreateModel(
            name='DeviceBay',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_bays', to='api.device')),
                ('installed_device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_bay', to='api.device')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('device', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DeviceBayTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_bay_templates', to='api.devicetype')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('device_type', 'name')},
            },
        ),
    ]
