# Generated by Django 5.2.15 on 2026-07-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_topologyview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='duplex',
            field=models.CharField(blank=True, choices=[('half', 'Half'), ('full', 'Full'), ('auto', 'Auto')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='interface',
            name='mgmt_only',
            field=models.BooleanField(default=False, help_text='Out-of-band management interface.'),
        ),
        migrations.AddField(
            model_name='interface',
            name='poe_mode',
            field=models.CharField(blank=True, choices=[('pd', 'PD (powered device)'), ('pse', 'PSE (supplying)')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='interface',
            name='poe_type',
            field=models.CharField(blank=True, default='', help_text='IEEE standard / passive type, e.g. type2-ieee802.3at.', max_length=32),
        ),
        migrations.AddField(
            model_name='interface',
            name='wwn',
            field=models.CharField(blank=True, default='', help_text='World Wide Name (Fibre Channel), colon-separated hex.', max_length=32),
        ),
        migrations.AddField(
            model_name='interfacetemplate',
            name='poe_mode',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='interfacetemplate',
            name='poe_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='moduleinterfacetemplate',
            name='poe_mode',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='moduleinterfacetemplate',
            name='poe_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
