# Generated by Django 5.2.15 on 2026-07-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_interface_duplex_interface_mgmt_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduletype',
            name='faceplate',
            field=models.JSONField(blank=True, help_text="Saved faceplate layout for this module (FaceplateDoc v1); null → automatic layout. Composed into the host device's render at the bay it's installed in.", null=True),
        ),
    ]
