# Generated by Django 5.2.15 on 2026-07-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_moduletype_faceplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicerole',
            name='is_patch_panel',
            field=models.BooleanField(default=False, help_text='Devices with this role are passive patch panels — hidden in topology by default and kept out of the level tiers.'),
        ),
    ]
