# Generated by Django 5.2.15 on 2026-07-04 15:37

import django.core.validators
import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_devicerole_is_patch_panel'),
        ('core', '0011_tenantgroup_tenant_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('grid_width', models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(512)])),
                ('grid_height', models.PositiveSmallIntegerField(default=16, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(512)])),
                ('background_image', models.ImageField(blank=True, help_text='Blueprint/photo scaled under the grid.', null=True, upload_to='floor-plans/')),
                ('background_opacity', models.PositiveSmallIntegerField(default=60, help_text='Percent.', validators=[django.core.validators.MaxValueValidator(100)])),
                ('state', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='api.location')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FloorTileType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('icon', models.CharField(blank=True, default='', help_text='Lucide icon name (e.g. server, door-closed, wind, cctv).', max_length=48)),
                ('default_width', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(512)])),
                ('default_height', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(512)])),
                ('description', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_tile_types', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FloorPlanTile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.PositiveSmallIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('width', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(512)])),
                ('height', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(512)])),
                ('orientation', models.PositiveSmallIntegerField(choices=[(0, '0°'), (90, '90°'), (180, '180°'), (270, '270°')], default=0)),
                ('label', models.CharField(blank=True, default='', max_length=64)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('planned', 'Planned'), ('reserved', 'Reserved'), ('decommissioning', 'Decommissioning')], default='', max_length=16)),
                ('link_kind', models.CharField(blank=True, default='', max_length=16)),
                ('fov_deg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fov_distance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fov_direction', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_tiles', to='api.device')),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='api.floorplan')),
                ('linked_floor_plan', models.ForeignKey(blank=True, help_text='Nested plan: clicking this tile navigates into it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from_tiles', to='api.floorplan')),
                ('power_feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_tiles', to='api.powerfeed')),
                ('power_panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_tiles', to='api.powerpanel')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_tiles', to='api.rack')),
                ('role_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='floor_tiles', to='api.devicerole')),
                ('tile_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiles', to='api.floortiletype')),
            ],
            options={
                'ordering': ['y', 'x'],
            },
        ),
        migrations.AddConstraint(
            model_name='floorplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'location', 'name'), name='uniq_floorplan_tenant_location_name'),
        ),
        migrations.AddConstraint(
            model_name='floortiletype',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_floortiletype_tenant_slug'),
        ),
        migrations.AddIndex(
            model_name='floorplantile',
            index=models.Index(fields=['floor_plan'], name='api_floorpl_floor_p_bd0544_idx'),
        ),
        migrations.AddConstraint(
            model_name='floorplantile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role_type__isnull', True), ('tile_type__isnull', False)), models.Q(('role_type__isnull', False), ('tile_type__isnull', True)), _connector='OR'), name='floorplantile_exactly_one_type'),
        ),
        migrations.AddConstraint(
            model_name='floorplantile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('device__isnull', True), ('linked_floor_plan__isnull', True), ('power_feed__isnull', True), ('power_panel__isnull', True), ('rack__isnull', True)), models.Q(('device__isnull', True), ('linked_floor_plan__isnull', True), ('power_feed__isnull', True), ('power_panel__isnull', True), ('rack__isnull', False)), models.Q(('device__isnull', False), ('linked_floor_plan__isnull', True), ('power_feed__isnull', True), ('power_panel__isnull', True), ('rack__isnull', True)), models.Q(('device__isnull', True), ('linked_floor_plan__isnull', True), ('power_feed__isnull', True), ('power_panel__isnull', False), ('rack__isnull', True)), models.Q(('device__isnull', True), ('linked_floor_plan__isnull', True), ('power_feed__isnull', False), ('power_panel__isnull', True), ('rack__isnull', True)), models.Q(('device__isnull', True), ('linked_floor_plan__isnull', False), ('power_feed__isnull', True), ('power_panel__isnull', True), ('rack__isnull', True)), _connector='OR'), name='floorplantile_at_most_one_link'),
        ),
    ]
