# Generated by Django 5.2.15 on 2026-07-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_floorplan_floortiletype_floorplantile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorplantile',
            name='numid',
        ),
    ]
