# Generated by Django 5.2.15 on 2026-07-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_remove_floorplantile_numid'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicerole',
            name='has_fov',
            field=models.BooleanField(default=False, help_text='Floor-plan tiles typed by this role get camera field-of-view controls (e.g. a CCTV role).'),
        ),
        migrations.AddField(
            model_name='floortiletype',
            name='has_fov',
            field=models.BooleanField(default=False, help_text='Tiles of this type get camera field-of-view controls (direction / angle / distance cone).'),
        ),
        migrations.AddField(
            model_name='floortiletype',
            name='is_zone',
            field=models.BooleanField(default=False, help_text='Zone tiles paint the grid background (hot/cold aisles, security areas) — they render under normal tiles and other tiles may sit on top of them.'),
        ),
    ]
