# Generated by Django 5.2.15 on 2026-07-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_devicerole_has_fov_floortiletype_has_fov_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplantile',
            name='fov_anchor',
            field=models.CharField(blank=True, choices=[('', 'Center'), ('tl', 'Top left'), ('tr', 'Top right'), ('bl', 'Bottom left'), ('br', 'Bottom right')], default='', help_text="Where on the tile the cone emits from ('' = center).", max_length=2),
        ),
    ]
