# Generated by Django 5.2.15 on 2026-07-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_floorplantile_fov_anchor'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplantile',
            name='fov_ptz',
            field=models.BooleanField(default=False, help_text='Pan-tilt-zoom: coverage renders as a full 360° ring (radius = reach) instead of a fixed cone.'),
        ),
    ]
