# Generated by Django 5.2.15 on 2026-07-04 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_floorplantile_fov_ptz'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlanTray',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('kind', models.CharField(blank=True, default='', max_length=32)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('points', models.JSONField(default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('cables', models.ManyToManyField(blank=True, help_text='The physical cables routed through this tray.', related_name='trays', to='api.cable')),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trays', to='api.floorplan')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['floor_plan'], name='api_floorpl_floor_p_119960_idx')],
            },
        ),
    ]
