# Generated by Django 5.2.15 on 2026-07-05 15:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_floorplantray'),
        ('core', '0011_tenantgroup_tenant_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='fiber_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of fibre strands in the cable (2, 12, 24, 48…).', null=True),
        ),
        migrations.AddField(
            model_name='cable',
            name='strands',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='FiberSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiber_settings', to='core.tenant')),
            ],
            options={
                'verbose_name': 'fibre settings',
                'verbose_name_plural': 'fibre settings',
            },
        ),
    ]
