# Generated by Django 5.2.15 on 2026-07-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_cable_fiber_count_cable_strands_fibersettings'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='frontport',
            name='uniq_frontport_rear_position',
        ),
        migrations.RemoveConstraint(
            model_name='frontporttemplate',
            name='uniq_frontporttemplate_rear_position',
        ),
        migrations.AddField(
            model_name='fibersettings',
            name='strand_modelling',
            field=models.CharField(choices=[('off', 'Off'), ('count', 'Count + colours'), ('accurate', 'Strand-accurate')], default='count', max_length=8),
        ),
        migrations.AddField(
            model_name='frontport',
            name='positions',
            field=models.PositiveSmallIntegerField(default=1, help_text='Fibre strands this connector carries (LC=1, LC-duplex=2, MPO=8–24). Claims that many consecutive rear-port positions from the start.'),
        ),
        migrations.AddField(
            model_name='frontporttemplate',
            name='positions',
            field=models.PositiveSmallIntegerField(default=1, help_text='Fibre strands the connector carries.'),
        ),
        migrations.AlterField(
            model_name='frontport',
            name='rear_port_position',
            field=models.PositiveSmallIntegerField(default=1, help_text='First rear-port position (strand) this maps onto.'),
        ),
    ]
