# Generated by Django 5.2.15 on 2026-07-10 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_remove_frontport_uniq_frontport_rear_position_and_more'),
        ('core', '0013_alter_bookmark_options_bookmark_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='device-images/')),
                ('name', models.CharField(blank=True, default='', help_text='Optional caption shown under the image.', max_length=128)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Display order; lower sorts first.')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.device')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_images', to='core.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['device', 'sort_order'], name='api_devicei_device__28df22_idx')],
            },
        ),
    ]
