# Generated by Django 5.2.15 on 2026-07-10 18:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_deviceimage'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0013_alter_bookmark_options_bookmark_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('image', models.ImageField(upload_to='image-attachments/')),
                ('name', models.CharField(blank=True, default='', help_text='Optional caption shown under the image.', max_length=128)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Display order; lower sorts first.')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_attachments', to='core.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DeviceImage',
        ),
        migrations.AddIndex(
            model_name='imageattachment',
            index=models.Index(fields=['content_type', 'object_id', 'sort_order'], name='api_imageat_content_ab0661_idx'),
        ),
    ]
