# Generated by Django 5.2.15 on 2026-07-11 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_seed_not_connected_cable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='monitored',
            field=models.BooleanField(default=False, help_text="When on, each port is watched by a TCP/UDP check against the service's target IP (its own IP, else the parent's primary IP). Reconciled by monitoring.service_checks.sync_service_checks."),
        ),
        migrations.CreateModel(
            name='DeviceTypeService',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='tcp', max_length=4)),
                ('ports', models.JSONField(default=list, help_text='List of port numbers.')),
                ('monitor', models.BooleanField(default=False, help_text='Materialised services start monitored.')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_templates', to='api.devicetype')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('device_type', 'name')},
            },
        ),
    ]
