# Generated by Django 5.2.15 on 2026-07-15 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_service_monitored_devicetypeservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='default_prefix',
            field=models.ForeignKey(blank=True, help_text="The prefix new addresses at this site come from by default — so staff working at one site don't have to hunt for the right subnet. A hint, not a constraint: the picker still offers every prefix.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_sites', to='api.prefix'),
        ),
    ]
