# Generated by Django 5.2.15 on 2026-07-15 21:00

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_site_default_prefix'),
        ('core', '0018_deploymentsettings_allow_site_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='owning_site',
            field=models.ForeignKey(blank=True, help_text='Set = local to that site (enhanced site separation); empty = global to the tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.site'),
        ),
        migrations.AddField(
            model_name='iprole',
            name='owning_site',
            field=models.ForeignKey(blank=True, help_text='Set = local to that site (enhanced site separation); empty = global to the tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.site'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='owning_site',
            field=models.ForeignKey(blank=True, help_text='Set = local to that site (enhanced site separation); empty = global to the tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.site'),
        ),
        migrations.AddField(
            model_name='routetarget',
            name='owning_site',
            field=models.ForeignKey(blank=True, help_text='Set = local to that site (enhanced site separation); empty = global to the tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.site'),
        ),
        migrations.AddField(
            model_name='status',
            name='owning_site',
            field=models.ForeignKey(blank=True, help_text='Set = local to that site (enhanced site separation); empty = global to the tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.site'),
        ),
        migrations.AddField(
            model_name='vrf',
            name='owning_site',
            field=models.ForeignKey(blank=True, help_text='Set = local to that site (enhanced site separation); empty = global to the tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.site'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=80)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('weight', models.PositiveIntegerField(default=100, help_text='Lower weights sort first in dropdowns and lists.')),
                ('owning_site', models.ForeignKey(blank=True, help_text='Set = local to that site (enhanced site separation); empty = global to the tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.site')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['weight', 'name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vlan',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Security zone this segment belongs to (zone-based firewalling).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlans', to='api.zone'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_zone_tenant_slug'),
        ),
    ]
