# Generated by Django 5.2.15 on 2026-07-16 10:23

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_devicetype_owning_site_iprole_owning_site_and_more'),
        ('core', '0022_deploymentsettings_ssrf_allowlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetemplate',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='User-defined custom fields'),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
    ]
