# Generated by Django 5.2.15 on 2026-07-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_servicetemplate_custom_fields_servicetemplate_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='end_of_sale',
            field=models.DateField(blank=True, help_text='Vendor stops selling it (EoS).', null=True),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='end_of_security_updates',
            field=models.DateField(blank=True, help_text='Last security / vulnerability fixes.', null=True),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='end_of_support',
            field=models.DateField(blank=True, help_text='End of life — vendor support and maintenance ends.', null=True),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='lifecycle_url',
            field=models.URLField(blank=True, default='', help_text='Vendor end-of-life notice.'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='release_date',
            field=models.DateField(blank=True, help_text='GA / first-ship date — the start of the lifetime bar.', null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='end_of_sale',
            field=models.DateField(blank=True, help_text='Vendor stops selling it (EoS).', null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='end_of_security_updates',
            field=models.DateField(blank=True, help_text='Last security / vulnerability fixes.', null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='end_of_support',
            field=models.DateField(blank=True, help_text='End of life — vendor support and maintenance ends.', null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='lifecycle_url',
            field=models.URLField(blank=True, default='', help_text='Vendor end-of-life notice.'),
        ),
        migrations.AddField(
            model_name='platform',
            name='release_date',
            field=models.DateField(blank=True, help_text='GA / first-ship date — the start of the lifetime bar.', null=True),
        ),
    ]
