# Generated by Django 5.2.15 on 2026-07-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_devicetype_end_of_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude (decimal degrees).', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude (decimal degrees).', max_digits=9, null=True),
        ),
    ]
