# Generated by Django 5.2.15 on 2026-07-16 15:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_site_latitude_site_longitude'),
        ('core', '0023_deploymentsettings_map_tile_attribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='fov_deg',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='fov_direction',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='fov_distance_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='fov_ptz',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SiteMarker',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('label', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('fov_direction', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fov_deg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fov_distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('fov_ptz', models.BooleanField(default=False)),
                ('role_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_markers', to='api.devicerole')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_markers', to='core.tenant')),
                ('tile_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_markers', to='api.floortiletype')),
            ],
            options={
                'ordering': ['label'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('role_type__isnull', True), ('tile_type__isnull', False)), models.Q(('role_type__isnull', False), ('tile_type__isnull', True)), _connector='OR'), name='sitemarker_exactly_one_type')],
            },
        ),
    ]
