# Generated by Django 5.2.15 on 2026-07-16 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_device_fov_deg_device_fov_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemarker',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_markers', to='api.device'),
        ),
    ]
