# Generated by Django 5.2.15 on 2026-07-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_sitemarker_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='rearport',
            name='is_splitter',
            field=models.BooleanField(default=False, help_text='Optical splitter: every front port fans out from position 1 and carries the same signal (PON). Requires positions=1.'),
        ),
        migrations.AddField(
            model_name='rearporttemplate',
            name='is_splitter',
            field=models.BooleanField(default=False, help_text='Optical splitter: every front port fans out from position 1 and carries the same signal (PON). Requires positions=1.'),
        ),
    ]
