# Generated by Django 5.2.15 on 2026-07-17 09:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_rearport_is_splitter_rearporttemplate_is_splitter'),
        ('core', '0024_deploymentsettings_map_satellite_attribution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableRoute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('kind', models.CharField(blank=True, default='', max_length=32)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('waypoints', models.JSONField(default=list)),
                ('description', models.TextField(blank=True, default='')),
                ('cables', models.ManyToManyField(blank=True, help_text='The physical cables routed along this run.', related_name='routes', to='api.cable')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cable_routes', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant'], name='api_cablero_tenant__561ea3_idx')],
            },
        ),
    ]
