# Generated by Django 5.2.15 on 2026-07-20 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_cableroute'),
        ('core', '0026_deploymentsettings_disable_update_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='platform',
            field=models.ForeignKey(blank=True, help_text='Default OS platform for devices of this type. A device without its own platform inherits it (its effective platform).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_types', to='api.platform'),
        ),
        migrations.CreateModel(
            name='PlatformGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.platformgroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_groups', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='platform',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platforms', to='api.platformgroup'),
        ),
        migrations.AddConstraint(
            model_name='platformgroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_platformgroup_tenant_slug'),
        ),
    ]
