# Generated by Django 5.2.15 on 2026-07-20 12:53

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_cableroute'),
        ('core', '0026_deploymentsettings_disable_update_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicerole',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='platform',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
    ]
