# Generated by Django 5.2.15 on 2026-07-21 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_devicetype_platform_platformgroup_platform_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='switch',
            field=models.ForeignKey(blank=True, help_text='Access switch this IP is reached through (the device that owns the switch port). Its virtual chassis, if any, is derived from the device.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.device'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='switch_interface',
            field=models.ForeignKey(blank=True, help_text="Physical switch port this IP is behind. Setting it keeps `switch` in sync with the port's device.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.interface'),
        ),
    ]
