# Generated by Django 5.2.15 on 2026-07-22 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_ipaddress_switch_ipaddress_switch_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulebaytemplate',
            name='default_module_type',
            field=models.ForeignKey(blank=True, help_text="Pre-install a module of this type when the bay is stamped onto a new device, and into an empty matching bay on sync-from-type. Fully replaceable afterwards — this only decides what's pre-seated.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_in_bay_templates', to='api.moduletype'),
        ),
    ]
