# Generated by Django 5.2.15 on 2026-07-22 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_modulebaytemplate_default_module_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='ceiling_mm',
            field=models.PositiveSmallIntegerField(default=3000, help_text='Room ceiling height, in millimetres.', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(20000)]),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='cell_mm',
            field=models.PositiveSmallIntegerField(default=600, help_text='Physical size of one grid cell, in millimetres.', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AddField(
            model_name='floorplantray',
            name='elevation_mm',
            field=models.IntegerField(blank=True, help_text='Height above finished floor in millimetres (negative = below the raised floor). Blank derives from the level: overhead → ceiling − 300, underfloor → −300, floor → 0.', null=True, validators=[django.core.validators.MinValueValidator(-2000), django.core.validators.MaxValueValidator(20000)]),
        ),
        migrations.AddField(
            model_name='floorplantray',
            name='level',
            field=models.CharField(choices=[('overhead', 'Overhead'), ('underfloor', 'Underfloor'), ('floor', 'Floor level')], default='overhead', max_length=16),
        ),
        migrations.AddField(
            model_name='rack',
            name='outer_depth_mm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cabinet outer depth in millimetres (blank = 1000).', null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(3000)]),
        ),
        migrations.AddField(
            model_name='rack',
            name='outer_width_mm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cabinet outer width in millimetres (blank = derived).', null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
