# Generated by Django 5.2.15 on 2026-07-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_devicetypeimportrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='image_ports',
            field=models.JSONField(blank=True, default=None, help_text='Port markers anchored on the front/rear photo: {front:[{kind,name,x,y,w,h}], rear:[...]} with x/y/w/h normalized 0..1 (center-anchored). Rendered over the image in 2D and on the device face in 3D. Null = none placed.', null=True),
        ),
    ]
