# Generated by Django 5.2.15 on 2026-07-24 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_devicetype_image_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='capacity_bytes',
            field=models.PositiveBigIntegerField(blank=True, help_text='Capacity in BYTES (unit-agnostic: KB floppies to PB arrays; the UI converts).', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='kind',
            field=models.CharField(choices=[('other', 'Other'), ('disk', 'Disk'), ('cpu', 'CPU'), ('ram', 'RAM'), ('psu', 'PSU'), ('fan', 'Fan'), ('gpu', 'GPU'), ('controller', 'Controller'), ('transceiver', 'Transceiver')], default='other', max_length=16),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='media',
            field=models.CharField(blank=True, choices=[('', '—'), ('nvme', 'NVMe'), ('ssd', 'SSD (SATA/SAS)'), ('hdd', 'HDD'), ('tape', 'Tape')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='speed',
            field=models.CharField(blank=True, default='', help_text='Free-form: "7.2K RPM", "PCIe 4.0 x4", "3200 MT/s".', max_length=64),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='api.status'),
        ),
        migrations.AddField(
            model_name='inventoryitemtemplate',
            name='capacity_bytes',
            field=models.PositiveBigIntegerField(blank=True, help_text='Capacity in BYTES (unit-agnostic: KB floppies to PB arrays; the UI converts).', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitemtemplate',
            name='kind',
            field=models.CharField(choices=[('other', 'Other'), ('disk', 'Disk'), ('cpu', 'CPU'), ('ram', 'RAM'), ('psu', 'PSU'), ('fan', 'Fan'), ('gpu', 'GPU'), ('controller', 'Controller'), ('transceiver', 'Transceiver')], default='other', max_length=16),
        ),
        migrations.AddField(
            model_name='inventoryitemtemplate',
            name='media',
            field=models.CharField(blank=True, choices=[('', '—'), ('nvme', 'NVMe'), ('ssd', 'SSD (SATA/SAS)'), ('hdd', 'HDD'), ('tape', 'Tape')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='inventoryitemtemplate',
            name='speed',
            field=models.CharField(blank=True, default='', help_text='Free-form: "7.2K RPM", "PCIe 4.0 x4", "3200 MT/s".', max_length=64),
        ),
    ]
