# Generated by Django 5.2.15 on 2026-07-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_natural_sort_collation'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='snmp_name',
            field=models.CharField(blank=True, default='', help_text="What the agent calls this interface over SNMP (ifName / ifDescr) when it differs from the label — e.g. the port silkscreened 'Ethernet 1' reporting as 'eth0'. Set it and discovery stops reporting the pair as both new and missing.", max_length=128),
        ),
    ]
