# Generated by Django 5.2.15 on 2026-07-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_interface_snmp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='snmp_ignore',
            field=models.BooleanField(default=False, help_text="Exclude this interface from SNMP drift. For ports the polled agent can never report — silkscreened ports a BMC doesn't see, out-of-band jacks — which would otherwise flag as 'not seen on device' after every poll, forever."),
        ),
    ]
