# Generated by Django 5.2.15 on 2026-07-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_interface_snmp_ignore'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontport',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='interface',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rearport',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
