# Generated by Django 5.2.15 on 2026-07-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_frontport_description_interface_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetypeimportrun',
            name='kind',
            field=models.CharField(choices=[('library', 'Library import'), ('image_reimport', 'Image reimport')], default='library', max_length=16),
        ),
        migrations.AddField(
            model_name='devicetypeimportrun',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
