# Generated by Django 5.2.15 on 2026-07-25 19:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_devicetypeimportrun_kind_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplantray',
            name='elevation_mm',
            field=models.IntegerField(blank=True, help_text='Height above finished floor in millimetres (negative = below the raised floor). Blank derives from the level: overhead → ceiling − 300, underfloor → the plenum of the raised-floor area beneath the run (default 300), floor → 0.', null=True, validators=[django.core.validators.MinValueValidator(-2000), django.core.validators.MaxValueValidator(20000)]),
        ),
        migrations.CreateModel(
            name='FloorPlanRaisedFloorArea',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.PositiveSmallIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('width', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('plenum_mm', models.PositiveSmallIntegerField(default=300, help_text='Void depth under the finished floor — how far below 0 the structural slab sits here.', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(2000)])),
                ('label', models.CharField(blank=True, default='', max_length=64)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_floor_areas', to='api.floorplan')),
            ],
            options={
                'ordering': ['y', 'x'],
                'indexes': [models.Index(fields=['floor_plan'], name='api_floorpl_floor_p_c1423a_idx')],
            },
        ),
    ]
