# Generated by Django 5.2.15 on 2026-07-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_floorplanwall'),
    ]

    operations = [
        migrations.AddField(
            model_name='floortiletype',
            name='perforated',
            field=models.BooleanField(default=False, help_text='Zone tiles of this type render as perforated/grate floor in the 3D room — the cold-aisle supply-tile read.'),
        ),
    ]
