# Generated by Django 5.2.15 on 2026-07-26 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_floortiletype_perforated'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mount',
            field=models.CharField(blank=True, choices=[('side_left', 'Left rail'), ('side_right', 'Right rail')], default='', help_text='Zero-U side mounting: the rack rail this device bolts to instead of occupying units. Requires a rack, a 0U device type, and no U position/face/side.', max_length=12),
        ),
        migrations.AddField(
            model_name='device',
            name='mount_offset_mm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Bottom of the side-mounted strip above the base plate.', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='mount_span_u',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Vertical extent of the side-mounted strip, in U. Blank draws ~three quarters of the rack.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
