# Generated by Django 5.2.15 on 2026-07-26 09:04

import django.core.validators
import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_device_side_mount'),
        ('core', '0031_deploymentsettings_rq_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='RackType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('width', models.PositiveSmallIntegerField(choices=[(10, '10"'), (19, '19"'), (21, '21"'), (23, '23"')], default=19, help_text='Rail-to-rail width, inches.')),
                ('u_height', models.PositiveSmallIntegerField(default=42, help_text='Height in rack units (U).')),
                ('starting_unit', models.PositiveSmallIntegerField(default=1, help_text='Number of the bottom unit.')),
                ('desc_units', models.BooleanField(default=False, help_text='Number units top-to-bottom instead of bottom-up.')),
                ('outer_width_mm', models.PositiveSmallIntegerField(blank=True, help_text='Cabinet outer width in millimetres (blank = derived).', null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(2000)])),
                ('outer_depth_mm', models.PositiveSmallIntegerField(blank=True, help_text='Cabinet outer depth in millimetres (blank = 1000).', null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(3000)])),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Load budget this cabinet model is rated for.', max_digits=8, null=True)),
                ('max_weight_unit', models.CharField(blank=True, choices=[('kg', 'kg'), ('g', 'g'), ('lb', 'lb'), ('oz', 'oz')], default='', max_length=8)),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rack_types', to='api.manufacturer')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_types', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='rack',
            name='rack_type',
            field=models.ForeignKey(blank=True, help_text='The cabinet model this rack is an instance of.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racks', to='api.racktype'),
        ),
        migrations.CreateModel(
            name='RackTypeAccessory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Suffix for stamped devices (e.g. PDU-A).', max_length=64)),
                ('mount', models.CharField(choices=[('side_left', 'Left rail'), ('side_right', 'Right rail')], max_length=12)),
                ('mount_offset_mm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mount_span_u', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('device_type', models.ForeignKey(help_text='Must be a 0U device type (vertical strips side-mount).', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.devicetype')),
                ('rack_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='api.racktype')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AddConstraint(
            model_name='racktype',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_racktype_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='racktypeaccessory',
            constraint=models.UniqueConstraint(fields=('rack_type', 'label'), name='uniq_racktypeaccessory_type_label'),
        ),
    ]
