# Generated by Django 5.2.15 on 2026-07-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_rack_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='racktypeaccessory',
            name='face',
            field=models.CharField(blank=True, choices=[('front', 'Front'), ('rear', 'Rear')], default='', help_text='Which channel the strip bolts into. Blank draws it on both elevations, which is rarely what a real PDU does.', max_length=5),
        ),
        migrations.AlterField(
            model_name='device',
            name='mount',
            field=models.CharField(blank=True, choices=[('side_left', 'Left rail'), ('side_right', 'Right rail')], default='', help_text='Zero-U side mounting: the rack rail this device bolts to instead of occupying units. Requires a rack and a 0U device type, and no U position or half-width side. ``face`` stays meaningful — it says which channel (front/rear) the strip lives in; blank shows it on both.', max_length=12),
        ),
    ]
