# Generated by Django 5.2.15 on 2026-07-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_site_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='vminterface',
            name='speed',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
