# Generated by Django 5.2.15 on 2026-07-31 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_vminterface_speed'),
        ('core', '0033_deploymentsettings_vault_addr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('object_type', models.CharField(help_text='Object-type slug this labels (see the RBAC registry).', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('width_mm', models.FloatField(default=62.0)),
                ('height_mm', models.FloatField(default=29.0)),
                ('margin_mm', models.FloatField(default=2.0)),
                ('template_html', models.TextField(blank=True, default='', help_text='Jinja2 HTML. Context: the object under its type name (e.g. `device`), plus `obj`, `url`, `qr`, and common relations.')),
                ('css', models.TextField(blank=True, default='')),
                ('qr_enabled', models.BooleanField(default=True)),
                ('qr_content', models.CharField(blank=True, default='', help_text="Jinja2 expression for what the QR encodes. Blank = the object's absolute URL.", max_length=512)),
                ('qr_size_mm', models.FloatField(default=18.0)),
                ('is_default', models.BooleanField(default=False, help_text='Preselected when printing labels for this object type.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_templates', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_labeltemplate_tenant_name')],
            },
        ),
    ]
