# Generated by Django 5.2.16 on 2026-08-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_labeltemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltemplate',
            name='device_types',
            field=models.ManyToManyField(blank=True, related_name='label_templates', to='api.devicetype'),
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='label_templates', to='api.devicerole'),
        ),
    ]
