# Generated by Django 5.2.16 on 2026-08-01 11:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_labeltemplate_device_types_labeltemplate_roles'),
        ('core', '0034_tenantsettings_onboarding_dismissed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, default='', max_length=140)),
                ('color', models.CharField(blank=True, default='', help_text='Optional hex swatch (e.g. #2563eb) for the category badge.', max_length=7)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_categories', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'document categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(help_text='Model label, e.g. api.device.', max_length=64)),
                ('object_id', models.UUIDField()),
                ('object_site_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='Document title.', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('url', models.URLField(blank=True, default='', max_length=2048)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('link_status', models.CharField(choices=[('unknown', 'Unknown'), ('ok', 'OK'), ('broken', 'Broken')], default='unknown', max_length=8)),
                ('link_checked_at', models.DateTimeField(blank=True, null=True)),
                ('link_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='api.document')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.tenant')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='api.documentcategory')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_documentcategory_tenant_name'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['object_type', 'object_id', 'sort_order'], name='api_documen_object__f8b704_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('file__isnull', False), models.Q(('file', ''), _negated=True), ('url', '')), models.Q(models.Q(('url', ''), _negated=True), models.Q(('file__isnull', True), ('file', ''), _connector='OR')), _connector='OR'), name='document_exactly_one_of_file_or_url'),
        ),
    ]
