# Generated by Django 5.2.16 on 2026-08-13 19:59
#
# Semantic flags for maintenance/outage workflow statuses, then extend every
# tenant's built-in catalog with the issue #20 vocabularies (tentative →
# completed, reported → resolved). Required system data: MaintenanceEvent.status
# FKs these rows. Idempotent — seed_builtin_statuses merges by slug.

from django.db import migrations, models


def seed(apps, schema_editor):
    from api.status_registry import seed_builtin_statuses

    Tenant = apps.get_model("core", "Tenant")
    Status = apps.get_model("api", "Status")
    for tenant in Tenant.objects.all():
        seed_builtin_statuses(tenant, Status=Status)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_documentcategory_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_closed',
            field=models.BooleanField(default=False, help_text="Marks the workflow as finished — a closed maintenance/outage event leaves the open list, the calendar's open count, and releases its silence."),
        ),
        migrations.AddField(
            model_name='status',
            name='suppresses_alerts',
            field=models.BooleanField(default=False, help_text='While a maintenance/outage event carries this status, monitoring alerts for its impacted devices are silenced (maintenance & outage events).'),
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
