# Generated by Django 5.2.16 on 2026-08-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_status_is_closed_status_suppresses_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='is_uplink',
            field=models.BooleanField(default=False, help_text='This port faces other network infrastructure. It never gets switch-link suggestions — the MACs it learns belong to hosts behind it, not on it. The escape hatch when the automatic uplink detection misreads a topology.'),
        ),
    ]
