# Generated by Django 5.2.16 on 2026-08-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_interface_is_uplink'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='combo_group',
            field=models.CharField(blank=True, default='', help_text='Combo/shared port: interfaces on this device with the same group are alternate connectors for one logical port — enabling one disables the others.', max_length=64),
        ),
        migrations.AddField(
            model_name='interfacetemplate',
            name='combo_group',
            field=models.CharField(blank=True, default='', help_text='Combo/shared port group — materialised onto each device so its alternate connectors stay mutually exclusive.', max_length=64),
        ),
    ]
