# Generated by Django 5.2.16 on 2026-08-17 10:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_interface_combo_group_interfacetemplate_combo_group'),
        ('core', '0040_deploymentsettings_component_popover_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualDisk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('size_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('storage', models.CharField(blank=True, default='', max_length=128)),
                ('controller', models.CharField(blank=True, choices=[('scsi', 'SCSI'), ('virtio', 'VirtIO'), ('ide', 'IDE'), ('sata', 'SATA'), ('nvme', 'NVMe')], default='', max_length=16)),
                ('disk_format', models.CharField(blank=True, default='', max_length=16)),
                ('created_disk', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disks', to='api.virtualmachine')),
            ],
            options={
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('vm', 'key'), name='uniq_virtualdisk_vm_key')],
            },
        ),
        migrations.CreateModel(
            name='VirtualSwitch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('kind', models.CharField(blank=True, choices=[('standard', 'Standard switch'), ('distributed', 'Distributed switch'), ('linux-bridge', 'Linux bridge'), ('ovs', 'Open vSwitch'), ('bond', 'Bond')], default='', max_length=16)),
                ('uplinks', models.CharField(blank=True, default='', max_length=255)),
                ('mtu', models.IntegerField(blank=True, null=True)),
                ('created_switch', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_switches', to='api.cluster')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_switches', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'cluster', 'name'), name='uniq_virtualswitch_tenant_cluster_name')],
            },
        ),
    ]
