# Generated by Django 5.2.16 on 2026-08-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_virtualdisk_virtualswitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualswitch',
            name='uplink_interfaces',
            field=models.ManyToManyField(blank=True, related_name='uplink_switches', to='api.interface'),
        ),
    ]
