# Generated by Django 5.2.16 on 2026-08-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_virtualswitch_uplink_interfaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
