# Generated by Django 5.2.16 on 2026-08-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_vlan_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='apply_site_to_vms',
            field=models.BooleanField(default=False, help_text='Give VMs on this cluster its site when they have none.'),
        ),
    ]
