# Generated by Django 5.2.16 on 2026-08-19 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_backfill_iprange_vrf'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualswitch',
            name='vrf',
            field=models.ForeignKey(blank=True, help_text="Default routing context for addresses on this switch's networks. Leave empty to follow the sync source.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='virtual_switches', to='api.vrf'),
        ),
    ]
