# Generated by Django 5.2.16 on 2026-08-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_vswitch_network_vrf'),
    ]

    operations = [
        migrations.AddField(
            model_name='vminterface',
            name='created_interface',
            field=models.BooleanField(default=False),
        ),
    ]
