# Generated by Django 5.2.16 on 2026-08-19 21:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_vminterface_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='color',
            field=models.CharField(blank=True, default='', help_text="Optional 7-char hex - the physical cable's color.", max_length=7),
        ),
        migrations.AlterField(
            model_name='cable',
            name='label',
            field=models.CharField(blank=True, default='', help_text="Free-form physical label (matches NetBox's cable label) - what's printed on the cable's tag.", max_length=255),
        ),
        migrations.AlterField(
            model_name='cable',
            name='type',
            field=models.CharField(blank=True, choices=[('Copper - twisted pair', [('cat3', 'CAT3'), ('cat5', 'CAT5'), ('cat5e', 'CAT5e'), ('cat6', 'CAT6'), ('cat6a', 'CAT6a'), ('cat7', 'CAT7'), ('cat7a', 'CAT7a'), ('cat8', 'CAT8'), ('mrj21-trunk', 'MRJ21 Trunk')]), ('Copper - twinax / DAC', [('dac-active', 'Direct Attach Copper (Active)'), ('dac-passive', 'Direct Attach Copper (Passive)')]), ('Copper - coaxial', [('coaxial', 'Coaxial'), ('rg-6', 'RG-6'), ('rg-8', 'RG-8'), ('rg-11', 'RG-11'), ('rg-59', 'RG-59'), ('rg-62', 'RG-62'), ('rg-213', 'RG-213'), ('lmr-100', 'LMR-100'), ('lmr-200', 'LMR-200'), ('lmr-400', 'LMR-400')]), ('Fiber - multimode', [('mmf', 'Multimode Fiber'), ('mmf-om1', 'Multimode Fiber (OM1)'), ('mmf-om2', 'Multimode Fiber (OM2)'), ('mmf-om3', 'Multimode Fiber (OM3)'), ('mmf-om4', 'Multimode Fiber (OM4)'), ('mmf-om5', 'Multimode Fiber (OM5)')]), ('Fiber - single-mode', [('smf', 'Single-mode Fiber'), ('smf-os1', 'Single-mode Fiber (OS1)'), ('smf-os2', 'Single-mode Fiber (OS2)')]), ('Fiber - other', [('aoc', 'Active Optical Cabling (AOC)')]), ('Power / other', [('power', 'Power'), ('usb', 'USB')])], help_text='Cable medium, e.g. cat6 / dac-passive / smf-os2 / mmf-om4.', max_length=64),
        ),
        migrations.AlterField(
            model_name='configcontext',
            name='weight',
            field=models.PositiveIntegerField(default=1000, help_text='Merge order - higher weight wins on conflicts.'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mount',
            field=models.CharField(blank=True, choices=[('side_left', 'Left rail'), ('side_right', 'Right rail')], default='', help_text='Zero-U side mounting: the rack rail this device bolts to instead of occupying units. Requires a rack and a 0U device type, and no U position or half-width side. ``face`` stays meaningful - it says which channel (front/rear) the strip lives in; blank shows it on both.', max_length=12),
        ),
        migrations.AlterField(
            model_name='devicerole',
            name='is_patch_panel',
            field=models.BooleanField(default=False, help_text='Devices with this role are passive patch panels - hidden in topology by default and kept out of the level tiers.'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='end_of_support',
            field=models.DateField(blank=True, help_text='End of life - vendor support and maintenance ends.', null=True),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='release_date',
            field=models.DateField(blank=True, help_text='GA / first-ship date - the start of the lifetime bar.', null=True),
        ),
        migrations.AlterField(
            model_name='exporttemplate',
            name='template_code',
            field=models.TextField(help_text='Jinja2 source. Context: `objects` (and `queryset`) - the objects of this type in the active tenant.'),
        ),
        migrations.AlterField(
            model_name='floorplanraisedfloorarea',
            name='plenum_mm',
            field=models.PositiveSmallIntegerField(default=300, help_text='Void depth under the finished floor - how far below 0 the structural slab sits here.', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='floortiletype',
            name='is_zone',
            field=models.BooleanField(default=False, help_text='Zone tiles paint the grid background (hot/cold aisles, security areas) - they render under normal tiles and other tiles may sit on top of them.'),
        ),
        migrations.AlterField(
            model_name='floortiletype',
            name='perforated',
            field=models.BooleanField(default=False, help_text='Zone tiles of this type render as perforated/grate floor in the 3D room - the cold-aisle supply-tile read.'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='combo_group',
            field=models.CharField(blank=True, default='', help_text='Combo/shared port: interfaces on this device with the same group are alternate connectors for one logical port - enabling one disables the others.', max_length=64),
        ),
        migrations.AlterField(
            model_name='interface',
            name='is_uplink',
            field=models.BooleanField(default=False, help_text='This port faces other network infrastructure. It never gets switch-link suggestions - the MACs it learns belong to hosts behind it, not on it. The escape hatch when the automatic uplink detection misreads a topology.'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='snmp_ignore',
            field=models.BooleanField(default=False, help_text="Exclude this interface from SNMP drift. For ports the polled agent can never report - silkscreened ports a BMC doesn't see, out-of-band jacks - which would otherwise flag as 'not seen on device' after every poll, forever."),
        ),
        migrations.AlterField(
            model_name='interface',
            name='snmp_name',
            field=models.CharField(blank=True, default='', help_text="What the agent calls this interface over SNMP (ifName / ifDescr) when it differs from the label - e.g. the port silkscreened 'Ethernet 1' reporting as 'eth0'. Set it and discovery stops reporting the pair as both new and missing.", max_length=128),
        ),
        migrations.AlterField(
            model_name='interface',
            name='virtual',
            field=models.BooleanField(default=False, help_text='A logical interface with no physical port - sub-interface, LAG/aggregate, loopback, tunnel, VLAN interface.'),
        ),
        migrations.AlterField(
            model_name='interfacetemplate',
            name='combo_group',
            field=models.CharField(blank=True, default='', help_text='Combo/shared port group - materialised onto each device so its alternate connectors stay mutually exclusive.', max_length=64),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='media',
            field=models.CharField(blank=True, choices=[('', '-'), ('nvme', 'NVMe'), ('ssd', 'SSD (SATA/SAS)'), ('hdd', 'HDD'), ('tape', 'Tape')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='inventoryitemtemplate',
            name='media',
            field=models.CharField(blank=True, choices=[('', '-'), ('nvme', 'NVMe'), ('ssd', 'SSD (SATA/SAS)'), ('hdd', 'HDD'), ('tape', 'Tape')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='flap_exclude',
            field=models.BooleanField(default=False, help_text="Exclude this IP from the flapping monitor - for a known noisy host you don't want flagged."),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='mac_address',
            field=models.CharField(blank=True, help_text="Hardware address paired with this IP - e.g. a DHCP reservation. Independent of the interface's own MAC.", max_length=17),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='status',
            field=models.ForeignKey(help_text="Operational status - pick from your tenant's status catalog.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ips', to='api.status'),
        ),
        migrations.AlterField(
            model_name='l2vpn',
            name='identifier',
            field=models.BigIntegerField(blank=True, help_text='Overlay identifier - VNI / VC-ID.', null=True),
        ),
        migrations.AlterField(
            model_name='modulebaytemplate',
            name='default_module_type',
            field=models.ForeignKey(blank=True, help_text="Pre-install a module of this type when the bay is stamped onto a new device, and into an empty matching bay on sync-from-type. Fully replaceable afterwards - this only decides what's pre-seated.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_in_bay_templates', to='api.moduletype'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='end_of_support',
            field=models.DateField(blank=True, help_text='End of life - vendor support and maintenance ends.', null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='release_date',
            field=models.DateField(blank=True, help_text='GA / first-ship date - the start of the lifetime bar.', null=True),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='auto_discover',
            field=models.BooleanField(default=False, help_text='Opt in to periodic ICMP discovery - responders not yet recorded are auto-created as IPs (see monitoring settings).'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='max_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Load budget (see max_weight_unit) - what the rack/floor is rated to carry. Devices sum against it via their type's weight.", max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='default_prefix',
            field=models.ForeignKey(blank=True, help_text="The prefix new addresses at this site come from by default - so staff working at one site don't have to hunt for the right subnet. A hint, not a constraint: the picker still offers every prefix.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_sites', to='api.prefix'),
        ),
        migrations.AlterField(
            model_name='site',
            name='vrfs',
            field=models.ManyToManyField(blank=True, help_text='Which VRFs operate at this site. Documentation only - not enforced.', related_name='sites', to='api.vrf'),
        ),
        migrations.AlterField(
            model_name='status',
            name='is_closed',
            field=models.BooleanField(default=False, help_text="Marks the workflow as finished - a closed maintenance/outage event leaves the open list, the calendar's open count, and releases its silence."),
        ),
        migrations.AlterField(
            model_name='status',
            name='requires_note',
            field=models.BooleanField(default=False, help_text="Picking this status on an IP forces the operator to fill in the reservation_note field - used so e.g. 'Reserved' always carries the who/why on hover."),
        ),
        migrations.AlterField(
            model_name='tunnel',
            name='encapsulation',
            field=models.CharField(choices=[('ipsec-tunnel', 'IPSec - Tunnel'), ('ipsec-transport', 'IPSec - Transport'), ('gre', 'GRE'), ('ip-ip', 'IP-in-IP'), ('wireguard', 'WireGuard')], default='ipsec-tunnel', max_length=20),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional VLAN group - scopes VID uniqueness.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlans', to='api.vlangroup'),
        ),
    ]
