# Generated by Django 5.2.16 on 2026-08-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_repair_maskless_prefixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='location',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Lucide icon name (e.g. building, layers, door-closed).', max_length=48),
        ),
        migrations.AddField(
            model_name='site',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='site',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Lucide icon name (e.g. building-2, factory, warehouse).', max_length=48),
        ),
    ]
