# Generated by Django 5.2.16 on 2026-08-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_location_color_location_icon_site_color_site_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicerole',
            name='icon',
            field=models.CharField(blank=True, default='', help_text="Lucide icon name (e.g. server, router, cctv) - shown in the role's badge on maps and floor plans.", max_length=48),
        ),
    ]
