# Generated by Django 5.2.16 on 2026-08-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_devicerole_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontport',
            name='mark_connected',
            field=models.BooleanField(default=False, help_text="There is a cable in this port, it just isn't documented yet. Counts as connected in port utilization; cleared automatically when a real cable is attached."),
        ),
        migrations.AddField(
            model_name='interface',
            name='mark_connected',
            field=models.BooleanField(default=False, help_text="There is a cable in this port, it just isn't documented yet. Counts as connected in port utilization; cleared automatically when a real cable is attached."),
        ),
        migrations.AddField(
            model_name='rearport',
            name='mark_connected',
            field=models.BooleanField(default=False, help_text="There is a cable in this port, it just isn't documented yet. Counts as connected in port utilization; cleared automatically when a real cable is attached."),
        ),
    ]
