# Generated by Django 5.2.16 on 2026-08-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_frontport_mark_connected_interface_mark_connected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vminterface',
            name='sync_ignore_ips',
            field=models.BooleanField(default=False),
        ),
    ]
