# Generated by Django 5.2.16 on 2026-08-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_vminterface_sync_ignore_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageattachment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='image-attachments/thumbs/'),
        ),
    ]
