# Generated by Django 5.2.16 on 2026-08-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_imageattachment_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='boundary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='boundary_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='region',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
