# Generated by Django 5.2.16 on 2026-08-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_region_boundary_region_boundary_label_region_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetypeservice',
            name='protocol_ports',
            field=models.JSONField(blank=True, default=dict, help_text='Ports per protocol, e.g. {"tcp": [53, 443], "udp": [53]}. Empty means the single protocol/ports pair applies.'),
        ),
        migrations.AddField(
            model_name='service',
            name='protocol_ports',
            field=models.JSONField(blank=True, default=dict, help_text='Ports per protocol, e.g. {"tcp": [53, 443], "udp": [53]}. Empty means the single protocol/ports pair applies.'),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='protocol_ports',
            field=models.JSONField(blank=True, default=dict, help_text='Ports per protocol, e.g. {"tcp": [53, 443], "udp": [53]}. Empty means the single protocol/ports pair applies.'),
        ),
    ]
