# Generated by Django 5.2.16 on 2026-08-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_service_protocol_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageattachment',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageattachment',
            name='size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageattachment',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
