# Generated by Django 5.2.16 on 2026-08-22 20:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_image_dimensions'),
        ('core', '0044_login_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortReservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('aux_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.auxport')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='port_reservations', to=settings.AUTH_USER_MODEL)),
                ('console_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.consoleport')),
                ('console_server_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.consoleserverport')),
                ('front_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.frontport')),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.interface')),
                ('power_feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.powerfeed')),
                ('power_outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.poweroutlet')),
                ('power_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.powerport')),
                ('rear_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.rearport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_reservations', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('aux_port__isnull', True), ('console_port__isnull', True), ('console_server_port__isnull', True), ('front_port__isnull', True), ('interface__isnull', False), ('power_feed__isnull', True), ('power_outlet__isnull', True), ('power_port__isnull', True), ('rear_port__isnull', True)), models.Q(('aux_port__isnull', True), ('console_port__isnull', True), ('console_server_port__isnull', True), ('front_port__isnull', False), ('interface__isnull', True), ('power_feed__isnull', True), ('power_outlet__isnull', True), ('power_port__isnull', True), ('rear_port__isnull', True)), models.Q(('aux_port__isnull', True), ('console_port__isnull', True), ('console_server_port__isnull', True), ('front_port__isnull', True), ('interface__isnull', True), ('power_feed__isnull', True), ('power_outlet__isnull', True), ('power_port__isnull', True), ('rear_port__isnull', False)), models.Q(('aux_port__isnull', True), ('console_port__isnull', False), ('console_server_port__isnull', True), ('front_port__isnull', True), ('interface__isnull', True), ('power_feed__isnull', True), ('power_outlet__isnull', True), ('power_port__isnull', True), ('rear_port__isnull', True)), models.Q(('aux_port__isnull', True), ('console_port__isnull', True), ('console_server_port__isnull', False), ('front_port__isnull', True), ('interface__isnull', True), ('power_feed__isnull', True), ('power_outlet__isnull', True), ('power_port__isnull', True), ('rear_port__isnull', True)), models.Q(('aux_port__isnull', True), ('console_port__isnull', True), ('console_server_port__isnull', True), ('front_port__isnull', True), ('interface__isnull', True), ('power_feed__isnull', True), ('power_outlet__isnull', True), ('power_port__isnull', False), ('rear_port__isnull', True)), models.Q(('aux_port__isnull', True), ('console_port__isnull', True), ('console_server_port__isnull', True), ('front_port__isnull', True), ('interface__isnull', True), ('power_feed__isnull', True), ('power_outlet__isnull', False), ('power_port__isnull', True), ('rear_port__isnull', True)), models.Q(('aux_port__isnull', True), ('console_port__isnull', True), ('console_server_port__isnull', True), ('front_port__isnull', True), ('interface__isnull', True), ('power_feed__isnull', False), ('power_outlet__isnull', True), ('power_port__isnull', True), ('rear_port__isnull', True)), models.Q(('aux_port__isnull', False), ('console_port__isnull', True), ('console_server_port__isnull', True), ('front_port__isnull', True), ('interface__isnull', True), ('power_feed__isnull', True), ('power_outlet__isnull', True), ('power_port__isnull', True), ('rear_port__isnull', True)), _connector='OR'), name='portreservation_exactly_one_point'), models.UniqueConstraint(condition=models.Q(('interface__isnull', False)), fields=('interface',), name='uniq_reservation_interface'), models.UniqueConstraint(condition=models.Q(('front_port__isnull', False)), fields=('front_port',), name='uniq_reservation_front_port'), models.UniqueConstraint(condition=models.Q(('rear_port__isnull', False)), fields=('rear_port',), name='uniq_reservation_rear_port'), models.UniqueConstraint(condition=models.Q(('console_port__isnull', False)), fields=('console_port',), name='uniq_reservation_console_port'), models.UniqueConstraint(condition=models.Q(('console_server_port__isnull', False)), fields=('console_server_port',), name='uniq_reservation_console_server_port'), models.UniqueConstraint(condition=models.Q(('power_port__isnull', False)), fields=('power_port',), name='uniq_reservation_power_port'), models.UniqueConstraint(condition=models.Q(('power_outlet__isnull', False)), fields=('power_outlet',), name='uniq_reservation_power_outlet'), models.UniqueConstraint(condition=models.Q(('power_feed__isnull', False)), fields=('power_feed',), name='uniq_reservation_power_feed'), models.UniqueConstraint(condition=models.Q(('aux_port__isnull', False)), fields=('aux_port',), name='uniq_reservation_aux_port')],
            },
        ),
    ]
