# Generated by Django 5.2.16 on 2026-08-23 19:05

import django.db.models.deletion
from django.db import migrations, models


def backfill_site(apps, schema_editor):
    """Existing holds predate the column - resolve each one's site from the
    port it holds, so site-scoped grants see the right rows immediately."""
    Reservation = apps.get_model("api", "PortReservation")
    POINTS = [
        ("interface", "device"), ("front_port", "device"),
        ("rear_port", "device"), ("console_port", "device"),
        ("console_server_port", "device"), ("power_port", "device"),
        ("power_outlet", "device"), ("aux_port", "device"),
        ("power_feed", "power_panel"),
    ]
    for row in Reservation.objects.all().iterator():
        for field, parent in POINTS:
            port = getattr(row, field, None)
            if port is None:
                continue
            owner = getattr(port, parent, None)
            row.site_id = getattr(owner, "site_id", None)
            row.save(update_fields=["site"])
            break


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_planned_status_amber'),
    ]

    operations = [
        migrations.AddField(
            model_name='portreservation',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='port_reservations', to='api.site'),
        ),
        migrations.RunPython(backfill_site, migrations.RunPython.noop),
    ]
