# Generated by Django 5.2.16 on 2026-08-24 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_backfill_blank_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interfaces', to='api.status'),
        ),
        migrations.AddField(
            model_name='status',
            name='excludes_capacity',
            field=models.BooleanField(default=False, help_text="Ports carrying this status don't count as capacity in port utilization - the hardware isn't there (interface 'Not present' / 'Decommissioning')."),
        ),
    ]
