# Generated by Django 5.2.16 on 2026-08-27 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0141_cable_to_circuit_termination'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Weekly working hours, keyed 0 (Mon) to 6 (Sun).'),
        ),
        migrations.AddField(
            model_name='contact',
            name='business_hours_tz',
            field=models.CharField(blank=True, default='', help_text='IANA zone the working hours are stated in.', max_length=63),
        ),
        migrations.AddField(
            model_name='provider',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_manager_for', to='api.contact'),
        ),
        migrations.AddField(
            model_name='provider',
            name='account_manager_name',
            field=models.CharField(blank=True, default='', help_text='Used when the account manager has no Contact record.', max_length=128),
        ),
        migrations.AddField(
            model_name='provider',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Weekly support hours, keyed 0 (Mon) to 6 (Sun).'),
        ),
        migrations.AddField(
            model_name='provider',
            name='business_hours_tz',
            field=models.CharField(blank=True, default='', help_text='IANA zone the support hours are stated in.', max_length=63),
        ),
        migrations.AddField(
            model_name='provider',
            name='support_contract',
            field=models.CharField(blank=True, default='', help_text='Contract/reference quoted when opening a support case.', max_length=128),
        ),
        migrations.AddField(
            model_name='provider',
            name='support_phone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
