# Generated by Django 5.2.16 on 2026-08-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0143_wireless_lan_psk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetypeimportrun',
            name='kind',
            field=models.CharField(choices=[('library', 'Library import'), ('image_reimport', 'Image reimport'), ('component_sync', 'Component sync')], default='library', max_length=16),
        ),
        migrations.AlterField(
            model_name='devicetypeimportrun',
            name='source_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
