# Generated by Django 5.2.16 on 2026-08-28 20:56

import api.models
import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_devicetype_run_component_sync'),
        ('core', '0045_hide_local_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxport',
            name='type',
            field=models.CharField(blank=True, choices=[('USB', [('usb-a', 'USB Type A'), ('usb-b', 'USB Type B'), ('usb-c', 'USB Type C'), ('usb-mini-b', 'USB Mini B'), ('usb-micro-b', 'USB Micro B')]), ('Video', [('hdmi', 'HDMI'), ('mini-hdmi', 'Mini HDMI'), ('vga', 'VGA (DE-15)'), ('dvi', 'DVI'), ('displayport', 'DisplayPort'), ('mini-displayport', 'Mini DisplayPort')]), ('Storage', [('sd', 'SD card'), ('microsd', 'microSD card')]), ('RF / antenna', [('rp-sma', 'RP-SMA'), ('sma', 'SMA'), ('n-type', 'N-type'), ('mmcx', 'MMCX'), ('u.fl', 'U.FL'), ('qma', 'QMA'), ('4.3-10', '4.3-10')]), ('Other', [('rj11', 'RJ11'), ('audio-3.5mm', 'Audio 3.5 mm'), ('grounding', 'Grounding lug'), ('other', 'Other')])], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='auxporttemplate',
            name='type',
            field=models.CharField(blank=True, choices=[('USB', [('usb-a', 'USB Type A'), ('usb-b', 'USB Type B'), ('usb-c', 'USB Type C'), ('usb-mini-b', 'USB Mini B'), ('usb-micro-b', 'USB Micro B')]), ('Video', [('hdmi', 'HDMI'), ('mini-hdmi', 'Mini HDMI'), ('vga', 'VGA (DE-15)'), ('dvi', 'DVI'), ('displayport', 'DisplayPort'), ('mini-displayport', 'Mini DisplayPort')]), ('Storage', [('sd', 'SD card'), ('microsd', 'microSD card')]), ('RF / antenna', [('rp-sma', 'RP-SMA'), ('sma', 'SMA'), ('n-type', 'N-type'), ('mmcx', 'MMCX'), ('u.fl', 'U.FL'), ('qma', 'QMA'), ('4.3-10', '4.3-10')]), ('Other', [('rj11', 'RJ11'), ('audio-3.5mm', 'Audio 3.5 mm'), ('grounding', 'Grounding lug'), ('other', 'Other')])], default='', max_length=32),
        ),
        migrations.CreateModel(
            name='Antenna',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('antenna_type', models.CharField(blank=True, choices=[('internal', 'Internal'), ('omni', 'Omnidirectional'), ('directional', 'Directional'), ('sector', 'Sector'), ('patch', 'Patch'), ('yagi', 'Yagi'), ('parabolic', 'Parabolic dish')], default='', max_length=16)),
                ('gain_dbi', models.DecimalField(blank=True, decimal_places=2, help_text='Peak gain in dBi.', max_digits=5, null=True)),
                ('bands', models.JSONField(blank=True, default=list, help_text='Band slugs, e.g. ["2.4ghz", "5ghz"].', validators=[api.models.validate_antenna_bands])),
                ('polarization', models.CharField(blank=True, choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('dual', 'Dual'), ('dual-slant', 'Dual slant ±45°'), ('circular', 'Circular')], default='', max_length=16)),
                ('connector', models.CharField(blank=True, choices=[('rp-sma', 'RP-SMA'), ('sma', 'SMA'), ('n-type', 'N-type'), ('mmcx', 'MMCX'), ('u.fl', 'U.FL'), ('qma', 'QMA'), ('4.3-10', '4.3-10')], default='', help_text='RF connector, for external elements. Blank for internal.', max_length=16)),
                ('direct_mount', models.BooleanField(default=False, help_text='Mounted directly on the device connector, no cable.')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antennas', to='api.device')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('device', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AntennaTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('antenna_type', models.CharField(blank=True, choices=[('internal', 'Internal'), ('omni', 'Omnidirectional'), ('directional', 'Directional'), ('sector', 'Sector'), ('patch', 'Patch'), ('yagi', 'Yagi'), ('parabolic', 'Parabolic dish')], default='', max_length=16)),
                ('gain_dbi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bands', models.JSONField(blank=True, default=list, validators=[api.models.validate_antenna_bands])),
                ('polarization', models.CharField(blank=True, choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal'), ('dual', 'Dual'), ('dual-slant', 'Dual slant ±45°'), ('circular', 'Circular')], default='', max_length=16)),
                ('connector', models.CharField(blank=True, choices=[('rp-sma', 'RP-SMA'), ('sma', 'SMA'), ('n-type', 'N-type'), ('mmcx', 'MMCX'), ('u.fl', 'U.FL'), ('qma', 'QMA'), ('4.3-10', '4.3-10')], default='', max_length=16)),
                ('direct_mount', models.BooleanField(default=False)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antenna_templates', to='api.devicetype')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('device_type', 'name')},
            },
        ),
    ]
