# Generated by Django 5.2.16 on 2026-09-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0145_antennas'),
    ]

    operations = [
        migrations.AddField(
            model_name='vminterface',
            name='kind',
            field=models.CharField(blank=True, choices=[('', 'Virtual'), ('bridge', 'Bridge'), ('loopback', 'Loopback'), ('tunnel', 'Tunnel')], default='', max_length=16),
        ),
    ]
