# Generated by Django 5.2.16 on 2026-09-01 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0146_vminterface_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='vminterface',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.vminterface'),
        ),
    ]
