# Generated by Django 5.2.16 on 2026-09-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_vminterface_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontport',
            name='label',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='interface',
            name='label',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='rearport',
            name='label',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
