# Generated by Django 5.2.16 on 2026-09-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0148_frontport_label_interface_label_rearport_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='image_ports',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
