# Generated by Django 5.2.16 on 2026-09-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0149_device_image_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontport',
            name='marker_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='interface',
            name='marker_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='rearport',
            name='marker_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
