# Generated by Django 5.2.16 on 2026-09-01 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_backfill_marker_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='bridge',
            field=models.ForeignKey(blank=True, help_text='The bridge interface this one belongs to. Same device or virtual chassis.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bridge_members', to='api.interface'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='lag',
            field=models.ForeignKey(blank=True, help_text='The link-aggregation (LAG/aggregate) interface this one is a member of, e.g. a physical port → ae1. Same device or virtual chassis.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lag_members', to='api.interface'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The interface this one nests under (e.g. a sub-interface ae1.100 → ae1). Same device or virtual chassis.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.interface'),
        ),
    ]
