# Generated by Django 5.2.16 on 2026-09-01 19:34

from django.db import migrations, models


def promote_untyped_aggregates(apps, schema_editor):
    """An interface that already has LAG members is an aggregate. Where its
    type was left blank or "virtual", stamp it "lag" so it passes the new
    membership rule; a physical media type is left alone (an operator choice
    the rule reports on the next edit instead)."""
    Interface = apps.get_model("api", "Interface")
    Interface.objects.filter(
        lag_members__isnull=False, type__in=["", "virtual"]
    ).distinct().update(type="lag", virtual=True)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0152_interface_relations_span_virtual_chassis'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='lacp_mode',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('passive', 'Passive')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='interface',
            name='lacp_rate',
            field=models.CharField(blank=True, choices=[('slow', 'Slow (30 s)'), ('fast', 'Fast (1 s)')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='interface',
            name='lag_min_links',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Members that must be up for the bundle to count as up.', null=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='lag_protocol',
            field=models.CharField(blank=True, choices=[('lacp', 'LACP (802.3ad)'), ('pagp', 'PAgP')], default='', help_text='Bundling protocol. Blank = static aggregate (no negotiation).', max_length=8),
        ),
        migrations.RunPython(promote_untyped_aggregates, migrations.RunPython.noop),
    ]
