# Generated by Django 5.2.16 on 2026-09-08 08:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0157_search_extensions'),
        ('core', '0048_deploymentsettings_secrets_provider_registry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='macaddress',
            name='vendor_override',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='OuiImport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('upload', 'Uploaded CSV'), ('url', 'Fetched from URL')], default='upload', max_length=8)),
                ('source_url', models.CharField(blank=True, default='', max_length=512)),
                ('file', models.FileField(blank=True, upload_to='oui-imports/')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OuiPrefix',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefix', models.CharField(db_index=True, max_length=11)),
                ('bits', models.PositiveSmallIntegerField()),
                ('vendor', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('ieee', 'IEEE registry'), ('custom', 'Custom range')], default='custom', max_length=8)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oui_prefixes', to='core.tenant')),
            ],
            options={
                'ordering': ['prefix'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'prefix'), name='uniq_ouiprefix_tenant_prefix', nulls_distinct=False)],
            },
        ),
    ]
