# Generated by Django 5.2.16 on 2026-09-08 10:45

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


def _pin_fold_search_path(apps, schema_editor):
    """CREATE INDEX evaluates its expression under a locked-down search_path,
    so ``danbyte_fold`` must name the schema its ``unaccent`` dictionary lives
    in. Redefine it with that schema pinned (looked up, not assumed)."""
    with schema_editor.connection.cursor() as cur:
        cur.execute(
            "SELECT n.nspname FROM pg_extension e JOIN pg_namespace n "
            "ON e.extnamespace = n.oid WHERE e.extname = 'unaccent'"
        )
        row = cur.fetchone()
        schema = row[0] if row else "public"
        cur.execute(
            "CREATE OR REPLACE FUNCTION danbyte_fold(text) RETURNS text "
            "LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT "
            f'SET search_path = "{schema}", pg_catalog '
            # Danish/Norwegian "aa" is "å", which unaccent folds to "a": collapse
            # the digraph too so aarhus, arhus and Århus all meet.
            f"AS $$ SELECT replace(lower(\"{schema}\".unaccent('\"{schema}\".unaccent'::regdictionary, $1)), 'aa', 'a') $$;"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0158_oui_prefix_vendor'),
        ('core', '0048_deploymentsettings_secrets_provider_registry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=64)),
                ('object_id', models.UUIDField()),
                ('numid', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('facets', models.JSONField(blank=True, default=dict)),
                ('url', models.CharField(max_length=255)),
                ('weight', models.PositiveSmallIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.site')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_entries', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'object_type'], name='searchentry_tenant_type'), models.Index(fields=['tenant', 'numid'], name='searchentry_tenant_numid'), django.contrib.postgres.indexes.GinIndex(fields=['facets'], name='searchentry_facets_gin')],
                'constraints': [models.UniqueConstraint(fields=('object_type', 'object_id'), name='uniq_searchentry_object')],
            },
        ),
        migrations.RunPython(_pin_fold_search_path, migrations.RunPython.noop),
        migrations.RunSQL(
            'CREATE INDEX "searchentry_title_trgm" ON "api_searchentry" '
            'USING gin (danbyte_fold("title") gin_trgm_ops);',
            'DROP INDEX IF EXISTS "searchentry_title_trgm";',
        ),
        migrations.RunSQL(
            'CREATE INDEX "searchentry_body_trgm" ON "api_searchentry" '
            'USING gin (danbyte_fold("body") gin_trgm_ops);',
            'DROP INDEX IF EXISTS "searchentry_body_trgm";',
        ),
    ]
