# Generated by Django 5.2.16 on 2026-09-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0159_search_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchentry',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
