# Generated by Django 5.2.16 on 2026-09-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    """Split VLAN VID uniqueness into group-scoped and site-scoped (#159).

    The old single constraint made a VID unique per tenant whenever it had no
    group, so the same VLAN 105 could not exist at two sites - two separate
    broadcast domains that happen to share a number. Strictly a relaxation:
    everything the old constraint allowed, these two allow, so no existing
    row can fail it.
    """

    dependencies = [
        ('api', '0160_searchentry_context'),
        ('core', '0051_deploymentsettings_azure_authority_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vlan',
            name='uniq_vlan_tenant_group_vid',
        ),
        migrations.AddConstraint(
            model_name='vlan',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('tenant', 'group', 'vlan_id'), name='uniq_vlan_group_vid'),
        ),
        migrations.AddConstraint(
            model_name='vlan',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', True)), fields=('tenant', 'site', 'vlan_id'), name='uniq_vlan_site_vid', nulls_distinct=False),
        ),
    ]
