# Generated by Django 5.2.16 on 2026-09-10 14:10

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0161_remove_vlan_uniq_vlan_tenant_group_vid_and_more'),
        ('core', '0051_deploymentsettings_azure_authority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NATRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('dnat', 'Destination NAT (port forward)'), ('snat', 'Source NAT'), ('static', 'Static (1:1) NAT'), ('masquerade', 'Masquerade')], default='dnat', max_length=12)),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('tcp-udp', 'TCP/UDP'), ('icmp', 'ICMP'), ('any', 'Any')], default='tcp', max_length=8)),
                ('external_ports', models.CharField(blank=True, default='', max_length=32)),
                ('internal_ports', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nat_rules', to='api.device')),
                ('external_ip', models.ForeignKey(blank=True, help_text="The address reached from outside. Blank for masquerade, which uses whatever the firewall's egress address is.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nat_external', to='api.ipaddress')),
                ('internal_ip', models.ForeignKey(blank=True, help_text='The address traffic is translated to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nat_internal', to='api.ipaddress')),
                ('source_ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nat_source', to='api.ipaddress')),
                ('source_prefix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nat_rules', to='api.prefix')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nat_rules', to='api.status')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nat_rules', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
