# Generated by Django 5.2.16 on 2026-09-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0162_natrule'),
        ('core', '0051_deploymentsettings_azure_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='monitoring_state',
            field=models.CharField(blank=True, default='', help_text="The monitoring check state this status speaks for - blank means it is not a monitoring status. Set, and the status replaces that state's shipped name and colour wherever monitoring is shown, and becomes pickable where a check state is (a Zabbix severity map, say). A check still records one of the six states, so at most one status per tenant may claim each.", max_length=8),
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.UniqueConstraint(condition=models.Q(('monitoring_state', ''), _negated=True), fields=('tenant', 'monitoring_state'), name='uniq_status_tenant_monitoring_state'),
        ),
    ]
