# Generated by Django 5.2.16 on 2026-09-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_status_monitoring_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipsecprofile',
            name='psk_secret_path',
            field=models.CharField(blank=True, default='', help_text='Reference to the PSK inside that store. Empty: no PSK set.', max_length=255),
        ),
        migrations.AddField(
            model_name='ipsecprofile',
            name='psk_secret_provider',
            field=models.CharField(blank=True, default='', help_text='Which secret store holds the PSK, stamped at write-time.', max_length=8),
        ),
    ]
