# Generated by Django 5.2.16 on 2026-09-15 18:02

import django.db.models.deletion
from django.db import migrations, models


def seed_statuses(apps, schema_editor):
    """L2VPNs have carried a status since they existed, but the scope was
    never registered, so a fresh tenant's picker was empty. Seed it now,
    alongside the VTEP scope the overlay adds."""
    from api.status_registry import seed_builtin_statuses

    Tenant = apps.get_model("core", "Tenant")
    Status = apps.get_model("api", "Status")
    for tenant in Tenant.objects.all():
        seed_builtin_statuses(tenant, Status=Status)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_ipsecprofile_psk'),
        ('core', '0052_sitecertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='l2vpn',
            name='vrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l3vnis', to='api.vrf'),
        ),
        migrations.AlterField(
            model_name='fhrpgroup',
            name='protocol',
            field=models.CharField(choices=[('vrrp2', 'VRRPv2'), ('vrrp3', 'VRRPv3'), ('hsrp', 'HSRP'), ('glbp', 'GLBP'), ('carp', 'CARP'), ('anycast', 'EVPN anycast gateway')], max_length=8),
        ),
        migrations.AddConstraint(
            model_name='l2vpn',
            constraint=models.UniqueConstraint(condition=models.Q(('identifier__isnull', False), ('type__in', ['vxlan', 'vxlan-evpn'])), fields=('tenant', 'identifier'), name='uniq_l2vpn_vxlan_vni'),
        ),
        migrations.RunPython(seed_statuses, migrations.RunPython.noop),
    ]
