# Generated by Django 5.2.16 on 2026-09-18 19:11

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0168_vlan_vrf'),
        ('core', '0052_sitecertificate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['tenant', 'status'], name='ip_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['tenant', 'role'], name='ip_tenant_role_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['tenant', 'site'], name='ip_tenant_site_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(models.F('tenant'), django.db.models.functions.text.Upper('dns_name'), name='ip_tenant_dns_upper_idx'),
        ),
    ]
