# Generated by Django 5.2.16 on 2026-09-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_ipaddress_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='mask_length',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Prefix length the address is configured with on its interface when it differs from the containing prefix - a /31 link inside an aggregate. Empty = the prefix's length.", null=True),
        ),
    ]
