# Generated by Django 5.2.16 on 2026-09-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0170_ipaddress_mask_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='port_labels',
            field=models.CharField(blank=True, choices=[('', 'Inherit'), ('on', 'Shown'), ('off', 'Hidden')], default='', help_text='Port labels on faceplate renders: inherit the deployment setting, or force them shown or hidden on this device.', max_length=8),
        ),
        migrations.AddField(
            model_name='interface',
            name='hide_label',
            field=models.BooleanField(default=False, help_text="Leave this port's marker blank on faceplate renders even when port labels are on."),
        ),
        migrations.AddField(
            model_name='interface',
            name='label_color',
            field=models.CharField(blank=True, default='', help_text="Text colour of this port's label on faceplate renders (#rrggbb); blank uses the deployment's colour.", max_length=7),
        ),
    ]
