# Generated by Django 5.2.16 on 2026-09-20 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_port_label_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='vlan_id',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4094)]),
        ),
    ]
