# Generated by Django 5.2.16 on 2026-09-20 19:16

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0172_vlan_id_range'),
        ('core', '0053_faceplate_port_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachineGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('vapp', 'vApp'), ('pool', 'Resource pool'), ('folder', 'Folder'), ('other', 'Group')], default='other', max_length=8)),
                ('description', models.TextField(blank=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vm_groups', to='api.cluster')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vm_groups', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_machines', to='api.virtualmachinegroup'),
        ),
        migrations.AddConstraint(
            model_name='virtualmachinegroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'cluster', 'name'), name='uniq_vmgroup_tenant_cluster_name'),
        ),
    ]
