# Generated by Django 5.2.16 on 2026-09-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0173_vm_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='evpn_mh_uplink',
            field=models.BooleanField(default=False),
        ),
    ]
