# Generated by Django 5.2.16 on 2026-09-21 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0174_interface_evpn_mh_uplink'),
        ('core', '0053_faceplate_port_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttemplate',
            name='target_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='ConfigBundle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('roles', models.ManyToManyField(blank=True, related_name='config_bundles', to='api.devicerole')),
                ('templates', models.ManyToManyField(blank=True, related_name='bundles', to='api.exporttemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_bundles', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_configbundle_tenant_name')],
            },
        ),
    ]
