# Generated by Django 5.2.16 on 2026-09-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0175_config_bundles'),
    ]

    operations = [
        migrations.AddField(
            model_name='vminterface',
            name='snmp_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
