# Generated by Django 5.2.16 on 2026-09-23 16:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0176_vminterface_snmp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=api.models._document_path),
        ),
    ]
