# Generated by Django 5.2.16 on 2026-09-25 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0177_document_random_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vlans', to='api.status'),
        ),
    ]
