# Generated by Django 5.2.16 on 2026-09-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0179_seed_vlan_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='wirelesslan',
            name='pmf',
            field=models.CharField(blank=True, choices=[('disabled', 'Disabled'), ('optional', 'Optional'), ('required', 'Required')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='wirelesslan',
            name='auth_cipher',
            field=models.CharField(blank=True, choices=[('auto', 'Auto'), ('aes', 'AES-CCMP'), ('gcmp-256', 'GCMP-256'), ('tkip', 'TKIP (legacy)')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='wirelesslan',
            name='auth_type',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('owe', 'Enhanced Open (OWE)'), ('wep', 'WEP (legacy)'), ('wpa2-personal', 'WPA2-Personal'), ('wpa3-personal', 'WPA3-Personal (SAE)'), ('wpa2-wpa3-personal', 'WPA2/WPA3-Personal'), ('wpa2-enterprise', 'WPA2-Enterprise'), ('wpa3-enterprise', 'WPA3-Enterprise'), ('wpa2-wpa3-enterprise', 'WPA2/WPA3-Enterprise'), ('wpa-personal', 'WPA Personal (PSK)'), ('wpa-enterprise', 'WPA Enterprise')], default='', max_length=24),
        ),
    ]
