# Generated by Django 5.2.16 on 2026-09-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0180_wifi_security_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='topology_card',
            field=models.JSONField(blank=True, default=None, help_text='Topology card lines for this device. Null inherits; an empty list shows the name only.', null=True),
        ),
    ]
