# Generated by Django 5.2.16 on 2026-09-29 11:00
# Component, template, rack and location lists default to the natural_sort
# collation (0099), so DIMM 2 comes before DIMM 10 in every related list.
# State only: Meta.ordering changes no SQL.

import django.db.models.functions.comparison
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0181_device_topology_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antenna',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='antennatemplate',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='auxport',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='auxporttemplate',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='consoleport',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='consoleporttemplate',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='consoleserverport',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='consoleserverporttemplate',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='devicebay',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='devicebaytemplate',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='devicetypeservice',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='frontport',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='frontporttemplate',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='interface',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='interfacetemplate',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='inventoryitemtemplate',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': [django.db.models.functions.comparison.Collate('site__name', 'natural_sort'), django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': [django.db.models.functions.comparison.Collate('module_bay__name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='modulebay',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='modulebaytemplate',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='moduleinterfacetemplate',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='poweroutlet',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='poweroutlettemplate',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='powerport',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='powerporttemplate',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='rack',
            options={'ordering': [django.db.models.functions.comparison.Collate('site__name', 'natural_sort'), django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='rearport',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='rearporttemplate',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='virtualdisk',
            options={'ordering': [django.db.models.functions.comparison.Collate('key', 'natural_sort')]},
        ),
        migrations.AlterModelOptions(
            name='vminterface',
            options={'ordering': [django.db.models.functions.comparison.Collate('name', 'natural_sort')]},
        ),
    ]
