# Generated by Django 5.2.16 on 2026-09-29 16:46
# Per-address monitoring exclusion and availability reset. Constant-default
# columns: PostgreSQL adds them without rewriting the table. The two partial
# indexes cover only the (few) excluded and reset addresses.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0182_natural_component_ordering'),
        ('core', '0056_topology_card_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='availability_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='availability_reset_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='availability_reset_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='availability_since',
            field=models.DateTimeField(blank=True, help_text='Uptime, SLA and availability for this address count from here. Earlier history is kept but not counted.', null=True, verbose_name='availability counts from'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='monitoring_excluded',
            field=models.BooleanField(default=False, help_text='Every check on this address is parked: nothing runs, no alerts, and the time off is not counted as availability.', verbose_name='excluded from monitoring'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='monitoring_excluded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='monitoring_excluded_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='monitoring_excluded_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(condition=models.Q(('availability_since__isnull', False)), fields=['tenant', 'availability_since'], name='ip_counted_from_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(condition=models.Q(('monitoring_excluded', True)), fields=['tenant'], name='ip_mon_excluded_idx'),
        ),
    ]
