# Generated by Django 5.2.16 on 2026-09-30 12:05
# Database defaults for the NOT NULL columns 0183 added. A web worker,
# background job or timer still running the release before 0183 inserts
# addresses without naming these columns; without a default on the column
# that insert fails for as long as the old process lives. SET DEFAULT only
# changes the catalog, so this does not rewrite the table.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0183_ip_monitoring_exclude_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='availability_reset_by',
            field=models.CharField(blank=True, db_default='', default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='availability_reset_reason',
            field=models.CharField(blank=True, db_default='', default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='monitoring_excluded',
            field=models.BooleanField(db_default=False, default=False, help_text='Every check on this address is parked: nothing runs, no alerts, and the time off is not counted as availability.', verbose_name='excluded from monitoring'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='monitoring_excluded_by',
            field=models.CharField(blank=True, db_default='', default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='monitoring_excluded_reason',
            field=models.CharField(blank=True, db_default='', default='', max_length=200),
        ),
    ]
