# Generated by Django 5.2.16 on 2026-10-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0185_ipaddress_host_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='topology_photo_size',
            field=models.CharField(blank=True, choices=[('rack', 'Rack width'), ('own', 'Own size')], db_default='', default='', help_text="How wide the topology Diagram draws this device's photo. Blank inherits.", max_length=4),
        ),
        migrations.AddField(
            model_name='devicerole',
            name='topology_photo_size',
            field=models.CharField(blank=True, choices=[('rack', 'Rack width'), ('own', 'Own size')], db_default='', default='', help_text="How wide the topology Diagram draws the photos of this role's devices. Blank inherits.", max_length=4),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='topology_photo_size',
            field=models.CharField(blank=True, choices=[('rack', 'Rack width'), ('own', 'Own size')], db_default='', default='', help_text='How wide the topology Diagram draws photos of this type. Blank inherits.', max_length=4),
        ),
    ]
