# Generated by Django 5.2.16 on 2026-10-01 19:50

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.comparison
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0186_topology_photo_size'),
        ('core', '0057_tenantsettings_default_topology_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_roles', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CabinetType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('inner_width_mm', models.PositiveSmallIntegerField(help_text='Mounting plate width in millimetres.', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(5000)], verbose_name='plate width (mm)')),
                ('inner_height_mm', models.PositiveSmallIntegerField(help_text='Mounting plate height in millimetres.', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(5000)], verbose_name='plate height (mm)')),
                ('outer_width_mm', models.PositiveSmallIntegerField(blank=True, help_text='Enclosure outer width in millimetres.', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(5000)], verbose_name='outer width (mm)')),
                ('outer_height_mm', models.PositiveSmallIntegerField(blank=True, help_text='Enclosure outer height in millimetres.', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(5000)], verbose_name='outer height (mm)')),
                ('outer_depth_mm', models.PositiveSmallIntegerField(blank=True, help_text='Enclosure outer depth in millimetres.', null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(3000)], verbose_name='outer depth (mm)')),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_types', to='api.manufacturer')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_types', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('facility_id', models.CharField(blank=True, default='', help_text="The cabinet's ID in the facility (e.g. a panel label).", max_length=64)),
                ('inner_width_mm', models.PositiveSmallIntegerField(help_text='Mounting plate width in millimetres.', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(5000)], verbose_name='plate width (mm)')),
                ('inner_height_mm', models.PositiveSmallIntegerField(help_text='Mounting plate height in millimetres.', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(5000)], verbose_name='plate height (mm)')),
                ('outer_width_mm', models.PositiveSmallIntegerField(blank=True, help_text='Enclosure outer width in millimetres.', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(5000)], verbose_name='outer width (mm)')),
                ('outer_height_mm', models.PositiveSmallIntegerField(blank=True, help_text='Enclosure outer height in millimetres.', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(5000)], verbose_name='outer height (mm)')),
                ('outer_depth_mm', models.PositiveSmallIntegerField(blank=True, help_text='Enclosure outer depth in millimetres.', null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(3000)], verbose_name='outer depth (mm)')),
                ('description', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinets', to='api.location')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cabinets', to='api.site')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cabinets', to='api.status')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='core.tenant')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinets', to='api.cabinetrole')),
                ('cabinet_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinets', to='api.cabinettype')),
            ],
            options={
                'ordering': [django.db.models.functions.comparison.Collate('site__name', 'natural_sort'), django.db.models.functions.comparison.Collate('name', 'natural_sort')],
            },
        ),
        migrations.AddConstraint(
            model_name='cabinetrole',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_cabinetrole_tenant_slug'),
        ),
        migrations.AddConstraint(
            model_name='cabinettype',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_cabinettype_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='cabinet',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='uniq_cabinet_site_name'),
        ),
    ]
