# Generated by Django 5.2.16 on 2026-10-01 20:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0188_seed_cabinet_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinRail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=32)),
                ('profile', models.CharField(choices=[('ts35', 'TS 35'), ('ts15', 'TS 15'), ('g32', 'G 32')], default='ts35', max_length=8)),
                ('x_mm', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)], verbose_name='left end (mm)')),
                ('y_mm', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)], verbose_name='centreline (mm)')),
                ('length_mm', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(5000)], verbose_name='length (mm)')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rails', to='api.cabinet')),
            ],
            options={
                'ordering': ['y_mm', 'x_mm', 'label'],
                'constraints': [models.UniqueConstraint(fields=('cabinet', 'label'), name='uniq_dinrail_cabinet_label')],
            },
        ),
        migrations.CreateModel(
            name='DinRailTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=32)),
                ('profile', models.CharField(choices=[('ts35', 'TS 35'), ('ts15', 'TS 15'), ('g32', 'G 32')], default='ts35', max_length=8)),
                ('x_mm', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)], verbose_name='left end (mm)')),
                ('y_mm', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)], verbose_name='centreline (mm)')),
                ('length_mm', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(5000)], verbose_name='length (mm)')),
                ('cabinet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rail_templates', to='api.cabinettype')),
            ],
            options={
                'ordering': ['y_mm', 'x_mm', 'label'],
                'constraints': [models.UniqueConstraint(fields=('cabinet_type', 'label'), name='uniq_dinrailtemplate_type_label')],
            },
        ),
    ]
