# Generated by Django 5.2.16 on 2026-10-01 22:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0189_din_rails'),
        ('core', '0057_tenantsettings_default_topology_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='api.cabinet'),
        ),
        migrations.AddField(
            model_name='device',
            name='din_offset_mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)], verbose_name='offset on the rail (mm)'),
        ),
        migrations.AddField(
            model_name='device',
            name='din_rail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='api.dinrail'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='depth_mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)], verbose_name='depth (mm)'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='din_profiles',
            field=models.JSONField(blank=True, db_default=models.Value([], models.JSONField()), default=list, help_text='The rail profiles the type mounts on (ts35, ts15, g32); empty = not DIN-rail mounted.', verbose_name='DIN rail profiles'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='din_rail_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="The rail's centreline below the body's top edge; empty = the middle.", max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)], verbose_name='rail position (mm)'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='height_mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)], verbose_name='height (mm)'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='width_mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)], verbose_name='width (mm)'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(('rack__isnull', True), ('cabinet__isnull', True), _connector='OR'), name='device_rack_or_cabinet'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('din_offset_mm__isnull', True), ('din_rail__isnull', True)), models.Q(('cabinet__isnull', False), ('din_offset_mm__isnull', False), ('din_rail__isnull', False)), _connector='OR'), name='device_din_rail_offset'),
        ),
    ]
