# Generated by Django 5.2.16 on 2026-10-02 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0190_din_mounting'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='floorplantile',
            name='floorplantile_at_most_one_link',
        ),
        migrations.AddField(
            model_name='floorplantile',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_tiles', to='api.cabinet'),
        ),
        migrations.AddConstraint(
            model_name='floorplantile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('device__isnull', True), ('linked_floor_plan__isnull', True), ('power_feed__isnull', True), ('power_panel__isnull', True), ('rack__isnull', True)), models.Q(('cabinet__isnull', True), ('device__isnull', True), ('linked_floor_plan__isnull', True), ('power_feed__isnull', True), ('power_panel__isnull', True), ('rack__isnull', False)), models.Q(('cabinet__isnull', False), ('device__isnull', True), ('linked_floor_plan__isnull', True), ('power_feed__isnull', True), ('power_panel__isnull', True), ('rack__isnull', True)), models.Q(('cabinet__isnull', True), ('device__isnull', False), ('linked_floor_plan__isnull', True), ('power_feed__isnull', True), ('power_panel__isnull', True), ('rack__isnull', True)), models.Q(('cabinet__isnull', True), ('device__isnull', True), ('linked_floor_plan__isnull', True), ('power_feed__isnull', True), ('power_panel__isnull', False), ('rack__isnull', True)), models.Q(('cabinet__isnull', True), ('device__isnull', True), ('linked_floor_plan__isnull', True), ('power_feed__isnull', False), ('power_panel__isnull', True), ('rack__isnull', True)), models.Q(('cabinet__isnull', True), ('device__isnull', True), ('linked_floor_plan__isnull', False), ('power_feed__isnull', True), ('power_panel__isnull', True), ('rack__isnull', True)), _connector='OR'), name='floorplantile_at_most_one_link'),
        ),
    ]
