# Generated by Django 5.2.16 on 2026-10-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0191_floor_tile_cabinet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnel',
            name='capacity_kbps',
            field=models.PositiveBigIntegerField(blank=True, help_text="How fast the tunnel's path is; empty = unknown.", null=True, verbose_name='capacity (kbps)'),
        ),
    ]
