# Generated by Django 5.2.16 on 2026-10-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0193_interface_virtual_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='never_uplink',
            field=models.BooleanField(db_default=False, default=False, help_text='Never treat this port as an uplink, whatever the automatic detection says - a server bond, or a phone that announces itself as a bridge. Its learned MACs are located here.'),
        ),
    ]
