# Generated by Django 5.2.16 on 2026-10-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0195_searchentry_folded_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='port_labels',
            field=models.CharField(blank=True, choices=[('', 'Inherit'), ('on', 'Shown'), ('off', 'Hidden')], db_default='', default='', help_text='Port labels on faceplate renders: inherit the deployment setting, or force them shown or hidden on this device.', max_length=8),
        ),
        migrations.AlterField(
            model_name='exporttemplate',
            name='target_path',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='fhrpgroup',
            name='nd_ra',
            field=models.BooleanField(db_default=False, default=False, help_text='Send IPv6 router advertisements from the gateway SVI.'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='evpn_mh_uplink',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='interface',
            name='hide_label',
            field=models.BooleanField(db_default=False, default=False, help_text="Leave this port's marker blank on faceplate renders even when port labels are on."),
        ),
        migrations.AlterField(
            model_name='interface',
            name='label_color',
            field=models.CharField(blank=True, db_default='', default='', help_text="Text colour of this port's label on faceplate renders (#rrggbb); blank uses the deployment's colour.", max_length=7),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='slot',
            field=models.CharField(blank=True, db_default='', default='', help_text='Where it sits: "Socket 1", "DIMM A1", "Bay 3".', max_length=32),
        ),
        migrations.AlterField(
            model_name='vminterface',
            name='snmp_name',
            field=models.CharField(blank=True, db_default='', default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='wirelesslan',
            name='pmf',
            field=models.CharField(blank=True, choices=[('disabled', 'Disabled'), ('optional', 'Optional'), ('required', 'Required')], db_default='', default='', max_length=8),
        ),
    ]
