# Generated by Django 5.2.16 on 2026-10-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0198_interface_module'),
        ('core', '0058_deploymentsettings_port_count_virtual'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['tenant', 'ip_address'], name='ip_tenant_addr_idx'),
        ),
    ]
