# Generated by Django 5.2.16 on 2026-10-10 06:56

import api.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0199_ip_tenant_addr_idx'),
        ('core', '0059_upgrade_db_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlanDrawing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.FileField(max_length=255, upload_to=api.models._cad_upload_to)),
                ('source_name', models.CharField(blank=True, default='', max_length=255)),
                ('source_kind', models.CharField(choices=[('dxf', 'DXF'), ('dwg', 'DWG')], max_length=8)),
                ('source_bytes', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('units', models.CharField(blank=True, default='', max_length=16)),
                ('units_mm_per_unit', models.FloatField(blank=True, null=True)),
                ('calibration', models.JSONField(blank=True, null=True)),
                ('extents', models.JSONField(blank=True, null=True)),
                ('layers', models.JSONField(blank=True, default=list)),
                ('rendered', models.FileField(blank=True, max_length=255, upload_to=api.models._cad_upload_to)),
                ('rendered_bytes', models.PositiveIntegerField(default=0)),
                ('rendered_elements', models.PositiveIntegerField(default=0)),
                ('simplified', models.JSONField(blank=True, default=list)),
                ('skipped', models.JSONField(blank=True, default=dict)),
                ('placement', models.JSONField(blank=True, default=dict)),
                ('variants', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('floor_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drawing', to='api.floorplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan_drawings', to='core.tenant')),
            ],
            options={
                'ordering': ['floor_plan'],
            },
        ),
    ]
