# Generated by Django 5.2.16 on 2026-10-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0200_floor_plan_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='max_power_w',
            field=models.PositiveIntegerField(blank=True, help_text='Power budget in watts. When set, demand is measured against it instead of the feeds.', null=True),
        ),
    ]
