# Generated by Django 5.2.16 on 2026-10-10 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0201_rack_max_power_w'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerpanel',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Where in the site the panel is (building / floor / room).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_panels', to='api.location'),
        ),
    ]
