# Generated by Django 5.2.16 on 2026-08-05 15:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0037_deploymentsettings_cert_digest_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_boards', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskLabel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('weight', models.PositiveIntegerField(default=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_labels', to='core.tenant')),
            ],
            options={
                'ordering': ['weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Markdown subset (headings, lists, code, links).')),
                ('priority', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='none', max_length=8)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(default=100, help_text='Ordering within the status column.')),
                ('assignees', models.ManyToManyField(blank=True, related_name='planning_tasks', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planning.board')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_planning_tasks', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_tasks', to='core.tenant')),
                ('labels', models.ManyToManyField(blank=True, related_name='tasks', to='planning.tasklabel')),
            ],
            options={
                'ordering': ['weight', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(help_text='Model label, e.g. api.device.', max_length=64)),
                ('object_id', models.UUIDField()),
                ('object_site_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='planning.task')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_task_links', to='core.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('semantic_group', models.CharField(choices=[('backlog', 'Backlog'), ('unstarted', 'Unstarted'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unstarted', max_length=12)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('weight', models.PositiveIntegerField(default=100, help_text='Lower weights order columns left to right.')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='planning.board')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_statuses', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'task statuses',
                'ordering': ['weight', 'name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='planning.taskstatus'),
        ),
        migrations.AddConstraint(
            model_name='board',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_board_slug_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='tasklabel',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_label_name_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='tasklink',
            index=models.Index(fields=['object_type', 'object_id'], name='planning_ta_object__4d0d21_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasklink',
            constraint=models.UniqueConstraint(fields=('task', 'object_type', 'object_id'), name='uniq_link_per_task_object'),
        ),
        migrations.AddConstraint(
            model_name='taskstatus',
            constraint=models.UniqueConstraint(fields=('board', 'name'), name='uniq_status_name_per_board'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['board', 'status', 'weight'], name='planning_ta_board_i_2a526e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'due_date'], name='planning_ta_tenant__f23871_idx'),
        ),
    ]
