# Generated by Django 5.2.16 on 2026-08-05 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_deploymentsettings_cert_digest_enabled_and_more'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('weight', models.PositiveIntegerField(default=100)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='planning.board')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_milestones', to='core.tenant')),
            ],
            options={
                'ordering': ['weight', 'due_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='planning.milestone'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.UniqueConstraint(fields=('board', 'name'), name='uniq_milestone_name_per_board'),
        ),
    ]
