# Generated by Django 5.2.16 on 2026-08-09 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_deploymentsettings_cert_digest_enabled_and_more'),
        ('planning', '0002_milestone_task_milestone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedChange',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(help_text='Model label, e.g. api.interface.', max_length=64)),
                ('object_id', models.UUIDField()),
                ('object_site_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('field', models.CharField(help_text='Payload key from /api/editable-fields/, e.g. enabled, status_id.', max_length=64)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('new_display', models.CharField(blank=True, default='', max_length=255)),
                ('current_value', models.JSONField(blank=True, null=True)),
                ('current_display', models.CharField(blank=True, default='', max_length=255)),
                ('planned_for', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('planned', 'Planned'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='planned', max_length=9)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_changes', to='planning.task')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_planned_changes', to='core.tenant')),
            ],
            options={
                'ordering': ['planned_for', 'created_at'],
                'indexes': [models.Index(condition=models.Q(('state', 'planned')), fields=['object_type', 'object_id'], name='idx_pchange_open_target'), models.Index(fields=['object_type', 'object_id'], name='idx_pchange_target'), models.Index(fields=['tenant', 'state'], name='idx_pchange_tenant_state'), models.Index(fields=['task', 'state'], name='idx_pchange_task_state')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'planned')), fields=('task', 'object_type', 'object_id', 'field'), name='uniq_open_planned_change_per_target_field')],
            },
        ),
    ]
