# Generated by Django 5.2.16 on 2026-08-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_plannedchange'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plannedchange',
            name='uniq_open_planned_change_per_target_field',
        ),
        migrations.RemoveField(
            model_name='plannedchange',
            name='current_display',
        ),
        migrations.RemoveField(
            model_name='plannedchange',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='plannedchange',
            name='field',
        ),
        migrations.RemoveField(
            model_name='plannedchange',
            name='new_display',
        ),
        migrations.RemoveField(
            model_name='plannedchange',
            name='new_value',
        ),
        migrations.AddField(
            model_name='plannedchange',
            name='before',
            field=models.JSONField(blank=True, default=dict, help_text="The live values of payload's keys when this was planned."),
        ),
        migrations.AddField(
            model_name='plannedchange',
            name='created_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plannedchange',
            name='display',
            field=models.JSONField(blank=True, default=list, help_text='[{field, label, from, to}] rendered at plan time.'),
        ),
        migrations.AddField(
            model_name='plannedchange',
            name='kind',
            field=models.CharField(choices=[('update', 'Edit an object'), ('create', 'Create an object')], default='update', max_length=6),
        ),
        migrations.AddField(
            model_name='plannedchange',
            name='payload',
            field=models.JSONField(default=dict, help_text='Write-shaped fields. For an edit, only what differs.'),
        ),
        migrations.AlterField(
            model_name='plannedchange',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
