# Generated by Django 5.2.16 on 2026-08-14 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('planning', '0004_remove_plannedchange_uniq_open_planned_change_per_target_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_tasks', to='auth.group'),
        ),
    ]
