# Generated by Django 5.2.16 on 2026-08-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_task_assigned_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Copy this column onto newly created boards (instead of the built-in four). Deduplicated by name across boards.'),
        ),
    ]
