# Generated by Django 5.2.16 on 2026-08-16 10:19

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_deploymentsettings_component_popover_fields'),
        ('planning', '0006_taskstatus_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
    ]
