# Generated by Django 5.2.16 on 2026-09-08 18:59

import django.db.models.deletion
import scripting.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0049_deploymentsettings_upgrade_notes_done'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, default='', max_length=140)),
                ('description', models.TextField(blank=True, default='')),
                ('language', models.CharField(choices=[('python', 'Python')], default='python', max_length=16)),
                ('source', models.TextField(blank=True, default='')),
                ('params_schema', models.JSONField(blank=True, default=list)),
                ('token_scope', models.CharField(choices=[('full', 'Read and write'), ('read', 'Read only')], default='full', max_length=8)),
                ('timeout_seconds', models.PositiveIntegerField(default=300)),
                ('trusted', models.BooleanField(default=False)),
                ('run_as', models.CharField(choices=[('caller', 'The person who runs it'), ('owner', "The script's owner")], default='caller', max_length=8)),
                ('visibility', models.CharField(choices=[('owner', 'Only me'), ('users', 'Chosen users'), ('groups', 'Chosen groups'), ('global', 'Everyone in the tenant')], default='owner', max_length=8)),
                ('schedule_enabled', models.BooleanField(default=False)),
                ('cadence', models.JSONField(blank=True, default=dict)),
                ('retention', models.JSONField(blank=True, default=dict)),
                ('schedule_params', models.JSONField(blank=True, default=dict)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_scripts', to=settings.AUTH_USER_MODEL)),
                ('shared_groups', models.ManyToManyField(blank=True, related_name='shared_scripts', to='auth.group')),
                ('shared_users', models.ManyToManyField(blank=True, related_name='shared_scripts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScriptRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timed out'), ('canceled', 'Canceled')], default='queued', max_length=10)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('log', models.TextField(blank=True, default='')),
                ('truncated', models.BooleanField(default=False)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('scheduled', models.BooleanField(default=False)),
                ('trusted', models.BooleanField(default=False)),
                ('source', models.TextField(blank=True, default='')),
                ('rq_job_id', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('run_as_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scripting.script')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScriptOutput',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=scripting.models.output_path)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.BigIntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='scripting.scriptrun')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='script',
            index=models.Index(fields=['tenant', 'visibility'], name='scripting_s_tenant__b3bde5_idx'),
        ),
        migrations.AddConstraint(
            model_name='script',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_script_tenant_name'),
        ),
        migrations.AddIndex(
            model_name='scriptrun',
            index=models.Index(fields=['script', '-created_at'], name='scripting_s_script__c24847_idx'),
        ),
        migrations.AddIndex(
            model_name='scriptrun',
            index=models.Index(fields=['status', '-created_at'], name='scripting_s_status_08cd2c_idx'),
        ),
    ]
