#!/bin/sh
# One-time (sudo): wire the "Danbyte is updating" page into nginx, safely.
# Backs up the config, injects the include, runs `nginx -t`, and RESTORES the
# backup if the test fails — so it can't leave your site broken.
#
#   sudo sh deploy/setup-maintenance.sh [path-to-your-nginx-site-conf]
#
# If you don't pass a path it tries to auto-detect the server block that proxies
# to Danbyte. Re-running is a no-op once installed.
set -eu

DANBYTE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SNIPPET_DIR="/etc/nginx/snippets"
SNIPPET="$SNIPPET_DIR/danbyte-maintenance.conf"

[ "$(id -u)" -eq 0 ] || { echo "run with sudo: sudo sh $0 $*" >&2; exit 1; }

CONF="${1:-}"
if [ -z "$CONF" ]; then
  # -R follows the sites-enabled symlinks; search sites-available too.
  CONF=$(grep -RlE "proxy_pass" /etc/nginx/sites-available /etc/nginx/sites-enabled \
    /etc/nginx/conf.d /etc/nginx/nginx.conf 2>/dev/null | head -1)
fi
[ -n "$CONF" ] && [ -f "$CONF" ] || {
  echo "Couldn't find your nginx site conf — pass it: sudo sh $0 /etc/nginx/sites-enabled/danbyte" >&2
  exit 1
}
echo "nginx conf: $CONF"

# 1. The snippet (with the correct absolute path to the page).
mkdir -p "$SNIPPET_DIR"
cat > "$SNIPPET" <<EOF
# Auto-generated by Danbyte setup-maintenance.sh
error_page 502 503 504 @danbyte_maintenance;
location @danbyte_maintenance {
    root $DANBYTE_DIR/deploy;
    rewrite ^ /maintenance.html break;
    internal;
    add_header Retry-After 30 always;
}
EOF

# 2. Inject an include into the server block (idempotent).
if grep -q "danbyte-maintenance.conf" "$CONF"; then
  echo "include already present — snippet refreshed."
else
  BK="$CONF.danbyte-bak-$(date +%s)"
  cp "$CONF" "$BK"
  echo "backup: $BK"
  python3 - "$CONF" "$SNIPPET" <<'PY'
import sys
conf, snippet = sys.argv[1], sys.argv[2]
lines = open(conf).read().splitlines(keepends=True)
inc = f"    include {snippet};\n"
# Insert before the last lone closing brace (the server block's close).
idx = max((i for i, l in enumerate(lines) if l.strip() == "}"), default=None)
if idx is None:
    sys.exit("no closing brace found")
lines.insert(idx, inc)
open(conf, "w").write("".join(lines))
PY
  if nginx -t 2>&1; then
    echo "nginx -t OK"
  else
    echo "nginx -t FAILED — restoring $BK"; cp "$BK" "$CONF"; exit 1
  fi
fi

nginx -t && systemctl reload nginx && \
  echo "Done — the updating page is live. It shows automatically whenever the
backend is down (e.g. during an in-app upgrade)."
