# Generated by Django 5.2.16 on 2026-10-10 10:37

import django.db.models.deletion
import monitoring.secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0201_rack_max_power_w'),
        ('core', '0060_tenantsettings_capacity_thresholds'),
    ]

    operations = [
        migrations.CreateModel(
            name='OxidizedConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('credentials', monitoring.secrets.EncryptedJSONField(blank=True, default=dict)),
                ('verify_tls', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('match_by', models.CharField(choices=[('address_name', 'Address, then name'), ('address', 'Address only'), ('name', 'Name only')], default='address_name', max_length=16)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('node_count', models.PositiveIntegerField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_summary', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oxidized_connections', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OxidizedNodeLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('node_name', models.CharField(max_length=255)),
                ('node_group', models.CharField(blank=True, default='', max_length=255)),
                ('node_ip', models.CharField(blank=True, default='', max_length=64)),
                ('node_model', models.CharField(blank=True, default='', max_length=64)),
                ('matched_by', models.CharField(choices=[('address', 'Address'), ('name', 'Name'), ('manual', 'Manual')], max_length=8)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='oxidized.oxidizedconnection')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oxidized_links', to='api.device')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oxidized_links', to='core.tenant')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='oxidizedconnection',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_oxidized_conn_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='oxidizednodelink',
            constraint=models.UniqueConstraint(fields=('connection', 'device'), name='uniq_oxidized_link_conn_device'),
        ),
        migrations.AddConstraint(
            model_name='oxidizednodelink',
            constraint=models.UniqueConstraint(fields=('connection', 'full_name'), name='uniq_oxidized_link_conn_node'),
        ),
    ]
