# Generated by Django 5.2.16 on 2026-09-15 15:41

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


def seed_statuses(apps, schema_editor):
    """Static routes carry a status: give every existing tenant the
    built-in vocabulary (active / planned / disabled). New tenants get it
    from bootstrap. Idempotent - merges by slug."""
    from api.status_registry import seed_builtin_statuses

    Tenant = apps.get_model("core", "Tenant")
    Status = apps.get_model("api", "Status")
    for tenant in Tenant.objects.all():
        seed_builtin_statuses(tenant, Status=Status)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0164_ipsecprofile_psk'),
        ('core', '0052_sitecertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASPathList',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_%(class)ss', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ASPathListRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('permit', 'Permit'), ('deny', 'Deny')], default='permit', max_length=6)),
                ('regex', models.CharField(help_text='e.g. "^65010_"', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('as_path_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='routing.aspathlist')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('value', models.CharField(help_text='e.g. "65000:100"', max_length=64)),
                ('kind', models.CharField(choices=[('standard', 'Standard'), ('large', 'Large'), ('extended', 'Extended')], default='standard', max_length=8)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_%(class)ss', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'communities',
                'ordering': ['value'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityList',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('standard', 'Standard'), ('expanded', 'Expanded (regex)'), ('large', 'Large'), ('extended', 'Extended')], default='standard', max_length=8)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_%(class)ss', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityListRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('permit', 'Permit'), ('deny', 'Deny')], default='permit', max_length=6)),
                ('regex', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('communities', models.ManyToManyField(blank=True, related_name='community_list_rules', to='routing.community')),
                ('community_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='routing.communitylist')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='PrefixList',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('family', models.CharField(choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6')], default='ipv4', max_length=4)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_%(class)ss', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrefixListRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('permit', 'Permit'), ('deny', 'Deny')], default='permit', max_length=6)),
                ('prefix', models.CharField(max_length=64)),
                ('ge', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('le', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('prefix_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='routing.prefixlist')),
                ('prefix_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefix_list_rules', to='api.prefix')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='RoutingKeychain',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('psk_secret_provider', models.CharField(blank=True, default='', help_text='Which secret store holds the PSK, stamped at write-time.', max_length=8)),
                ('psk_secret_path', models.CharField(blank=True, default='', help_text='Reference to the PSK inside that store. Empty: no PSK set.', max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('algorithm', models.CharField(choices=[('md5', 'MD5'), ('sha1', 'SHA-1'), ('sha256', 'SHA-256'), ('hmac-sha-256', 'HMAC-SHA-256')], default='md5', max_length=16)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_%(class)ss', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoutingPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_%(class)ss', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'routing policies',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoutingPolicyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('permit', 'Permit'), ('deny', 'Deny')], default='permit', max_length=6)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('match_extra', models.JSONField(blank=True, default=dict)),
                ('set_local_pref', models.PositiveIntegerField(blank=True, null=True)),
                ('set_med', models.PositiveIntegerField(blank=True, null=True)),
                ('set_weight', models.PositiveIntegerField(blank=True, null=True)),
                ('set_origin', models.CharField(blank=True, choices=[('igp', 'IGP'), ('egp', 'EGP'), ('incomplete', 'Incomplete')], default='', max_length=10)),
                ('set_next_hop', models.CharField(blank=True, default='', max_length=64)),
                ('set_as_path_prepend', models.CharField(blank=True, default='', help_text='e.g. "65001 65001"', max_length=255)),
                ('set_communities_additive', models.BooleanField(default=False)),
                ('set_metric_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Type 1'), (2, 'Type 2')], null=True)),
                ('set_extra', models.JSONField(blank=True, default=dict)),
                ('continue_seq', models.PositiveIntegerField(blank=True, null=True)),
                ('match_as_path_lists', models.ManyToManyField(blank=True, related_name='matched_by', to='routing.aspathlist')),
                ('match_community_lists', models.ManyToManyField(blank=True, related_name='matched_by', to='routing.communitylist')),
                ('match_next_hop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_as_next_hop_by', to='routing.prefixlist')),
                ('match_prefix_lists', models.ManyToManyField(blank=True, related_name='matched_by', to='routing.prefixlist')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='routing.routingpolicy')),
                ('set_communities', models.ManyToManyField(blank=True, related_name='set_by', to='routing.community')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='StaticRoute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('nexthop', 'Next hop'), ('blackhole', 'Blackhole'), ('reject', 'Reject')], default='nexthop', max_length=10)),
                ('next_hop', models.CharField(blank=True, default='', max_length=64)),
                ('distance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('metric', models.PositiveIntegerField(blank=True, null=True)),
                ('tag', models.PositiveIntegerField(blank=True, null=True)),
                ('bfd', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_routes', to='api.device')),
                ('next_hop_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='static_routes', to='api.interface')),
                ('next_hop_vrf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaked_static_routes', to='api.vrf')),
                ('prefix_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='static_routes', to='api.prefix')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='static_routes', to='api.status')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_routes', to='core.tenant')),
                ('vrf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='static_routes', to='api.vrf')),
            ],
            options={
                'ordering': ['device__name', 'vrf__name', 'prefix'],
            },
        ),
        migrations.AddConstraint(
            model_name='aspathlist',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_aspathlist_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='aspathlistrule',
            constraint=models.UniqueConstraint(fields=('as_path_list', 'sequence'), name='uniq_aspathlistrule_seq'),
        ),
        migrations.AddConstraint(
            model_name='community',
            constraint=models.UniqueConstraint(fields=('tenant', 'value'), name='uniq_community_tenant_value'),
        ),
        migrations.AddConstraint(
            model_name='communitylist',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_communitylist_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='communitylistrule',
            constraint=models.UniqueConstraint(fields=('community_list', 'sequence'), name='uniq_communitylistrule_seq'),
        ),
        migrations.AddConstraint(
            model_name='prefixlist',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_prefixlist_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='prefixlistrule',
            constraint=models.UniqueConstraint(fields=('prefix_list', 'sequence'), name='uniq_prefixlistrule_seq'),
        ),
        migrations.AddConstraint(
            model_name='routingkeychain',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_routingkeychain_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='routingpolicy',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_routingpolicy_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='routingpolicyrule',
            constraint=models.UniqueConstraint(fields=('policy', 'sequence'), name='uniq_routingpolicyrule_seq'),
        ),
        migrations.AddConstraint(
            model_name='staticroute',
            constraint=models.UniqueConstraint(fields=('device', 'vrf', 'prefix', 'next_hop', 'next_hop_interface'), name='uniq_staticroute_path', nulls_distinct=False),
        ),
        migrations.RunPython(seed_statuses, migrations.RunPython.noop),
    ]
