# Generated by Django 5.2.16 on 2026-09-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_routing_policies_static_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticroute',
            name='kind',
            field=models.CharField(choices=[('nexthop', 'Next hop'), ('interface', 'Interface'), ('blackhole', 'Blackhole'), ('reject', 'Reject')], default='nexthop', max_length=10),
        ),
    ]
