# Generated by Django 5.2.16 on 2026-09-15 16:39

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_ipsecprofile_psk'),
        ('core', '0052_sitecertificate'),
        ('routing', '0002_staticroute_interface_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGPInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('router_id', models.CharField(blank=True, default='', max_length=64)),
                ('bfd', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('cluster_id', models.CharField(blank=True, default='', max_length=64)),
                ('graceful_restart', models.BooleanField(default=False)),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bgp_instances', to='api.asn')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.device')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='api.status')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_%(class)ss', to='core.tenant')),
                ('vrf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.vrf')),
            ],
            options={
                'ordering': ['device__name', 'vrf__name'],
            },
        ),
        migrations.CreateModel(
            name='BGPAddressFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('afi_safi', models.CharField(choices=[('ipv4-unicast', 'IPv4 unicast'), ('ipv6-unicast', 'IPv6 unicast'), ('vpnv4-unicast', 'VPNv4 unicast'), ('vpnv6-unicast', 'VPNv6 unicast'), ('l2vpn-evpn', 'L2VPN EVPN'), ('ipv4-labeled-unicast', 'IPv4 labeled unicast')], max_length=24)),
                ('networks', models.JSONField(blank=True, default=list)),
                ('maximum_paths', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('maximum_paths_ibgp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('export_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bgp_af_exports', to='routing.routingpolicy')),
                ('import_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bgp_af_imports', to='routing.routingpolicy')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_families', to='routing.bgpinstance')),
            ],
            options={
                'ordering': ['afi_safi'],
            },
        ),
        migrations.CreateModel(
            name='BGPPeerGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('address_families', models.JSONField(blank=True, default=list)),
                ('bfd', models.BooleanField(blank=True, null=True)),
                ('ebgp_multihop', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('next_hop_self', models.BooleanField(blank=True, null=True)),
                ('route_reflector_client', models.BooleanField(blank=True, null=True)),
                ('send_community', models.CharField(blank=True, choices=[('none', 'None'), ('standard', 'Standard'), ('extended', 'Extended'), ('both', 'Standard and extended'), ('large', 'Large')], default='', max_length=8)),
                ('keepalive', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hold_time', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('remote_asn', models.PositiveBigIntegerField(blank=True, null=True)),
                ('remote_asn_mode', models.CharField(choices=[('asn', 'Number'), ('external', 'External (any other AS)'), ('internal', 'Internal (own AS)')], default='asn', max_length=8)),
                ('update_source', models.CharField(blank=True, default='', max_length=64)),
                ('export_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_exports', to='routing.routingpolicy')),
                ('import_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_imports', to='routing.routingpolicy')),
                ('keychain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='routing.routingkeychain')),
                ('local_asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bgp_peer_groups_local', to='api.asn')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_%(class)ss', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BGPSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('address_families', models.JSONField(blank=True, default=list)),
                ('bfd', models.BooleanField(blank=True, null=True)),
                ('ebgp_multihop', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('next_hop_self', models.BooleanField(blank=True, null=True)),
                ('route_reflector_client', models.BooleanField(blank=True, null=True)),
                ('send_community', models.CharField(blank=True, choices=[('none', 'None'), ('standard', 'Standard'), ('extended', 'Extended'), ('both', 'Standard and extended'), ('large', 'Large')], default='', max_length=8)),
                ('keepalive', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hold_time', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('remote_asn', models.PositiveBigIntegerField(blank=True, null=True)),
                ('remote_asn_mode', models.CharField(blank=True, choices=[('asn', 'Number'), ('external', 'External (any other AS)'), ('internal', 'Internal (own AS)')], default='', max_length=8)),
                ('remote_address', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('export_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_exports', to='routing.routingpolicy')),
                ('import_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_imports', to='routing.routingpolicy')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='routing.bgpinstance')),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bgp_sessions', to='api.interface')),
                ('keychain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='routing.routingkeychain')),
                ('local_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bgp_sessions_local', to='api.ipaddress')),
                ('local_asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bgp_sessions_local', to='api.asn')),
                ('peer_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bgp_peer_sessions', to='api.device')),
                ('peer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='routing.bgppeergroup')),
                ('peer_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peer_of', to='routing.bgpsession')),
                ('remote_address_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bgp_sessions_remote', to='api.ipaddress')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bgp_sessions', to='api.status')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bgp_sessions', to='core.tenant')),
            ],
            options={
                'ordering': ['instance__device__name', 'remote_address', 'interface__name'],
            },
        ),
        migrations.CreateModel(
            name='Redistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('connected', 'Connected'), ('static', 'Static'), ('bgp', 'BGP'), ('ospf', 'OSPF'), ('isis', 'IS-IS'), ('kernel', 'Kernel')], max_length=12)),
                ('metric', models.PositiveIntegerField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('bgp_af', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redistributions', to='routing.bgpaddressfamily')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redistributions', to='routing.routingpolicy')),
            ],
            options={
                'ordering': ['source'],
            },
        ),
        migrations.AddConstraint(
            model_name='bgpinstance',
            constraint=models.UniqueConstraint(fields=('device', 'vrf'), name='uniq_bgpinstance_device_vrf', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='bgpaddressfamily',
            constraint=models.UniqueConstraint(fields=('instance', 'afi_safi'), name='uniq_bgpaf_instance_afi'),
        ),
        migrations.AddConstraint(
            model_name='bgppeergroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_bgppeergroup_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='bgpsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('interface__isnull', False), ('remote_address', '')), models.Q(models.Q(('remote_address', ''), _negated=True), ('interface__isnull', True)), _connector='OR'), name='bgpsession_address_xor_interface'),
        ),
        migrations.AddConstraint(
            model_name='bgpsession',
            constraint=models.UniqueConstraint(condition=models.Q(('remote_address', ''), _negated=True), fields=('instance', 'remote_address'), name='uniq_bgpsession_instance_address'),
        ),
        migrations.AddConstraint(
            model_name='bgpsession',
            constraint=models.UniqueConstraint(condition=models.Q(('interface__isnull', False)), fields=('instance', 'interface'), name='uniq_bgpsession_instance_interface'),
        ),
        migrations.AddConstraint(
            model_name='redistribution',
            constraint=models.CheckConstraint(condition=models.Q(('bgp_af__isnull', False)), name='redistribution_one_parent'),
        ),
    ]
