# Generated by Django 5.2.16 on 2026-09-15 17:13

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_ipsecprofile_psk'),
        ('core', '0052_sitecertificate'),
        ('routing', '0004_seed_bgp_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISISInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('router_id', models.CharField(blank=True, default='', max_length=64)),
                ('bfd', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('process', models.CharField(blank=True, default='', max_length=32)),
                ('net', models.CharField(help_text='49.0001.0000.0000.0001.00', max_length=64)),
                ('level', models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2'), ('1-2', 'Level 1-2')], default='1-2', max_length=3)),
                ('metric_style', models.CharField(choices=[('wide', 'Wide'), ('narrow', 'Narrow'), ('transition', 'Transition')], default='wide', max_length=10)),
                ('authentication', models.CharField(choices=[('none', 'None'), ('text', 'Clear text'), ('md5', 'MD5')], default='none', max_length=4)),
            ],
            options={
                'ordering': ['device__name', 'process'],
            },
        ),
        migrations.CreateModel(
            name='ISISInterface',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passive', models.BooleanField(blank=True, null=True)),
                ('bfd', models.BooleanField(default=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('families', models.JSONField(blank=True, default=list)),
                ('level', models.CharField(blank=True, choices=[('1', 'Level 1'), ('2', 'Level 2'), ('1-2', 'Level 1-2')], default='', max_length=3)),
                ('metric', models.PositiveIntegerField(blank=True, null=True)),
                ('metric_l2', models.PositiveIntegerField(blank=True, null=True)),
                ('network_type', models.CharField(blank=True, choices=[('point-to-point', 'Point-to-point'), ('broadcast', 'Broadcast')], default='', max_length=14)),
                ('hello_interval', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hello_multiplier', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('authentication', models.CharField(choices=[('none', 'None'), ('text', 'Clear text'), ('md5', 'MD5')], default='none', max_length=4)),
            ],
            options={
                'ordering': ['interface__name'],
            },
        ),
        migrations.CreateModel(
            name='OSPFArea',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('area_id', models.CharField(help_text='0 or 0.0.0.0', max_length=15)),
                ('kind', models.CharField(choices=[('normal', 'Normal'), ('stub', 'Stub'), ('totally-stub', 'Totally stubby'), ('nssa', 'NSSA'), ('totally-nssa', 'Totally NSSA')], default='normal', max_length=13)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OSPFInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('router_id', models.CharField(blank=True, default='', max_length=64)),
                ('bfd', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('process_id', models.CharField(blank=True, default='', max_length=32)),
                ('version', models.PositiveSmallIntegerField(choices=[(2, 'OSPFv2'), (3, 'OSPFv3')], default=2)),
                ('reference_bandwidth', models.PositiveIntegerField(blank=True, help_text='Mbit/s', null=True)),
                ('passive_by_default', models.BooleanField(default=False)),
                ('default_originate', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['device__name', 'vrf__name', 'process_id'],
            },
        ),
        migrations.CreateModel(
            name='OSPFInterface',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passive', models.BooleanField(blank=True, null=True)),
                ('bfd', models.BooleanField(default=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
                ('network_type', models.CharField(blank=True, choices=[('broadcast', 'Broadcast'), ('point-to-point', 'Point-to-point'), ('nbma', 'NBMA'), ('point-to-multipoint', 'Point-to-multipoint')], default='', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hello', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dead', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mtu_ignore', models.BooleanField(default=False)),
                ('authentication', models.CharField(choices=[('none', 'None'), ('simple', 'Simple'), ('md5', 'MD5'), ('sha', 'SHA')], default='none', max_length=6)),
            ],
            options={
                'ordering': ['interface__name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='redistribution',
            name='redistribution_one_parent',
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.device'),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='keychain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isis_instances', to='routing.routingkeychain'),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='api.status'),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_%(class)ss', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='vrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.vrf'),
        ),
        migrations.AddField(
            model_name='redistribution',
            name='isis_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redistributions', to='routing.isisinstance'),
        ),
        migrations.AddField(
            model_name='isisinterface',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='routing.isisinstance'),
        ),
        migrations.AddField(
            model_name='isisinterface',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.interface'),
        ),
        migrations.AddField(
            model_name='isisinterface',
            name='keychain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='routing.routingkeychain'),
        ),
        migrations.AddField(
            model_name='ospfarea',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='ospfarea',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_%(class)ss', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='ospfinstance',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.device'),
        ),
        migrations.AddField(
            model_name='ospfinstance',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='api.status'),
        ),
        migrations.AddField(
            model_name='ospfinstance',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='ospfinstance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_%(class)ss', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='ospfinstance',
            name='vrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.vrf'),
        ),
        migrations.AddField(
            model_name='redistribution',
            name='ospf_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redistributions', to='routing.ospfinstance'),
        ),
        migrations.AddConstraint(
            model_name='redistribution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bgp_af__isnull', False), ('isis_instance__isnull', True), ('ospf_instance__isnull', True)), models.Q(('bgp_af__isnull', True), ('isis_instance__isnull', True), ('ospf_instance__isnull', False)), models.Q(('bgp_af__isnull', True), ('isis_instance__isnull', False), ('ospf_instance__isnull', True)), _connector='OR'), name='redistribution_one_parent'),
        ),
        migrations.AddField(
            model_name='ospfinterface',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interfaces', to='routing.ospfarea'),
        ),
        migrations.AddField(
            model_name='ospfinterface',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='routing.ospfinstance'),
        ),
        migrations.AddField(
            model_name='ospfinterface',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.interface'),
        ),
        migrations.AddField(
            model_name='ospfinterface',
            name='keychain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='routing.routingkeychain'),
        ),
        migrations.AddConstraint(
            model_name='isisinstance',
            constraint=models.UniqueConstraint(fields=('device', 'process'), name='uniq_isisinstance_device_process'),
        ),
        migrations.AddConstraint(
            model_name='isisinterface',
            constraint=models.UniqueConstraint(fields=('instance', 'interface'), name='uniq_isisinterface_instance_iface'),
        ),
        migrations.AddConstraint(
            model_name='ospfarea',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_ospfarea_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='ospfinstance',
            constraint=models.UniqueConstraint(fields=('device', 'vrf', 'version', 'process_id'), name='uniq_ospfinstance_process', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='ospfinterface',
            constraint=models.UniqueConstraint(fields=('instance', 'interface'), name='uniq_ospfinterface_instance_iface'),
        ),
    ]
