# Generated by Django 5.2.16 on 2026-09-15 18:02

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0165_l2vpn_vrf_vni'),
        ('core', '0052_sitecertificate'),
        ('routing', '0005_ospf_isis'),
    ]

    operations = [
        migrations.CreateModel(
            name='VTEP',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anycast_gateway_mac', models.CharField(blank=True, default='', max_length=17)),
                ('arp_suppression', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('anycast_ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anycast_vteps', to='api.ipaddress')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vtep', to='api.device')),
                ('source_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vteps', to='api.interface')),
                ('source_ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vteps', to='api.ipaddress')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vteps', to='api.status')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vteps', to='core.tenant')),
            ],
            options={
                'ordering': ['device__name'],
            },
        ),
        migrations.CreateModel(
            name='VTEPMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rd', models.CharField(blank=True, default='', help_text='Per-device RD override', max_length=32)),
                ('ingress_replication', models.BooleanField(default=True)),
                ('mcast_group', models.CharField(blank=True, default='', max_length=64)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('l2vpn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vtep_memberships', to='api.l2vpn')),
                ('vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vtep_memberships', to='api.vlan')),
                ('vtep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='routing.vtep')),
            ],
            options={
                'ordering': ['l2vpn__identifier', 'l2vpn__name'],
                'constraints': [models.UniqueConstraint(fields=('vtep', 'l2vpn'), name='uniq_vtepmembership_vtep_l2vpn')],
            },
        ),
    ]
