# Generated by Django 5.2.16 on 2026-09-15 20:22

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0165_l2vpn_vrf_vni'),
        ('core', '0052_sitecertificate'),
        ('routing', '0006_vtep'),
    ]

    operations = [
        migrations.CreateModel(
            name='EIGRPInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('router_id', models.CharField(blank=True, default='', max_length=64)),
                ('bfd', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('asn', models.PositiveIntegerField(help_text='1…65535')),
                ('name', models.CharField(blank=True, default='', help_text='Named mode', max_length=64)),
                ('k_values', models.CharField(blank=True, default='', max_length=32)),
                ('variance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('maximum_paths', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('passive_by_default', models.BooleanField(default=False)),
                ('stub', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['device__name', 'vrf__name', 'asn'],
            },
        ),
        migrations.CreateModel(
            name='EIGRPInterface',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passive', models.BooleanField(blank=True, null=True)),
                ('bfd', models.BooleanField(default=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('hello_interval', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hold_time', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bandwidth_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('split_horizon', models.BooleanField(blank=True, null=True)),
                ('summary_addresses', models.JSONField(blank=True, default=list)),
                ('authentication', models.CharField(choices=[('none', 'None'), ('md5', 'MD5'), ('hmac-sha-256', 'HMAC-SHA-256')], default='none', max_length=12)),
            ],
            options={
                'ordering': ['interface__name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='redistribution',
            name='redistribution_one_parent',
        ),
        migrations.AlterField(
            model_name='redistribution',
            name='source',
            field=models.CharField(choices=[('connected', 'Connected'), ('static', 'Static'), ('bgp', 'BGP'), ('ospf', 'OSPF'), ('isis', 'IS-IS'), ('eigrp', 'EIGRP'), ('kernel', 'Kernel')], max_length=12),
        ),
        migrations.AddField(
            model_name='eigrpinstance',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.device'),
        ),
        migrations.AddField(
            model_name='eigrpinstance',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='api.status'),
        ),
        migrations.AddField(
            model_name='eigrpinstance',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='eigrpinstance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_%(class)ss', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='eigrpinstance',
            name='vrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.vrf'),
        ),
        migrations.AddField(
            model_name='redistribution',
            name='eigrp_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redistributions', to='routing.eigrpinstance'),
        ),
        migrations.AddConstraint(
            model_name='redistribution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bgp_af__isnull', False), ('eigrp_instance__isnull', True), ('isis_instance__isnull', True), ('ospf_instance__isnull', True)), models.Q(('bgp_af__isnull', True), ('eigrp_instance__isnull', True), ('isis_instance__isnull', True), ('ospf_instance__isnull', False)), models.Q(('bgp_af__isnull', True), ('eigrp_instance__isnull', True), ('isis_instance__isnull', False), ('ospf_instance__isnull', True)), models.Q(('bgp_af__isnull', True), ('eigrp_instance__isnull', False), ('isis_instance__isnull', True), ('ospf_instance__isnull', True)), _connector='OR'), name='redistribution_one_parent'),
        ),
        migrations.AddField(
            model_name='eigrpinterface',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='routing.eigrpinstance'),
        ),
        migrations.AddField(
            model_name='eigrpinterface',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.interface'),
        ),
        migrations.AddField(
            model_name='eigrpinterface',
            name='keychain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='routing.routingkeychain'),
        ),
        migrations.AddConstraint(
            model_name='eigrpinstance',
            constraint=models.UniqueConstraint(fields=('device', 'vrf', 'asn'), name='uniq_eigrpinstance_asn', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='eigrpinterface',
            constraint=models.UniqueConstraint(fields=('instance', 'interface'), name='uniq_eigrpinterface_instance_iface'),
        ),
    ]
