# Generated by Django 5.2.16 on 2026-09-15 20:46

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_sitecertificate'),
        ('routing', '0007_eigrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BFDProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('min_tx', models.PositiveIntegerField(default=300, help_text='ms')),
                ('min_rx', models.PositiveIntegerField(default=300, help_text='ms')),
                ('multiplier', models.PositiveSmallIntegerField(default=3)),
                ('echo', models.BooleanField(default=False)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_%(class)ss', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bgpinstance',
            name='bfd_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='routing.bfdprofile'),
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='bfd_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='routing.bfdprofile'),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='bfd_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='routing.bfdprofile'),
        ),
        migrations.AddField(
            model_name='eigrpinstance',
            name='bfd_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='routing.bfdprofile'),
        ),
        migrations.AddField(
            model_name='eigrpinterface',
            name='bfd_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='routing.bfdprofile'),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='bfd_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='routing.bfdprofile'),
        ),
        migrations.AddField(
            model_name='isisinterface',
            name='bfd_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='routing.bfdprofile'),
        ),
        migrations.AddField(
            model_name='ospfinstance',
            name='bfd_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='routing.bfdprofile'),
        ),
        migrations.AddField(
            model_name='ospfinterface',
            name='bfd_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='routing.bfdprofile'),
        ),
        migrations.AddConstraint(
            model_name='bfdprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_bfdprofile_tenant_name'),
        ),
    ]
