# Generated by Django 5.2.16 on 2026-09-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0008_bfd_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgppeergroup',
            name='allowas_in',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='as_override',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='default_originate',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='maximum_prefix',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='remove_private_as',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='soft_reconfiguration',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='allowas_in',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='as_override',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='default_originate',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='maximum_prefix',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='remove_private_as',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='soft_reconfiguration',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
