# Generated by Django 5.2.16 on 2026-09-21 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0010_af_advertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgpinstance',
            name='bestpath_multipath_relax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bgpinstance',
            name='distance_ebgp',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bgpinstance',
            name='distance_ibgp',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bgpinstance',
            name='distance_local',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='capability_extended_nexthop',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='default_originate_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_default_originates', to='routing.routingpolicy'),
        ),
        migrations.AddField(
            model_name='bgppeergroup',
            name='ttl_security_hops',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='capability_extended_nexthop',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='default_originate_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_default_originates', to='routing.routingpolicy'),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='ttl_security_hops',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='default_originate_ipv4',
            field=models.CharField(blank=True, choices=[('', 'No'), ('on', 'When a default exists'), ('always', 'Always')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='default_originate_ipv6',
            field=models.CharField(blank=True, choices=[('', 'No'), ('on', 'When a default exists'), ('always', 'Always')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='log_adjacency_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='lsp_gen_interval',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='lsp_mtu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='spf_holddown',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='spf_init_delay',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='spf_interval',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='spf_long_delay',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='spf_short_delay',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='spf_time_to_learn',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redistribution',
            name='family',
            field=models.CharField(blank=True, choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='redistribution',
            name='level',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
