# Generated by Django 5.2.16 on 2026-09-21 18:41

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0174_interface_evpn_mh_uplink'),
        ('core', '0053_faceplate_port_labels'),
        ('routing', '0011_isis_bgp_fabric_knobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgpinstance',
            name='vpn_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bgpinstance',
            name='vpn_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bgpinstance',
            name='vpn_label_export',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='bgpinstance',
            name='vpn_nexthop_export',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.CreateModel(
            name='EthernetSegment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('esi', models.CharField(blank=True, default='', max_length=32)),
                ('es_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sys_mac', models.CharField(blank=True, default='', max_length=17)),
                ('df_preference', models.PositiveIntegerField(blank=True, null=True)),
                ('interfaces', models.ManyToManyField(blank=True, related_name='ethernet_segments', to='api.interface')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_%(class)ss', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_ethernetsegment_tenant_name')],
            },
        ),
        migrations.CreateModel(
            name='LDPInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('numid', models.PositiveIntegerField(blank=True, db_index=True, editable=False, help_text='Per-tenant human-readable number (see NumIdSequence).', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('router_id', models.CharField(blank=True, default='', max_length=64)),
                ('bfd', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('transport_address', models.CharField(blank=True, default='', max_length=45)),
                ('label_allocation', models.CharField(choices=[('all', 'All routes'), ('host-routes', 'Host routes only')], default='host-routes', max_length=12)),
                ('bfd_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='routing.bfdprofile')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.device')),
                ('interfaces', models.ManyToManyField(blank=True, related_name='ldp_instances', to='api.interface')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='api.status')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_%(class)ss', to='core.tenant')),
                ('vrf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.vrf')),
            ],
            options={
                'ordering': ['device__name'],
                'constraints': [models.UniqueConstraint(fields=('device',), name='uniq_ldpinstance_device')],
            },
        ),
    ]
