# Generated by Django 5.2.16 on 2026-09-25 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0180_wifi_security_modes'),
        ('core', '0055_dashboards'),
        ('routing', '0012_ethernet_segments_ldp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bgpsession',
            options={'ordering': ['instance__device__name', 'instance__virtual_machine__name', 'remote_address', 'interface__name']},
        ),
        migrations.AlterModelOptions(
            name='eigrpinterface',
            options={'ordering': ['interface__name', 'vm_interface__name']},
        ),
        migrations.AlterModelOptions(
            name='isisinterface',
            options={'ordering': ['interface__name', 'vm_interface__name']},
        ),
        migrations.AlterModelOptions(
            name='ospfinterface',
            options={'ordering': ['interface__name', 'vm_interface__name']},
        ),
        migrations.RemoveConstraint(
            model_name='bgpinstance',
            name='uniq_bgpinstance_device_vrf',
        ),
        migrations.RemoveConstraint(
            model_name='bgpsession',
            name='bgpsession_address_xor_interface',
        ),
        migrations.RemoveConstraint(
            model_name='eigrpinstance',
            name='uniq_eigrpinstance_asn',
        ),
        migrations.RemoveConstraint(
            model_name='eigrpinterface',
            name='uniq_eigrpinterface_instance_iface',
        ),
        migrations.RemoveConstraint(
            model_name='isisinstance',
            name='uniq_isisinstance_device_process',
        ),
        migrations.RemoveConstraint(
            model_name='isisinterface',
            name='uniq_isisinterface_instance_iface',
        ),
        migrations.RemoveConstraint(
            model_name='ospfinstance',
            name='uniq_ospfinstance_process',
        ),
        migrations.RemoveConstraint(
            model_name='ospfinterface',
            name='uniq_ospfinterface_instance_iface',
        ),
        migrations.RemoveConstraint(
            model_name='staticroute',
            name='uniq_staticroute_path',
        ),
        migrations.AddField(
            model_name='bgpinstance',
            name='virtual_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.virtualmachine'),
        ),
        migrations.AddField(
            model_name='bgpsession',
            name='vm_interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bgp_sessions', to='api.vminterface'),
        ),
        migrations.AddField(
            model_name='eigrpinstance',
            name='virtual_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.virtualmachine'),
        ),
        migrations.AddField(
            model_name='eigrpinterface',
            name='vm_interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.vminterface'),
        ),
        migrations.AddField(
            model_name='isisinstance',
            name='virtual_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.virtualmachine'),
        ),
        migrations.AddField(
            model_name='isisinterface',
            name='vm_interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.vminterface'),
        ),
        migrations.AddField(
            model_name='ospfinstance',
            name='virtual_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.virtualmachine'),
        ),
        migrations.AddField(
            model_name='ospfinterface',
            name='vm_interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.vminterface'),
        ),
        migrations.AddField(
            model_name='staticroute',
            name='next_hop_vm_interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='static_routes', to='api.vminterface'),
        ),
        migrations.AddField(
            model_name='staticroute',
            name='virtual_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='static_routes', to='api.virtualmachine'),
        ),
        migrations.AlterField(
            model_name='bgpinstance',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.device'),
        ),
        migrations.AlterField(
            model_name='eigrpinstance',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.device'),
        ),
        migrations.AlterField(
            model_name='eigrpinterface',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.interface'),
        ),
        migrations.AlterField(
            model_name='isisinstance',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.device'),
        ),
        migrations.AlterField(
            model_name='isisinterface',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.interface'),
        ),
        migrations.AlterField(
            model_name='ldpinstance',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ldpinstances', to='api.device'),
        ),
        migrations.AlterField(
            model_name='ospfinstance',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.device'),
        ),
        migrations.AlterField(
            model_name='ospfinterface',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.interface'),
        ),
        migrations.AlterField(
            model_name='staticroute',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='static_routes', to='api.device'),
        ),
        migrations.AddConstraint(
            model_name='bgpinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('device__isnull', False)), fields=('device', 'vrf'), name='uniq_bgpinstance_device_vrf', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='bgpinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('virtual_machine__isnull', False)), fields=('virtual_machine', 'vrf'), name='uniq_bgpinstance_vm_vrf', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='bgpinstance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('device__isnull', False), ('virtual_machine__isnull', True)), models.Q(('device__isnull', True), ('virtual_machine__isnull', False)), _connector='OR'), name='bgpinstance_device_xor_vm'),
        ),
        migrations.AddConstraint(
            model_name='bgpsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('interface__isnull', False), ('remote_address', ''), ('vm_interface__isnull', True)), models.Q(('interface__isnull', True), ('remote_address', ''), ('vm_interface__isnull', False)), models.Q(models.Q(('remote_address', ''), _negated=True), ('interface__isnull', True), ('vm_interface__isnull', True)), _connector='OR'), name='bgpsession_address_xor_interface'),
        ),
        migrations.AddConstraint(
            model_name='bgpsession',
            constraint=models.UniqueConstraint(condition=models.Q(('vm_interface__isnull', False)), fields=('instance', 'vm_interface'), name='uniq_bgpsession_instance_vm_interface'),
        ),
        migrations.AddConstraint(
            model_name='eigrpinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('device__isnull', False)), fields=('device', 'vrf', 'asn'), name='uniq_eigrpinstance_asn', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='eigrpinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('virtual_machine__isnull', False)), fields=('virtual_machine', 'vrf', 'asn'), name='uniq_eigrpinstance_vm_asn', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='eigrpinstance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('device__isnull', False), ('virtual_machine__isnull', True)), models.Q(('device__isnull', True), ('virtual_machine__isnull', False)), _connector='OR'), name='eigrpinstance_device_xor_vm'),
        ),
        migrations.AddConstraint(
            model_name='eigrpinterface',
            constraint=models.UniqueConstraint(condition=models.Q(('interface__isnull', False)), fields=('instance', 'interface'), name='uniq_eigrpinterface_instance_iface'),
        ),
        migrations.AddConstraint(
            model_name='eigrpinterface',
            constraint=models.UniqueConstraint(condition=models.Q(('vm_interface__isnull', False)), fields=('instance', 'vm_interface'), name='uniq_eigrpinterface_instance_vm_iface'),
        ),
        migrations.AddConstraint(
            model_name='eigrpinterface',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('interface__isnull', False), ('vm_interface__isnull', True)), models.Q(('interface__isnull', True), ('vm_interface__isnull', False)), _connector='OR'), name='eigrpinterface_iface_xor_vm_iface'),
        ),
        migrations.AddConstraint(
            model_name='isisinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('device__isnull', False)), fields=('device', 'process'), name='uniq_isisinstance_device_process'),
        ),
        migrations.AddConstraint(
            model_name='isisinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('virtual_machine__isnull', False)), fields=('virtual_machine', 'process'), name='uniq_isisinstance_vm_process'),
        ),
        migrations.AddConstraint(
            model_name='isisinstance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('device__isnull', False), ('virtual_machine__isnull', True)), models.Q(('device__isnull', True), ('virtual_machine__isnull', False)), _connector='OR'), name='isisinstance_device_xor_vm'),
        ),
        migrations.AddConstraint(
            model_name='isisinterface',
            constraint=models.UniqueConstraint(condition=models.Q(('interface__isnull', False)), fields=('instance', 'interface'), name='uniq_isisinterface_instance_iface'),
        ),
        migrations.AddConstraint(
            model_name='isisinterface',
            constraint=models.UniqueConstraint(condition=models.Q(('vm_interface__isnull', False)), fields=('instance', 'vm_interface'), name='uniq_isisinterface_instance_vm_iface'),
        ),
        migrations.AddConstraint(
            model_name='isisinterface',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('interface__isnull', False), ('vm_interface__isnull', True)), models.Q(('interface__isnull', True), ('vm_interface__isnull', False)), _connector='OR'), name='isisinterface_iface_xor_vm_iface'),
        ),
        migrations.AddConstraint(
            model_name='ospfinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('device__isnull', False)), fields=('device', 'vrf', 'version', 'process_id'), name='uniq_ospfinstance_process', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='ospfinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('virtual_machine__isnull', False)), fields=('virtual_machine', 'vrf', 'version', 'process_id'), name='uniq_ospfinstance_vm_process', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='ospfinstance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('device__isnull', False), ('virtual_machine__isnull', True)), models.Q(('device__isnull', True), ('virtual_machine__isnull', False)), _connector='OR'), name='ospfinstance_device_xor_vm'),
        ),
        migrations.AddConstraint(
            model_name='ospfinterface',
            constraint=models.UniqueConstraint(condition=models.Q(('interface__isnull', False)), fields=('instance', 'interface'), name='uniq_ospfinterface_instance_iface'),
        ),
        migrations.AddConstraint(
            model_name='ospfinterface',
            constraint=models.UniqueConstraint(condition=models.Q(('vm_interface__isnull', False)), fields=('instance', 'vm_interface'), name='uniq_ospfinterface_instance_vm_iface'),
        ),
        migrations.AddConstraint(
            model_name='ospfinterface',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('interface__isnull', False), ('vm_interface__isnull', True)), models.Q(('interface__isnull', True), ('vm_interface__isnull', False)), _connector='OR'), name='ospfinterface_iface_xor_vm_iface'),
        ),
        migrations.AddConstraint(
            model_name='staticroute',
            constraint=models.UniqueConstraint(condition=models.Q(('device__isnull', False)), fields=('device', 'vrf', 'prefix', 'next_hop', 'next_hop_interface'), name='uniq_staticroute_path', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='staticroute',
            constraint=models.UniqueConstraint(condition=models.Q(('virtual_machine__isnull', False)), fields=('virtual_machine', 'vrf', 'prefix', 'next_hop', 'next_hop_vm_interface'), name='uniq_staticroute_vm_path', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='staticroute',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('device__isnull', False), ('virtual_machine__isnull', True)), models.Q(('device__isnull', True), ('virtual_machine__isnull', False)), _connector='OR'), name='staticroute_device_xor_vm'),
        ),
    ]
