# Generated by Django 5.2.16 on 2026-10-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0013_vm_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgpaddressfamily',
            name='advertise_ipv4_unicast',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='bgpaddressfamily',
            name='advertise_ipv6_unicast',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='bgpinstance',
            name='bestpath_multipath_relax',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='bgpinstance',
            name='vpn_export',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='bgpinstance',
            name='vpn_import',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='bgpinstance',
            name='vpn_label_export',
            field=models.CharField(blank=True, db_default='', default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='bgpinstance',
            name='vpn_nexthop_export',
            field=models.CharField(blank=True, db_default='', default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='isisinstance',
            name='default_originate_ipv4',
            field=models.CharField(blank=True, choices=[('', 'No'), ('on', 'When a default exists'), ('always', 'Always')], db_default='', default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='isisinstance',
            name='default_originate_ipv6',
            field=models.CharField(blank=True, choices=[('', 'No'), ('on', 'When a default exists'), ('always', 'Always')], db_default='', default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='isisinstance',
            name='log_adjacency_changes',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='redistribution',
            name='family',
            field=models.CharField(blank=True, choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6')], db_default='', default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='redistribution',
            name='level',
            field=models.CharField(blank=True, db_default='', default='', max_length=3),
        ),
    ]
