# Generated by Django 5.2.15 on 2026-06-23 20:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_deploymentsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_name', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=8)),
                ('object_type', models.CharField(help_text='Model label, e.g. api.prefix.', max_length=64)),
                ('object_label', models.CharField(help_text='Human model name, e.g. Prefix.', max_length=64)),
                ('object_id', models.CharField(max_length=64)),
                ('object_repr', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, default='', max_length=36)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changelog', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changelog', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'change log entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant', '-timestamp'], name='audit_chang_tenant__5e50b1_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_chang_object__5bb19a_idx'), models.Index(fields=['user', '-timestamp'], name='audit_chang_user_id_d1d31f_idx')],
            },
        ),
    ]
