# Generated by Django 5.2.15 on 2026-06-24 12:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('core', '0005_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('object_type', models.CharField(help_text='Model label, e.g. api.prefix.', max_length=64)),
                ('object_id', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=8)),
                ('comments', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'journal entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['object_type', 'object_id', '-created_at'], name='audit_journ_object__76b7b7_idx'), models.Index(fields=['tenant', '-created_at'], name='audit_journ_tenant__b3e09b_idx')],
            },
        ),
    ]
