# Generated by Django 5.2.15 on 2026-07-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_journalentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="changelogentry",
            name="post_change",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="changelogentry",
            name="pre_change",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
