# Generated by Django 5.2.15 on 2026-07-18 11:21

from django.db import migrations, models

# NOTE: this migration originally ran a data-backfill (`_backfill_site`) that
# called the LIVE ``auth_api.site_paths.site_path_for`` → ``DeploymentSettings
# .load()``. On an upgrade from an older database that backfill executed a
# SELECT referencing model columns that a *later* migration adds
# (``core.disable_update_check``), so — depending on the migration plan order —
# it crashed with "column core_deploymentsettings.disable_update_check does not
# exist". The backfill is redundant anyway: ``0007_backfill_audit_site_scope``
# re-stamps every ``object_site_id IS NULL`` row correctly, using *historical*
# models (``apps.get_model``) instead of live app code. So this migration now
# only adds the columns; the backfill lives solely in 0007.


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_scrub_secret_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelogentry',
            name='object_site_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='object_site_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
