# Generated by Django 5.2.15 on 2026-07-18 11:21

from django.db import migrations, models


def _backfill_site(apps, schema_editor):
    """Best-effort: stamp object_site_id on existing rows from their live
    object. Rows whose object was already deleted stay NULL (their site can't be
    recovered) — new writes carry the site from the moment this ships."""
    from django.apps import apps as live_apps

    from auth_api.site_paths import site_path_for

    def resolve(label, oid):
        try:
            model = live_apps.get_model(label)
        except Exception:  # noqa: BLE001
            return None
        slug = model._meta.model_name
        path = site_path_for(slug, None)
        if not path:
            return None
        obj = model._default_manager.filter(pk=oid).first()
        if obj is None:
            return None
        if path == "id":
            return obj.pk
        parts = path.split("__")
        cur = obj
        for part in parts[:-1]:
            cur = getattr(cur, part, None)
            if cur is None:
                return None
        return getattr(cur, f"{parts[-1]}_id", None)

    for name in ("ChangeLogEntry", "JournalEntry"):
        Model = apps.get_model("audit", name)
        # Cache per (type, id) so a hot object isn't resolved repeatedly.
        cache: dict = {}
        batch = []
        for row in Model.objects.all().iterator(chunk_size=1000):
            key = (row.object_type, row.object_id)
            if key not in cache:
                cache[key] = resolve(row.object_type, row.object_id)
            sid = cache[key]
            if sid is not None:
                row.object_site_id = sid
                batch.append(row)
            if len(batch) >= 1000:
                Model.objects.bulk_update(batch, ["object_site_id"])
                batch = []
        if batch:
            Model.objects.bulk_update(batch, ["object_site_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_scrub_secret_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelogentry',
            name='object_site_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='object_site_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(_backfill_site, migrations.RunPython.noop),
    ]
