# Generated by Django 5.2.16 on 2026-07-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_backfill_audit_site_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelogentry',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('reveal', 'Secret revealed')], max_length=8),
        ),
    ]
