# Generated by Django 5.2.16 on 2026-08-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_alter_changelogentry_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelogentry',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('reveal', 'Secret revealed'), ('connect', 'Connected')], max_length=8),
        ),
    ]
