# Generated by Django 5.2.16 on 2026-08-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_alter_changelogentry_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelogentry',
            name='via',
            field=models.CharField(blank=True, choices=[('ui', 'UI'), ('api', 'API'), ('system', 'System')], default='', max_length=8),
        ),
    ]
