# Generated by Django 5.2.16 on 2026-09-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_changelogentry_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelogentry',
            name='via',
            field=models.CharField(blank=True, choices=[('ui', 'UI'), ('api', 'API'), ('chat', 'Assistant'), ('system', 'System')], default='', max_length=8),
        ),
    ]
