# Generated by Django 5.2.15 on 2026-06-25 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_deploymentsettings_ldap_attr_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('object_types', models.JSONField(default=list, help_text='Object-type slugs this fires for (see the RBAC registry), or ["*"] for every type.')),
                ('on_create', models.BooleanField(default=True)),
                ('on_update', models.BooleanField(default=True)),
                ('on_delete', models.BooleanField(default=False)),
                ('payload_url', models.URLField(max_length=512)),
                ('http_method', models.CharField(choices=[('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH')], default='POST', max_length=8)),
                ('http_content_type', models.CharField(default='application/json', max_length=100)),
                ('secret', models.CharField(blank=True, default='', help_text='When set, payloads are signed: the hex HMAC-SHA512 of the body is sent in the X-Danbyte-Signature header.', max_length=255)),
                ('additional_headers', models.TextField(blank=True, default='', help_text="Extra request headers, one 'Name: value' per line.")),
                ('ssl_verification', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_webhook_tenant_name')],
            },
        ),
    ]
