# Generated by Django 5.2.15 on 2026-06-26 10:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_deploymentsettings_ldap_attr_email_and_more'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationTarget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('awx', 'Ansible AWX / AAP'), ('webhook', 'Generic webhook')], default='awx', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('base_url', models.URLField(help_text='AWX/AAP controller URL (e.g. https://awx.example.com) or, for a generic webhook, the full POST URL.', max_length=512)),
                ('job_template_id', models.CharField(blank=True, default='', help_text='AWX job-template id to launch (AWX kind only).', max_length=64)),
                ('token', models.CharField(blank=True, default='', help_text='AWX bearer token / webhook signing secret. Write-only.', max_length=512)),
                ('ssl_verify', models.BooleanField(default=True)),
                ('extra_vars', models.JSONField(blank=True, default=dict, help_text='Extra vars merged into the AWX launch / webhook payload.')),
                ('auto_on_change', models.BooleanField(default=False)),
                ('object_types', models.JSONField(default=list, help_text='Object-type slugs this target can deploy (default: device).')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_targets', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeployRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_name', models.CharField(max_length=128)),
                ('event', models.CharField(default='manual', max_length=32)),
                ('device_ids', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('launched', 'Launched'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='integrations.automationtarget')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deploy_runs', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='automationtarget',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_automationtarget_tenant_name'),
        ),
    ]
