# Generated by Django 5.2.15 on 2026-06-26 11:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_exporttemplate'),
        ('core', '0006_deploymentsettings_ldap_attr_email_and_more'),
        ('integrations', '0002_automationtarget_deployrun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfigState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_sync', 'In sync'), ('drift', 'Drift'), ('unknown', 'Unknown'), ('error', 'Error')], default='unknown', max_length=16)),
                ('intended_config', models.TextField(blank=True, default='')),
                ('actual_config', models.TextField(blank=True, default='')),
                ('diff', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', help_text="Who reported the actual config (e.g. 'ansible', 'nornir').", max_length=64)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_state', to='api.device')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.exporttemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_states', to='core.tenant')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
