# Generated by Django 5.2.15 on 2026-06-26 15:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_interface_type_alter_cable_type'),
        ('core', '0006_deploymentsettings_ldap_attr_email_and_more'),
        ('integrations', '0003_deviceconfigstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfigSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=16)),
                ('diff', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_snapshots', to='api.device')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_snapshots', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', '-created_at'], name='integration_device__3584c8_idx')],
            },
        ),
    ]
