# Generated by Django 5.2.15 on 2026-06-30 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_deviceconfigsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployrun',
            name='attempt',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deployrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployrun',
            name='retry_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='integrations.deployrun'),
        ),
    ]
