# Generated by Django 5.2.15 on 2026-07-16 06:35

import django.db.models.deletion
import monitoring.secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_sitesettings'),
        ('integrations', '0006_encrypt_webhook_secret_awx_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetBoxImportRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('dry_run', models.BooleanField(default=True)),
                ('update_existing', models.BooleanField(default=False)),
                ('only', models.JSONField(blank=True, default=list)),
                ('skip', models.JSONField(blank=True, default=list)),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('secrets', monitoring.secrets.EncryptedJSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='netbox_imports', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='integration_tenant__e0e1ec_idx')],
            },
        ),
    ]
