# Generated by Django 5.2.15 on 2026-07-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_netboximportrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='netboximportrun',
            name='insecure',
            field=models.BooleanField(default=False),
        ),
    ]
