# Generated by Django 5.2.15 on 2026-07-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_netboximportrun_insecure'),
    ]

    operations = [
        migrations.AddField(
            model_name='netboximportrun',
            name='with_images',
            field=models.BooleanField(default=False),
        ),
    ]
