# Generated by Django 5.2.16 on 2026-08-16 16:51

import django.db.models.deletion
import monitoring.secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_deploymentsettings_component_popover_fields'),
        ('integrations', '0009_netboximportrun_with_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dhcp_sync_enabled', models.BooleanField(default=False)),
                ('dns_sync_enabled', models.BooleanField(default=False)),
                ('virtualization_enabled', models.BooleanField(default=False)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration_settings', to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'integration settings',
            },
        ),
        migrations.CreateModel(
            name='VirtualizationSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('proxmox', 'Proxmox VE'), ('vcenter', 'VMware vCenter')], default='proxmox', max_length=16)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=8006)),
                ('verify_ssl', models.BooleanField(default=False)),
                ('credentials', monitoring.secrets.EncryptedJSONField(blank=True, default=dict)),
                ('poll_interval_minutes', models.PositiveIntegerField(default=10)),
                ('enabled', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, default='', max_length=16)),
                ('last_sync_error', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtualization_sources', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_virtsource_tenant_name')],
            },
        ),
        migrations.CreateModel(
            name='WindowsServerConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=5985)),
                ('use_tls', models.BooleanField(default=False)),
                ('verify_ssl', models.BooleanField(default=False)),
                ('auth_mode', models.CharField(choices=[('ntlm', 'NTLM'), ('kerberos', 'Kerberos')], default='ntlm', max_length=16)),
                ('username', models.CharField(max_length=255)),
                ('credentials', monitoring.secrets.EncryptedJSONField(blank=True, default=dict)),
                ('dhcp_enabled', models.BooleanField(default=False)),
                ('dns_enabled', models.BooleanField(default=False)),
                ('poll_interval_minutes', models.PositiveIntegerField(default=5)),
                ('enabled', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, default='', max_length=16)),
                ('last_sync_error', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows_connections', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_winconn_tenant_name')],
            },
        ),
    ]
