# Generated by Django 5.2.16 on 2026-08-16 17:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_interface_is_uplink'),
        ('integrations', '0010_integrationsettings_virtualizationsource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DhcpScope',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('state', models.CharField(blank=True, default='', max_length=32)),
                ('start_range', models.GenericIPAddressField(blank=True, null=True)),
                ('end_range', models.GenericIPAddressField(blank=True, null=True)),
                ('subnet_mask', models.GenericIPAddressField(blank=True, null=True)),
                ('lease_duration', models.CharField(blank=True, default='', max_length=64)),
                ('options', models.JSONField(blank=True, default=list)),
                ('lease_sync', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dhcp_scopes', to='integrations.windowsserverconnection')),
                ('prefix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dhcp_scopes', to='api.prefix')),
            ],
            options={
                'ordering': ['scope_id'],
            },
        ),
        migrations.CreateModel(
            name='DhcpReservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField()),
                ('mac', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('managed', models.BooleanField(default=False)),
                ('drift', models.CharField(blank=True, choices=[('', 'In sync'), ('modified', 'Modified on server'), ('missing', 'Missing on server')], default='', max_length=16)),
                ('drift_detail', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dhcp_reservations', to='api.ipaddress')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='integrations.dhcpscope')),
            ],
            options={
                'ordering': ['ip'],
            },
        ),
        migrations.CreateModel(
            name='DhcpLease',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField()),
                ('mac', models.CharField(blank=True, default='', max_length=64)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('address_state', models.CharField(blank=True, default='', max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_ip', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dhcp_leases', to='api.ipaddress')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='integrations.dhcpscope')),
            ],
            options={
                'ordering': ['ip'],
            },
        ),
        migrations.CreateModel(
            name='DhcpExclusion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_address', models.GenericIPAddressField()),
                ('end_address', models.GenericIPAddressField()),
                ('ip_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dhcp_exclusions', to='api.iprange')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='integrations.dhcpscope')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dhcpscope',
            constraint=models.UniqueConstraint(fields=('connection', 'scope_id'), name='uniq_dhcpscope_conn_scope'),
        ),
        migrations.AddConstraint(
            model_name='dhcpreservation',
            constraint=models.UniqueConstraint(fields=('scope', 'ip'), name='uniq_dhcpres_scope_ip'),
        ),
        migrations.AddConstraint(
            model_name='dhcplease',
            constraint=models.UniqueConstraint(fields=('scope', 'ip'), name='uniq_dhcplease_scope_ip'),
        ),
        migrations.AddConstraint(
            model_name='dhcpexclusion',
            constraint=models.UniqueConstraint(fields=('scope', 'start_address', 'end_address'), name='uniq_dhcpexcl_scope_range'),
        ),
    ]
