# Generated by Django 5.2.16 on 2026-08-16 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_interface_is_uplink'),
        ('integrations', '0011_dhcpscope_dhcpreservation_dhcplease_dhcpexclusion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnsZone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('zone_type', models.CharField(blank=True, default='', max_length=32)),
                ('is_reverse', models.BooleanField(default=False)),
                ('sync', models.BooleanField(default=False)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_zones', to='integrations.windowsserverconnection')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DnsDrift',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('mismatch', 'Name differs'), ('missing_record', 'No record on server')], max_length=16)),
                ('record_type', models.CharField(blank=True, default='', max_length=8)),
                ('ip', models.GenericIPAddressField()),
                ('danbyte_name', models.CharField(blank=True, default='', max_length=255)),
                ('server_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_drifts', to='api.ipaddress')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drifts', to='integrations.dnszone')),
            ],
            options={
                'ordering': ['ip'],
            },
        ),
        migrations.AddConstraint(
            model_name='dnszone',
            constraint=models.UniqueConstraint(fields=('connection', 'name'), name='uniq_dnszone_conn_name'),
        ),
        migrations.AddConstraint(
            model_name='dnsdrift',
            constraint=models.UniqueConstraint(fields=('zone', 'ip', 'record_type'), name='uniq_dnsdrift_zone_ip_type'),
        ),
    ]
