# Generated by Django 5.2.16 on 2026-08-16 17:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_interface_is_uplink'),
        ('integrations', '0012_dnszone_dnsdrift_dnszone_uniq_dnszone_conn_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtGuest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vmid', models.PositiveIntegerField()),
                ('node', models.CharField(blank=True, default='', max_length=128)),
                ('kind', models.CharField(choices=[('qemu', 'QEMU'), ('lxc', 'LXC')], default='qemu', max_length=8)),
                ('created_vm', models.BooleanField(default=False)),
                ('power_state', models.CharField(blank=True, default='', max_length=16)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='integrations.virtualizationsource')),
                ('vm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virt_guests', to='api.virtualmachine')),
            ],
            options={
                'ordering': ['vmid'],
                'constraints': [models.UniqueConstraint(fields=('source', 'vmid'), name='uniq_virtguest_source_vmid')],
            },
        ),
    ]
