# Generated by Django 5.2.16 on 2026-08-16 19:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_interface_is_uplink'),
        ('integrations', '0013_virtguest'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualizationsource',
            name='sync_mode',
            field=models.CharField(choices=[('auto', 'Automatic (mirror)'), ('review', 'Review (scheduled detect, apply on accept)'), ('manual', 'Manual (detect on demand, apply on accept)')], default='review', max_length=8),
        ),
        migrations.CreateModel(
            name='VirtChange',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('new_guest', 'New VM on hypervisor'), ('spec_change', 'Specs changed'), ('removed_guest', 'VM removed from hypervisor')], max_length=16)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ignored', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='integrations.virtguest')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='integrations.virtualizationsource')),
                ('vm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virt_changes', to='api.virtualmachine')),
            ],
            options={
                'ordering': ['kind', 'guest__vmid'],
                'constraints': [models.UniqueConstraint(fields=('guest', 'kind'), name='uniq_virtchange_guest_kind')],
            },
        ),
    ]
