# Generated by Django 5.2.16 on 2026-08-16 19:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_interface_is_uplink'),
        ('integrations', '0014_virtualizationsource_sync_mode_virtchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnsRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('record_type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('PTR', 'PTR')], max_length=8)),
                ('data', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('ttl', models.CharField(blank=True, default='', max_length=32)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dns_records', to='api.ipaddress')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='integrations.dnszone')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['zone', 'ip'], name='integration_zone_id_b5682c_idx'), models.Index(fields=['ip_address'], name='integration_ip_addr_562d66_idx')],
                'constraints': [models.UniqueConstraint(fields=('zone', 'name', 'record_type', 'data'), name='uniq_dnsrecord_zone_name_type_data')],
            },
        ),
    ]
