# Generated by Django 5.2.16 on 2026-08-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_dnsrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnszone',
            name='auto_create',
            field=models.BooleanField(default=False),
        ),
    ]
