# Generated by Django 5.2.16 on 2026-08-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0016_dnszone_auto_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtguest',
            name='kind',
            field=models.CharField(choices=[('qemu', 'QEMU'), ('lxc', 'LXC'), ('vmware', 'VMware VM')], default='qemu', max_length=8),
        ),
    ]
