# Generated by Django 5.2.16 on 2026-08-17 10:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_virtualdisk_virtualswitch'),
        ('integrations', '0017_alter_virtguest_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualizationsource',
            name='sync_disks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='virtualizationsource',
            name='sync_networks',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VirtNetwork',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ext_key', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('created_vlan', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='integrations.virtualizationsource')),
                ('vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virt_networks', to='api.vlan')),
                ('vswitch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virt_networks', to='api.virtualswitch')),
            ],
            options={
                'ordering': ['name', 'ext_key'],
                'constraints': [models.UniqueConstraint(fields=('source', 'ext_key'), name='uniq_virtnetwork_source_key')],
            },
        ),
    ]
