# Generated by Django 5.2.16 on 2026-08-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0018_virtualizationsource_sync_disks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsrecord',
            name='managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dnsrecord',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dnsrecord',
            name='record_type',
            field=models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('MX', 'MX'), ('TXT', 'TXT'), ('NS', 'NS'), ('SRV', 'SRV'), ('PTR', 'PTR'), ('CAA', 'CAA')], max_length=8),
        ),
    ]
