# Generated by Django 5.2.16 on 2026-08-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0019_dnsrecord_managed_alter_dnsrecord_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnszone',
            name='managed',
            field=models.BooleanField(default=False),
        ),
    ]
