# Generated by Django 5.2.16 on 2026-08-17 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_virtualswitch_uplink_interfaces'),
        ('core', '0042_tenantsettings_default_dashboard_widgets'),
        ('integrations', '0020_dnszone_managed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcpscope',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dhcp_scopes', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='dhcpscope',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dhcp_scopes', to='integrations.windowsserverconnection'),
        ),
        migrations.AddConstraint(
            model_name='dhcpscope',
            constraint=models.UniqueConstraint(condition=models.Q(('connection__isnull', True)), fields=('tenant', 'scope_id'), name='uniq_dhcpscope_local_tenant_scope'),
        ),
    ]
