# Generated by Django 5.2.16 on 2026-08-19 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_backfill_iprange_vrf'),
        ('integrations', '0021_dhcpscope_tenant_alter_dhcpscope_connection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualizationsource',
            name='last_sync_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='virtualizationsource',
            name='vrf',
            field=models.ForeignKey(blank=True, help_text='Routing context for addresses this connection discovers. NULL = Global VRF.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.vrf'),
        ),
        migrations.AddField(
            model_name='virtualizationsource',
            name='vrf_mode',
            field=models.CharField(choices=[('pinned', 'Only the chosen VRF'), ('search', 'Chosen VRF first, then any other')], default='pinned', help_text='Whether to look outside the chosen VRF when nothing there contains a discovered address.', max_length=8),
        ),
        migrations.AddField(
            model_name='windowsserverconnection',
            name='last_sync_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='windowsserverconnection',
            name='vrf',
            field=models.ForeignKey(blank=True, help_text='Routing context for addresses this connection discovers. NULL = Global VRF.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.vrf'),
        ),
        migrations.AddField(
            model_name='windowsserverconnection',
            name='vrf_mode',
            field=models.CharField(choices=[('pinned', 'Only the chosen VRF'), ('search', 'Chosen VRF first, then any other')], default='pinned', help_text='Whether to look outside the chosen VRF when nothing there contains a discovered address.', max_length=8),
        ),
    ]
