# Generated by Django 5.2.16 on 2026-08-19 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_vswitch_network_vrf'),
        ('integrations', '0022_vrf_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtnetwork',
            name='vrf',
            field=models.ForeignKey(blank=True, help_text='Routing context for addresses on this network. Leave empty to follow the virtual switch, then the sync source.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='virt_networks', to='api.vrf'),
        ),
    ]
