# Generated by Django 5.2.16 on 2026-08-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0023_vswitch_network_vrf'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualizationsource',
            name='sync_hosts',
            field=models.BooleanField(default=False),
        ),
    ]
