# Generated by Django 5.2.16 on 2026-08-19 18:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_vswitch_network_vrf'),
        ('integrations', '0024_source_sync_hosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtPlacementRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('datacenter', 'Datacenter'), ('cluster', 'Cluster'), ('folder', 'Folder'), ('host', 'Host')], max_length=12)),
                ('pattern', models.CharField(help_text='Glob such as Lab* or *-DR. Prefix with regex: for a regular expression. Folder patterns match the name or the full path.', max_length=255)),
                ('weight', models.PositiveSmallIntegerField(default=100)),
                ('location', models.ForeignKey(blank=True, help_text='Optional. Ignored unless it belongs to the site above.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virt_placement_rules', to='api.location')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virt_placement_rules', to='api.site')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_rules', to='integrations.virtualizationsource')),
            ],
            options={
                'ordering': ['weight', 'pattern'],
                'indexes': [models.Index(fields=['source', 'scope'], name='integration_source__89f614_idx')],
            },
        ),
    ]
