# Generated by Django 5.2.16 on 2026-08-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0025_placement_rules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualizationsource',
            old_name='last_sync_warnings',
            new_name='last_sync_skipped',
        ),
        migrations.RenameField(
            model_name='windowsserverconnection',
            old_name='last_sync_warnings',
            new_name='last_sync_skipped',
        ),
    ]
