# Generated by Django 5.2.16 on 2026-08-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0026_rename_sync_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtchange',
            name='kind',
            field=models.CharField(choices=[('new_guest', 'New VM on hypervisor'), ('spec_change', 'Specs changed'), ('removed_guest', 'VM removed from hypervisor'), ('iface_extra', 'Interface not on hypervisor')], max_length=16),
        ),
    ]
