# Generated by Django 5.2.16 on 2026-08-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0027_text_hyphens'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualizationsource',
            name='sync_host_hardware',
            field=models.BooleanField(default=False),
        ),
    ]
