# Generated by Django 5.2.16 on 2026-08-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0028_sync_host_hardware'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualizationsource',
            name='sync_platforms',
            field=models.BooleanField(default=False),
        ),
    ]
