# Generated by Django 5.2.16 on 2026-08-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_text_hyphens'),
        ('integrations', '0029_sync_platforms'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dnsrecord',
            index=models.Index(fields=['name'], name='integration_name_8f51d9_idx'),
        ),
    ]
