# Generated by Django 5.2.16 on 2026-08-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0030_dnsrecord_name_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtplacementrule',
            name='scope',
            field=models.CharField(choices=[('datacenter', 'Datacenter'), ('cluster', 'Cluster'), ('folder', 'Folder'), ('host', 'Host'), ('ip', 'IP address')], max_length=12),
        ),
    ]
