# Generated by Django 5.2.16 on 2026-08-20 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_text_hyphens'),
        ('integrations', '0032_virtchange_iface_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtNetworkLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='integrations.virtnetwork')),
                ('vm_interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virt_network_links', to='api.vminterface')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('network', 'vm_interface'), name='uniq_virtnetworklink_network_iface')],
            },
        ),
    ]
