# Generated by Django 5.2.16 on 2026-08-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0033_virtnetworklink'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualizationsource',
            name='last_sync_log',
            field=models.TextField(blank=True, default=''),
        ),
    ]
