# Generated by Django 5.2.16 on 2026-08-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0034_virt_last_sync_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualizationsource',
            name='sync_allowed_networks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
