# Generated by Django 5.2.16 on 2026-08-22 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_login_logo'),
        ('integrations', '0035_virtualizationsource_sync_allowed_networks'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnszone',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_dns_zones', to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='dnszone',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dns_zones', to='integrations.windowsserverconnection'),
        ),
    ]
