# Generated by Django 5.2.16 on 2026-08-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0036_local_dns_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualizationsource',
            name='match_existing_vlans',
            field=models.BooleanField(default=False),
        ),
    ]
