# Generated by Django 5.2.16 on 2026-09-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0037_match_existing_vlans'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='ai_access_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='ai_writes_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
