# Generated by Django 5.2.16 on 2026-09-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0038_integrationsettings_ai_access_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='ai_chat_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
