# Generated by Django 5.2.16 on 2026-09-10 13:42

from django.db import migrations, models


def keep_existing_behaviour(apps, schema_editor):
    """Sources that already exist keep deleting a missing VM on the first pass.

    The new default is a week's grace, which is the right default for a source
    somebody sets up tomorrow - but silently making an upgrade hold on to VMs
    for seven days is a behaviour change nobody asked for. Existing rows get
    0, and the operator raises it when they want the safety net.
    """
    apps.get_model("integrations", "VirtualizationSource").objects.update(
        auto_prune_after_days=0
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0040_split_virtualization_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtguest',
            name='missing_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualizationsource',
            name='auto_prune',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='virtualizationsource',
            name='auto_prune_after_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='virtualizationsource',
            name='skip_offline_vms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualizationsource',
            name='sync_vm_interface_mtu',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(keep_existing_behaviour, noop),
    ]
