# Generated by Django 5.2.16 on 2026-09-10 13:42

from django.db import migrations, models


def stop_deleting_and_keep_the_cadence(apps, schema_editor):
    """Existing sources stop deleting VMs, and keep proposing at today's pace.

    Two separate things, both moved in the safe direction:

    * ``auto_prune=False`` - an auto-mode source has been deleting a VM the
      hypervisor stopped reporting, with no way to say no. Danbyte does not
      delete records you did not ask it to, so that stops on upgrade; the VM
      is kept and flagged instead, and one toggle turns it back on.
    * ``auto_prune_after_days=0`` - a review-mode source proposes removal on
      the first pass that misses a guest. Making an upgrade sit on that for a
      week is a change to a workflow nobody asked to change. New sources
      still get the week.
    """
    apps.get_model("integrations", "VirtualizationSource").objects.update(
        auto_prune=False, auto_prune_after_days=0
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0040_split_virtualization_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtguest',
            name='missing_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualizationsource',
            name='auto_prune',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualizationsource',
            name='auto_prune_after_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='virtualizationsource',
            name='skip_offline_vms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualizationsource',
            name='sync_vm_interface_mtu',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(stop_deleting_and_keep_the_cadence, noop),
    ]
