# Generated by Django 5.2.16 on 2026-09-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0041_virtguest_missing_since_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='zabbix_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
