# Generated by Django 5.2.16 on 2026-09-20 19:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0173_vm_group'),
        ('integrations', '0042_integrationsettings_zabbix_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtNatLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ext_key', models.CharField(max_length=160)),
                ('created_rule', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='virtchange',
            options={'ordering': ['kind', 'guest__vmid', 'guest__ext_id']},
        ),
        migrations.AlterModelOptions(
            name='virtguest',
            options={'ordering': ['vmid', 'ext_id']},
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='virt_vcloud_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtguest',
            name='ext_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='virtualizationsource',
            name='api_version',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='virtualizationsource',
            name='api_version_used',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='virtualizationsource',
            name='sync_nat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualizationsource',
            name='sync_templates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualizationsource',
            name='sync_vm_groups',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='virtguest',
            name='vmid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='virtualizationsource',
            name='kind',
            field=models.CharField(choices=[('proxmox', 'Proxmox VE'), ('vcenter', 'VMware vCenter'), ('vcloud', 'VMware Cloud Director')], default='proxmox', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='virtguest',
            constraint=models.UniqueConstraint(condition=models.Q(('ext_id', ''), _negated=True), fields=('source', 'ext_id'), name='uniq_virtguest_source_ext_id'),
        ),
        migrations.AddField(
            model_name='virtnatlink',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virt_nat_links', to='api.natrule'),
        ),
        migrations.AddField(
            model_name='virtnatlink',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nat_links', to='integrations.virtualizationsource'),
        ),
        migrations.AddConstraint(
            model_name='virtnatlink',
            constraint=models.UniqueConstraint(fields=('source', 'ext_key'), name='uniq_virtnatlink_source_key'),
        ),
    ]
