# Generated by Django 5.2.16 on 2026-09-21 19:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0175_config_bundles'),
        ('core', '0053_faceplate_port_labels'),
        ('integrations', '0043_vcloud_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPush',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
                ('bundle', models.CharField(blank=True, default='', max_length=128)),
                ('sha256', models.CharField(max_length=64)),
                ('output', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('pushed_at', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_pushes', to='api.device')),
                ('pushed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.exporttemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_pushes', to='core.tenant')),
            ],
            options={
                'ordering': ['-pushed_at'],
                'indexes': [models.Index(fields=['device', 'path', '-pushed_at'], name='integration_device__90fd35_idx')],
            },
        ),
    ]
