# Generated by Django 5.2.16 on 2026-10-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0044_config_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsettings',
            name='virt_vcloud_enabled',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='virtguest',
            name='ext_id',
            field=models.CharField(blank=True, db_default='', default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='virtualizationsource',
            name='api_version',
            field=models.CharField(blank=True, db_default='', default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='virtualizationsource',
            name='api_version_used',
            field=models.CharField(blank=True, db_default='', default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='virtualizationsource',
            name='sync_nat',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='virtualizationsource',
            name='sync_templates',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='virtualizationsource',
            name='sync_vm_groups',
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
