# Generated by Django 5.2.16 on 2026-10-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0045_upgrade_db_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='oxidized_enabled',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
