# Generated by Django 5.2.16 on 2026-09-10 17:00

import django.db.models.deletion
import monitoring.secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0051_deploymentsettings_azure_authority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('url', models.CharField(help_text='Frontend URL, e.g. https://zabbix.example.com - the API endpoint is derived from it.', max_length=255)),
                ('credentials', monitoring.secrets.EncryptedJSONField(blank=True, default=dict)),
                ('verify_tls', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('version', models.CharField(blank=True, default='', max_length=32)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zabbix_connections', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_zabbix_conn_tenant_name')],
            },
        ),
    ]
