# Generated by Django 5.2.16 on 2026-09-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixconnection',
            name='severity_map',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
