# Generated by Django 5.2.16 on 2026-09-10 17:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0162_natrule'),
        ('core', '0051_deploymentsettings_azure_authority_and_more'),
        ('zabbix', '0002_zabbixconnection_severity_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixconnection',
            name='provision_mode',
            field=models.CharField(choices=[('off', 'Off - Danbyte writes nothing'), ('review', 'Review - propose changes for approval'), ('auto', 'Auto - apply changes')], default='off', max_length=8),
        ),
        migrations.AddField(
            model_name='zabbixconnection',
            name='prune_after_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='zabbixconnection',
            name='prune_hosts',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ZabbixChange',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('create_host', 'Create host'), ('update_host', 'Update host'), ('ambiguous', 'Needs a decision'), ('prune_host', 'Remove host')], max_length=16)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ignored', models.BooleanField(default=False)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='zabbix.zabbixconnection')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zabbix_changes', to='api.device')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zabbix_changes', to='core.tenant')),
            ],
            options={
                'ordering': ['kind', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('connection', 'device', 'kind'), name='uniq_zbx_change_conn_device_kind')],
            },
        ),
        migrations.CreateModel(
            name='ZabbixHostLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostid', models.CharField(max_length=32)),
                ('host_name', models.CharField(blank=True, default='', max_length=255)),
                ('matched_by', models.CharField(blank=True, default='', max_length=16)),
                ('created_here', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('unwanted_since', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='zabbix.zabbixconnection')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zabbix_links', to='api.device')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zabbix_links', to='core.tenant')),
            ],
            options={
                'ordering': ['host_name'],
                'constraints': [models.UniqueConstraint(fields=('connection', 'device'), name='uniq_zbx_link_conn_device'), models.UniqueConstraint(fields=('connection', 'hostid'), name='uniq_zbx_link_conn_hostid')],
            },
        ),
    ]
