# Generated by Django 5.2.16 on 2026-09-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0003_zabbixconnection_provision_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixconnection',
            name='auto_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zabbixconnection',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zabbixconnection',
            name='last_sync_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='zabbixconnection',
            name='sync_interval_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
