# Generated by Django 5.2.16 on 2026-09-10 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_deploymentsettings_azure_authority_and_more'),
        ('zabbix', '0004_zabbixconnection_auto_sync_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixconnection',
            name='send_snmp_credentials',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ZabbixTemplateRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('tenant', 'Every device'), ('role', 'Device role'), ('platform', 'Platform'), ('device_type', 'Device type'), ('manufacturer', 'Manufacturer')], max_length=16)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('templates', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_rules', to='zabbix.zabbixconnection')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zabbix_template_rules', to='core.tenant')),
            ],
            options={
                'ordering': ['scope', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('connection', 'scope', 'object_id'), name='uniq_zbx_tplrule_conn_scope_object', nulls_distinct=False)],
            },
        ),
    ]
