# Generated by Django 5.2.16 on 2026-09-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0005_template_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zabbixchange',
            name='kind',
            field=models.CharField(choices=[('create_host', 'Create host'), ('update_host', 'Update host'), ('link_template', 'Link templates'), ('ambiguous', 'Needs a decision'), ('prune_host', 'Remove host')], max_length=16),
        ),
    ]
