# Generated by Django 5.2.16 on 2026-09-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0084_engine_binding_device_scope'),
        ('zabbix', '0006_change_template_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixconnection',
            name='engines',
            field=models.ManyToManyField(blank=True, related_name='zabbix_connections', to='monitoring.monitoringengine'),
        ),
    ]
