# Generated by Django 5.2.16 on 2026-09-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0009_provision_rule_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixprovisionrule',
            name='proxy',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='zabbixprovisionrule',
            name='scope',
            field=models.CharField(choices=[('tenant', 'Every device'), ('site', 'Site'), ('role', 'Device role'), ('platform', 'Platform'), ('device_type', 'Device type'), ('manufacturer', 'Manufacturer')], max_length=16),
        ),
    ]
