# Generated by Django 5.2.16 on 2026-09-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0016_adoption_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixconnection',
            name='last_status_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zabbixconnection',
            name='read_host_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zabbixconnection',
            name='status_interval_minutes',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='zabbixhostfacts',
            name='availability',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='zabbixhostfacts',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zabbixhostfacts',
            name='maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zabbixhostfacts',
            name='problem_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zabbixhostfacts',
            name='problems',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='zabbixhostfacts',
            name='status_polled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zabbixhostfacts',
            name='worst_severity',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
