# Generated by Django 5.2.15 on 2026-06-23 11:19

import django.db.models.deletion
import django.utils.timezone
import monitoring.secrets
import taggit.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0013_ipaddress_mac_address'),
        ('core', '0002_tenant_prefs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_mode', models.CharField(choices=[('follow_global', 'Follow global schedule'), ('custom_on', 'Custom — always on'), ('custom_off', 'Custom — off')], default='follow_global', max_length=16)),
                ('overrides', models.JSONField(blank=True, default=dict, help_text='Per-assignment overrides of the template — recognised keys: interval_seconds, timeout_ms, rise, fall, params (shallow-merged).')),
                ('enabled', models.BooleanField(default=True)),
                ('apply_to_children', models.BooleanField(default=True, help_text="Prefix assignments only: also apply to child IPs in the prefix's containment tree.")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_check_assignments', to=settings.AUTH_USER_MODEL)),
                ('exclusions', models.ManyToManyField(blank=True, help_text='Child IPs to skip for a prefix assignment.', related_name='check_assignment_exclusions', to='api.ipaddress')),
                ('ip_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_assignments', to='api.ipaddress')),
                ('prefix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_assignments', to='api.prefix')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_assignments', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='User-defined custom fields')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('kind', models.CharField(choices=[('icmp', 'ICMP (ping)'), ('tcp', 'TCP port'), ('udp', 'UDP port'), ('http', 'HTTP(S)'), ('snmp', 'SNMP'), ('ssh', 'SSH'), ('telnet', 'Telnet')], max_length=8)),
                ('params', models.JSONField(blank=True, default=dict, help_text='Kind-specific, non-secret config (port, oid, path, expected_status, thresholds…). Validated per-kind.')),
                ('secret_params', monitoring.secrets.EncryptedJSONField(blank=True, default=dict, help_text='Credentials (SNMP/SSH/Telnet). Encrypted at rest; never returned by the API.')),
                ('interval_seconds', models.PositiveIntegerField(default=300, help_text='How often the check runs, in seconds.')),
                ('timeout_ms', models.PositiveIntegerField(default=2000, help_text='Per-attempt timeout in milliseconds.')),
                ('retries', models.PositiveSmallIntegerField(default=0, help_text='Immediate retries on a failed attempt before recording a failure for this run.')),
                ('rise', models.PositiveSmallIntegerField(default=1, help_text='Consecutive successes required to transition to UP.')),
                ('fall', models.PositiveSmallIntegerField(default=3, help_text='Consecutive failures required to transition to DOWN.')),
                ('degraded_enabled', models.BooleanField(default=False, help_text="Evaluate the kind's degraded criteria (latency threshold, value mismatch, unexpected HTTP code) when reachable.")),
                ('enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_check_templates', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedItem', to='core.Tag', verbose_name='Tags')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_templates', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CheckState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('icmp', 'ICMP (ping)'), ('tcp', 'TCP port'), ('udp', 'UDP port'), ('http', 'HTTP(S)'), ('snmp', 'SNMP'), ('ssh', 'SSH'), ('telnet', 'Telnet')], max_length=8)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('degraded', 'Degraded'), ('unknown', 'Unknown'), ('stale', 'Stale')], default='unknown', max_length=8)),
                ('since', models.DateTimeField(blank=True, help_text='When the current status began.', null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_latency_ms', models.FloatField(blank=True, null=True)),
                ('consecutive_success', models.PositiveIntegerField(default=0)),
                ('consecutive_fail', models.PositiveIntegerField(default=0)),
                ('next_run', models.DateTimeField(blank=True, db_index=True, help_text='Dispatcher: due when <= now.', null=True)),
                ('in_flight', models.BooleanField(default=False, help_text='Dispatcher: a run is currently enqueued/executing.')),
                ('assignment', models.ForeignKey(blank=True, help_text='The assignment that produced this effective check (may be inherited from a prefix).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='states', to='monitoring.checkassignment')),
                ('target_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_states', to='api.ipaddress')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_states', to='core.tenant')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='monitoring.checktemplate')),
            ],
            options={
                'ordering': ['target_ip', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('icmp', 'ICMP (ping)'), ('tcp', 'TCP port'), ('udp', 'UDP port'), ('http', 'HTTP(S)'), ('snmp', 'SNMP'), ('ssh', 'SSH'), ('telnet', 'Telnet')], max_length=8)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('degraded', 'Degraded'), ('unknown', 'Unknown'), ('stale', 'Stale')], max_length=8)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict, help_text='Protocol-specific payload (rtt, snmp oid/value, http code, banner, error string).')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='monitoring.checkassignment')),
                ('target_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='api.ipaddress')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='core.tenant')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='monitoring.checktemplate')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='checkassignment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='monitoring.checktemplate'),
        ),
        migrations.CreateModel(
            name='StateTransition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('icmp', 'ICMP (ping)'), ('tcp', 'TCP port'), ('udp', 'UDP port'), ('http', 'HTTP(S)'), ('snmp', 'SNMP'), ('ssh', 'SSH'), ('telnet', 'Telnet')], max_length=8)),
                ('from_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('degraded', 'Degraded'), ('unknown', 'Unknown'), ('stale', 'Stale')], max_length=8)),
                ('to_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('degraded', 'Degraded'), ('unknown', 'Unknown'), ('stale', 'Stale')], max_length=8)),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('target_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_transitions', to='api.ipaddress')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions', to='monitoring.checktemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_transitions', to='core.tenant')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.AddIndex(
            model_name='checktemplate',
            index=models.Index(fields=['tenant', 'kind'], name='monitoring__tenant__707d23_idx'),
        ),
        migrations.AddConstraint(
            model_name='checktemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_checktemplate_tenant_slug'),
        ),
        migrations.AddIndex(
            model_name='checkstate',
            index=models.Index(fields=['tenant', 'status'], name='monitoring__tenant__0b75c3_idx'),
        ),
        migrations.AddIndex(
            model_name='checkstate',
            index=models.Index(fields=['next_run', 'in_flight'], name='monitoring__next_ru_82c1d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkstate',
            constraint=models.UniqueConstraint(fields=('target_ip', 'template'), name='uniq_checkstate_target_template'),
        ),
        migrations.AddIndex(
            model_name='checkresult',
            index=models.Index(fields=['target_ip', '-timestamp'], name='monitoring__target__7f21c9_idx'),
        ),
        migrations.AddIndex(
            model_name='checkresult',
            index=models.Index(fields=['target_ip', 'template', '-timestamp'], name='monitoring__target__37c838_idx'),
        ),
        migrations.AddIndex(
            model_name='checkresult',
            index=models.Index(fields=['tenant', '-timestamp'], name='monitoring__tenant__257383_idx'),
        ),
        migrations.AddIndex(
            model_name='checkassignment',
            index=models.Index(fields=['tenant'], name='monitoring__tenant__5a88ee_idx'),
        ),
        migrations.AddIndex(
            model_name='checkassignment',
            index=models.Index(fields=['ip_address'], name='monitoring__ip_addr_7e6d37_idx'),
        ),
        migrations.AddIndex(
            model_name='checkassignment',
            index=models.Index(fields=['prefix'], name='monitoring__prefix__50c1d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ip_address__isnull', False), ('prefix__isnull', True)), models.Q(('ip_address__isnull', True), ('prefix__isnull', False)), _connector='OR'), name='checkassignment_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='checkassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('ip_address__isnull', False)), fields=('template', 'ip_address'), name='uniq_assignment_template_ip'),
        ),
        migrations.AddConstraint(
            model_name='checkassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('prefix__isnull', False)), fields=('template', 'prefix'), name='uniq_assignment_template_prefix'),
        ),
        migrations.AddIndex(
            model_name='statetransition',
            index=models.Index(fields=['target_ip', '-at'], name='monitoring__target__ac2ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='statetransition',
            index=models.Index(fields=['tenant', '-at'], name='monitoring__tenant__6a0d7d_idx'),
        ),
    ]
