# Generated by Django 5.2.15 on 2026-06-23 12:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_ipaddress_mac_address'),
        ('core', '0002_tenant_prefs'),
        ('monitoring', '0002_notificationchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkresult',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('degraded', 'Degraded'), ('unknown', 'Unknown'), ('stale', 'Stale'), ('skipped', 'Skipped')], max_length=8),
        ),
        migrations.AlterField(
            model_name='checkstate',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('degraded', 'Degraded'), ('unknown', 'Unknown'), ('stale', 'Stale'), ('skipped', 'Skipped')], default='unknown', max_length=8),
        ),
        migrations.AlterField(
            model_name='statetransition',
            name='from_status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('degraded', 'Degraded'), ('unknown', 'Unknown'), ('stale', 'Stale'), ('skipped', 'Skipped')], max_length=8),
        ),
        migrations.AlterField(
            model_name='statetransition',
            name='to_status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('degraded', 'Degraded'), ('unknown', 'Unknown'), ('stale', 'Stale'), ('skipped', 'Skipped')], max_length=8),
        ),
        migrations.CreateModel(
            name='MonitoringSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('global_enabled', models.BooleanField(default=True, help_text="Master switch that 'follow global' assignments obey.")),
                ('default_interval_seconds', models.PositiveIntegerField(default=300, help_text='Interval new checks inherit by default.')),
                ('stale_after_scans', models.PositiveSmallIntegerField(default=10, help_text='Consecutive failed checks before a down IP is marked stale (0 = never by scan count).')),
                ('stale_after_days', models.PositiveSmallIntegerField(default=0, help_text='Days continuously down before a down IP is marked stale (0 = never by time).')),
                ('skip_ip_statuses', models.ManyToManyField(blank=True, help_text='IPs whose status is one of these are skipped (not checked).', related_name='monitoring_skip_settings', to='api.ipstatus')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_settings', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Monitoring settings',
                'verbose_name_plural': 'Monitoring settings',
            },
        ),
    ]
