# Generated by Django 5.2.15 on 2026-06-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_checkresult_status_alter_checkstate_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsettings',
            name='dns_clear_on_missing',
            field=models.BooleanField(default=False, help_text='Clear dns_name when the PTR lookup returns nothing.'),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='dns_preserve_if_alive',
            field=models.BooleanField(default=True, help_text='Keep the existing dns_name on a failed lookup if the IP is currently up (transient DNS blip vs. a real removal).'),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='dns_sync_enabled',
            field=models.BooleanField(default=False, help_text="Resolve reverse DNS (PTR) for monitored IPs and store it as the IP's dns_name."),
        ),
    ]
