# Generated by Django 5.2.15 on 2026-06-23 14:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_ipaddress_last_seen'),
        ('core', '0002_tenant_prefs'),
        ('monitoring', '0004_monitoringsettings_dns_clear_on_missing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('icmp', 'ICMP (ping)'), ('tcp', 'TCP port'), ('udp', 'UDP port'), ('http', 'HTTP(S)'), ('snmp', 'SNMP'), ('ssh', 'SSH'), ('telnet', 'Telnet')], max_length=8)),
                ('dedup_key', models.CharField(help_text='Stable key for the alerting condition — (IP, check). One firing alert per key.', max_length=120)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=8)),
                ('status', models.CharField(choices=[('firing', 'Firing'), ('resolved', 'Resolved')], default='firing', max_length=8)),
                ('check_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('degraded', 'Degraded'), ('unknown', 'Unknown'), ('stale', 'Stale'), ('skipped', 'Skipped')], help_text='The bad status that opened/sustains this alert.', max_length=8)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_status_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('target_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.ipaddress')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.checktemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.tenant')),
            ],
            options={
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='monitoring__tenant__c3d871_idx'), models.Index(fields=['tenant', 'severity', 'status'], name='monitoring__tenant__6d352d_idx'), models.Index(fields=['dedup_key', 'status'], name='monitoring__dedup_k_ab27bf_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'firing')), fields=('tenant', 'dedup_key'), name='uniq_firing_alert_per_key')],
            },
        ),
    ]
