# Generated by Django 5.2.15 on 2026-06-23 15:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_ipaddress_last_seen'),
        ('core', '0002_tenant_prefs'),
        ('monitoring', '0005_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('weight', models.PositiveIntegerField(default=100, help_text='Lower weights match first.')),
                ('match_kinds', models.JSONField(blank=True, default=list, help_text='Check kinds this rule covers.')),
                ('match_statuses', models.JSONField(blank=True, default=list, help_text='Bad statuses that trigger this rule (down/stale/degraded).')),
                ('match_tag_slugs', models.JSONField(blank=True, default=list, help_text='Only IPs carrying any of these tag slugs.')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=8)),
                ('match_prefix', models.ForeignKey(blank=True, help_text='Only IPs inside this prefix.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='api.prefix')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='core.tenant')),
            ],
            options={
                'ordering': ['weight', 'name'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='rule',
            field=models.ForeignKey(blank=True, help_text="The rule that set this alert's severity (null = default policy).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.alertrule'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['tenant', 'enabled', 'weight'], name='monitoring__tenant__cb181d_idx'),
        ),
    ]
