# Generated by Django 5.2.15 on 2026-06-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alertrule_alert_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationchannel',
            name='min_severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='info', help_text='Only alerts at or above this severity reach this channel.', max_length=8),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='kind',
            field=models.CharField(choices=[('webhook', 'Webhook'), ('email', 'Email'), ('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('discord', 'Discord'), ('pagerduty', 'PagerDuty')], max_length=12),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='on_statuses',
            field=models.JSONField(blank=True, default=list, help_text='Only notify on alerts in these check statuses; empty = all.'),
        ),
    ]
