# Generated by Django 5.2.15 on 2026-06-23 16:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_ipaddress_last_seen'),
        ('core', '0003_deploymentsettings'),
        ('monitoring', '0007_notificationchannel_min_severity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='ack_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Silence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('match_kinds', models.JSONField(blank=True, default=list)),
                ('match_statuses', models.JSONField(blank=True, default=list)),
                ('match_tag_slugs', models.JSONField(blank=True, default=list)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_silences', to=settings.AUTH_USER_MODEL)),
                ('match_ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silences', to='api.ipaddress')),
                ('match_prefix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silences', to='api.prefix')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silences', to='core.tenant')),
            ],
            options={
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['tenant', 'starts_at', 'ends_at'], name='monitoring__tenant__fa8e7b_idx')],
            },
        ),
    ]
