# Generated by Django 5.2.15 on 2026-06-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_alert_ack_note_alert_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkstate',
            name='in_flight_since',
            field=models.DateTimeField(blank=True, help_text='When the current run was claimed. Lets the reaper reclaim states orphaned by a dead/restarted worker.', null=True),
        ),
    ]
