# Generated by Django 5.2.15 on 2026-06-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_checkstate_in_flight_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='escalated',
            field=models.BooleanField(default=False, help_text='Bumped to critical after firing unacked past the threshold.'),
        ),
        migrations.AddField(
            model_name='alert',
            name='flapping',
            field=models.BooleanField(default=False, help_text='Condition is opening/clearing repeatedly — renotify is paused.'),
        ),
        migrations.AddField(
            model_name='alert',
            name='notify_count',
            field=models.PositiveIntegerField(default=0, help_text='How many times this alert has been notified.'),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='escalate_after_minutes',
            field=models.PositiveIntegerField(default=120, help_text='Minutes a firing, unacked alert waits before escalating to critical.'),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='escalate_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='flap_threshold',
            field=models.PositiveSmallIntegerField(default=5, help_text='Opens within the flap window before an alert is marked flapping (0 = disable flap detection).'),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='flap_window_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Window for counting flaps.'),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='group_notifications',
            field=models.BooleanField(default=True, help_text='Coalesce a burst of new alerts into one grouped notification.'),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='group_threshold',
            field=models.PositiveSmallIntegerField(default=3, help_text="New alerts in one scan batch before they're grouped into a digest."),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='renotify_enabled',
            field=models.BooleanField(default=False, help_text='Re-send a reminder for alerts still firing and unacknowledged.'),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='renotify_interval_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Minutes between renotifications of a firing alert.'),
        ),
    ]
