# Generated by Django 5.2.15 on 2026-06-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_alter_alert_kind_alter_checkresult_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsettings',
            name='cleanup_after_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Days a discovered IP must be unseen before cleanup removes it.'),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='cleanup_enabled',
            field=models.BooleanField(default=False, help_text='Delete discovered IPs unreachable for longer than the grace period.'),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='discovery_enabled',
            field=models.BooleanField(default=False, help_text='Master switch for periodic subnet discovery (per-prefix opt-in).'),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='discovery_min_prefix_length',
            field=models.PositiveSmallIntegerField(default=22, help_text='Smallest prefix length (largest subnet) discovery will sweep. 22 = up to /22 (~1k hosts); guards against scanning huge ranges.'),
        ),
    ]
