# Generated by Django 5.2.15 on 2026-06-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_ipaddress_flap_exclude'),
        ('monitoring', '0012_monitoringsettings_cleanup_after_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsettings',
            name='flap_exclude_ip_statuses',
            field=models.ManyToManyField(blank=True, help_text='IPs with these statuses are never flagged as flapping (e.g. DHCP scopes).', related_name='monitoring_flap_exclude_settings', to='api.ipstatus'),
        ),
    ]
