# Generated by Django 5.2.15 on 2026-06-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_monitoringsettings_flap_exclude_ip_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsettings',
            name='discovery_interval_minutes',
            field=models.PositiveIntegerField(default=30, help_text='How often each auto-discover prefix is re-swept, in minutes.'),
        ),
    ]
