# Generated by Django 5.2.15 on 2026-06-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_monitoringsettings_discovery_interval_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsettings',
            name='discovery_all_prefixes',
            field=models.BooleanField(default=False, help_text='Auto-discover every prefix by default (no per-prefix opt-in needed). Per-prefix auto_discover still enrols a subnet + its children.'),
        ),
    ]
