# Generated by Django 5.2.15 on 2026-06-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_unified_status'),
        ('monitoring', '0015_monitoringsettings_discovery_all_prefixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringsettings',
            name='flap_exclude_ip_statuses',
            field=models.ManyToManyField(blank=True, help_text='IPs with these statuses are never flagged as flapping (e.g. DHCP scopes).', related_name='monitoring_flap_exclude_settings', to='api.status'),
        ),
        migrations.AlterField(
            model_name='monitoringsettings',
            name='skip_ip_statuses',
            field=models.ManyToManyField(blank=True, help_text='IPs whose status is one of these are skipped (not checked).', related_name='monitoring_skip_settings', to='api.status'),
        ),
    ]
