# Generated by Django 5.2.15 on 2026-06-30 16:18

import django.db.models.deletion
import monitoring.secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_unified_status"),
        ("core", "0009_deploymentsettings_device_field_visibility"),
        (
            "monitoring",
            "0016_alter_monitoringsettings_flap_exclude_ip_statuses_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SnmpProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120)),
                (
                    "version",
                    models.CharField(
                        choices=[("v1", "v1"), ("v2c", "v2c"), ("v3", "v3")],
                        default="v2c",
                        max_length=4,
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Non-secret SNMP config: port, and for v3 username / auth_proto / priv_proto.",
                    ),
                ),
                (
                    "secret_params",
                    monitoring.secrets.EncryptedJSONField(
                        blank=True,
                        default=dict,
                        help_text="Credentials — v2c community, or v3 auth_key / priv_key. Encrypted at rest; never returned by the API.",
                    ),
                ),
                ("timeout_ms", models.PositiveIntegerField(default=2000)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Used when a device poll does not name a profile.",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snmp_profiles",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceSnmp",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Observed system facts (sys_name, sys_descr, sys_uptime, …).",
                    ),
                ),
                ("reachable", models.BooleanField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("polled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snmp",
                        to="api.device",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_snmp",
                        to="core.tenant",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_states",
                        to="monitoring.snmpprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-polled_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="snmpprofile",
            constraint=models.UniqueConstraint(
                fields=("tenant", "slug"), name="uniq_snmpprofile_tenant_slug"
            ),
        ),
    ]
