# Generated by Django 5.2.15 on 2026-06-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0017_snmpprofile_devicesnmp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicesnmp",
            name="interfaces",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Observed interfaces from ifTable/ifXTable (per-ifIndex dicts).",
            ),
        ),
    ]
