# Generated by Django 5.2.15 on 2026-06-30 16:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_deploymentsettings_device_field_visibility"),
        ("monitoring", "0018_devicesnmp_interfaces"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnmpProfileBinding",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("device", "Device"),
                            ("device_role", "Device role"),
                            ("device_type", "Device type"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "object_id",
                    models.UUIDField(help_text="id of the device / role / type."),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bindings",
                        to="monitoring.snmpprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snmp_bindings",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "scope", "object_id"],
                        name="monitoring__tenant__7b3b9a_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "scope", "object_id"),
                        name="uniq_snmpbinding_scope_object",
                    )
                ],
            },
        ),
    ]
