# Generated by Django 5.2.15 on 2026-06-30 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_unified_status"),
        ("core", "0009_deploymentsettings_device_field_visibility"),
        ("monitoring", "0019_snmpprofilebinding"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnmpInterfaceSample",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("if_index", models.CharField(max_length=32)),
                ("in_octets", models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ("out_octets", models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ("speed_mbps", models.PositiveIntegerField(default=0)),
                ("sampled_at", models.DateTimeField()),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snmp_samples",
                        to="api.device",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snmp_samples",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["sampled_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "if_index", "sampled_at"],
                        name="monitoring__device__fc46a7_idx",
                    )
                ],
            },
        ),
    ]
