# Generated by Django 5.2.15 on 2026-06-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0020_snmpinterfacesample"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicesnmp",
            name="arp",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="ARP table: [{ip, mac, if_index}] from ipNetToMediaTable.",
            ),
        ),
        migrations.AddField(
            model_name="devicesnmp",
            name="neighbors",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="LLDP neighbours: [{local_port, remote_device, remote_port}].",
            ),
        ),
    ]
