# Generated by Django 5.2.15 on 2026-07-06 09:34

import django.db.models.deletion
import monitoring.secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tenantgroup_tenant_group'),
        ('monitoring', '0021_devicesnmp_arp_devicesnmp_neighbors'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringEngine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('local', 'Local (built-in)'), ('remote', 'Outpost')], default='remote', max_length=6)),
                ('enabled', models.BooleanField(default=True)),
                ('token', monitoring.secrets.EncryptedJSONField(blank=True, default=dict, help_text='Outpost auth token (remote engines); {} until enrolled.')),
                ('poll_interval_seconds', models.PositiveIntegerField(default=15, help_text='How often the Outpost polls the core for work.')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('agent_version', models.CharField(blank=True, max_length=40)),
                ('agent_hostname', models.CharField(blank=True, max_length=255)),
                ('agent_ip', models.CharField(blank=True, max_length=45)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_engines', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='checkstate',
            name='engine',
            field=models.ForeignKey(blank=True, help_text="Which engine runs this check — resolved from the target's site/location at materialise time (null = the tenant's local engine).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_states', to='monitoring.monitoringengine'),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='default_engine',
            field=models.ForeignKey(blank=True, help_text='Default monitoring engine for targets with no site/location engine assigned (null = the local built-in engine).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_settings', to='monitoring.monitoringengine'),
        ),
        migrations.CreateModel(
            name='MonitoringEngineBinding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('site', 'Site'), ('location', 'Location')], max_length=16)),
                ('object_id', models.UUIDField(help_text='id of the site / location.')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='monitoring.monitoringengine')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_bindings', to='core.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='monitoringengine',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_monitoringengine_tenant_slug'),
        ),
        migrations.AddConstraint(
            model_name='monitoringengine',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'local')), fields=('tenant',), name='uniq_local_engine_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='monitoringenginebinding',
            index=models.Index(fields=['tenant', 'scope', 'object_id'], name='monitoring__tenant__6eb4f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='monitoringenginebinding',
            constraint=models.UniqueConstraint(fields=('tenant', 'scope', 'object_id'), name='uniq_enginebinding_scope_object'),
        ),
    ]
