# Generated by Django 5.2.15 on 2026-07-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0022_monitoringengine_checkstate_engine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringengine',
            name='transport',
            field=models.CharField(choices=[('pull', 'Outpost dials out (HTTPS 443)'), ('ssh', 'Danbyte dials in (SSH 22)')], default='pull', max_length=8),
        ),
    ]
