# Generated by Django 5.2.15 on 2026-07-06 11:11

import monitoring.secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0023_monitoringengine_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringengine',
            name='ssh_credential',
            field=monitoring.secrets.EncryptedJSONField(blank=True, default=dict, help_text='SSH key/password for the SSH transport; {} until set.'),
        ),
        migrations.AddField(
            model_name='monitoringengine',
            name='ssh_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='monitoringengine',
            name='ssh_port',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='monitoringengine',
            name='ssh_user',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
