# Generated by Django 5.2.15 on 2026-07-06 11:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0024_monitoringengine_ssh_credential_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutpostRelease',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=64, unique=True)),
                ('source', models.CharField(choices=[('file', 'Uploaded file'), ('git', 'Git repository')], default='file', max_length=4)),
                ('artifact', models.FileField(blank=True, upload_to='outpost-releases/')),
                ('git_url', models.CharField(blank=True, max_length=512)),
                ('git_ref', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
