# Generated by Django 5.2.15 on 2026-07-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0025_outpostrelease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snmpprofilebinding',
            name='scope',
            field=models.CharField(choices=[('device', 'Device'), ('device_role', 'Device role'), ('device_type', 'Device type'), ('location', 'Location'), ('site', 'Site')], max_length=16),
        ),
    ]
