# Generated by Django 5.2.15 on 2026-07-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0026_alter_snmpprofilebinding_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringengine',
            name='ssh_host_key',
            field=models.TextField(blank=True),
        ),
    ]
