# Generated by Django 5.2.15 on 2026-07-06 13:02

import monitoring.secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0027_monitoringengine_ssh_host_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsettings',
            name='outpost_repo_token',
            field=monitoring.secrets.EncryptedJSONField(blank=True, default=dict, help_text='Optional GitHub token for a private Outpost repo; {} if none.'),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='outpost_repo_url',
            field=models.CharField(blank=True, help_text='GitHub repo of the Outpost agent, e.g. https://github.com/you/danbyte-outpost.', max_length=512),
        ),
    ]
