# Generated by Django 5.2.15 on 2026-07-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0028_monitoringsettings_outpost_repo_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringengine',
            name='auto_update',
            field=models.BooleanField(default=False),
        ),
    ]
