# Generated by Django 5.2.15 on 2026-07-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0029_monitoringengine_auto_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringengine',
            name='sweep_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
