# Generated by Django 5.2.15 on 2026-07-08 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_remove_frontport_uniq_frontport_rear_position_and_more'),
        ('core', '0013_alter_bookmark_options_bookmark_weight_and_more'),
        ('monitoring', '0030_monitoringengine_sweep_requested_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('templates', models.ManyToManyField(blank=True, related_name='monitoring_profiles', to='monitoring.checktemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_profiles', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('vrf', 'VRF'), ('device_type', 'Device type'), ('device_role', 'Device role'), ('device', 'Device'), ('prefix', 'Prefix')], max_length=24)),
                ('enabled', models.BooleanField(default=True)),
                ('inherit', models.BooleanField(default=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_policies', to='api.device')),
                ('device_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_policies', to='api.devicerole')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_policies', to='api.devicetype')),
                ('prefix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_policies', to='api.prefix')),
                ('templates', models.ManyToManyField(blank=True, related_name='monitoring_policies', to='monitoring.checktemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_policies', to='core.tenant')),
                ('vrf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_policies', to='api.vrf')),
                ('profiles', models.ManyToManyField(blank=True, related_name='policies', to='monitoring.monitoringprofile')),
            ],
            options={
                'ordering': ['scope', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringDenySubnet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cidr', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_deny_subnets', to='core.tenant')),
                ('vrf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_deny_subnets', to='api.vrf')),
            ],
            options={
                'ordering': ['cidr'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'vrf', 'cidr'), name='uniq_monitoringdeny_vrf_cidr')],
            },
        ),
        migrations.AddConstraint(
            model_name='monitoringprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_monitoringprofile_tenant_slug'),
        ),
        migrations.AddConstraint(
            model_name='monitoringpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('vrf__isnull', False)), fields=('tenant', 'scope', 'vrf'), name='uniq_monitoringpolicy_vrf'),
        ),
        migrations.AddConstraint(
            model_name='monitoringpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('device_type__isnull', False)), fields=('tenant', 'scope', 'device_type'), name='uniq_monitoringpolicy_device_type'),
        ),
        migrations.AddConstraint(
            model_name='monitoringpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('device_role__isnull', False)), fields=('tenant', 'scope', 'device_role'), name='uniq_monitoringpolicy_device_role'),
        ),
        migrations.AddConstraint(
            model_name='monitoringpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('device__isnull', False)), fields=('tenant', 'scope', 'device'), name='uniq_monitoringpolicy_device'),
        ),
        migrations.AddConstraint(
            model_name='monitoringpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('prefix__isnull', False)), fields=('tenant', 'scope', 'prefix'), name='uniq_monitoringpolicy_prefix'),
        ),
    ]
