# Generated by Django 5.2.15 on 2026-07-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0031_monitoringprofile_monitoringpolicy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringenginebinding',
            name='scope',
            field=models.CharField(choices=[('site', 'Site'), ('location', 'Location'), ('prefix', 'Prefix')], max_length=16),
        ),
    ]
