# Generated by Django 5.2.15 on 2026-07-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0032_alter_monitoringenginebinding_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkstate',
            name='interval_seconds',
            field=models.PositiveIntegerField(blank=True, help_text="Resolved per-target frequency override for policy-sourced checks (from the most-specific MonitoringPolicy that sets one). Null = use the tenant's global default. Assignment-sourced checks ignore this and follow their own schedule.", null=True),
        ),
        migrations.AddField(
            model_name='monitoringpolicy',
            name='interval_seconds',
            field=models.PositiveIntegerField(blank=True, help_text="Per-scope check frequency override, in seconds. Null = use the tenant's global default interval. The most-specific policy that sets it wins (a prefix beats the VRF beats global).", null=True),
        ),
    ]
