# Generated by Django 5.2.15 on 2026-07-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0033_checkstate_interval_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringpolicy',
            name='target',
            field=models.CharField(choices=[('all', 'All IPs'), ('interfaces', 'Interface IPs'), ('primary', 'Primary IP'), ('oob', 'OOB / management IP')], default='all', help_text="For device/type/role scopes: which of the device's IPs the policy's checks run against. Ignored for global/vrf/prefix scopes.", max_length=16),
        ),
    ]
