# Generated by Django 5.2.15 on 2026-07-11 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_seed_not_connected_cable_status'),
        ('core', '0013_alter_bookmark_options_bookmark_weight_and_more'),
        ('monitoring', '0034_monitoringpolicy_target'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='checkresult',
            name='monitoring__target__37c838_idx',
        ),
        migrations.AlterField(
            model_name='checkresult',
            name='target_ip',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='api.ipaddress'),
        ),
        migrations.AlterField(
            model_name='checkresult',
            name='tenant',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='core.tenant'),
        ),
    ]
