# Generated by Django 5.2.15 on 2026-07-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0035_remove_checkresult_monitoring__target__37c838_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringengine',
            name='stale_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
