# Generated by Django 5.2.15 on 2026-07-11 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_service_monitored_devicetypeservice'),
        ('monitoring', '0036_monitoringengine_stale_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkassignment',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Set when this assignment was spawned by a monitored Service, so it can be reconciled/torn down with the service. NULL = a manual assignment, never auto-removed.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_assignments', to='api.service'),
        ),
    ]
