# Generated by Django 5.2.15 on 2026-07-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0037_checkassignment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringsettings',
            name='outpost_repo_url',
            field=models.CharField(blank=True, help_text='GitHub repo of the Outpost agent, e.g. https://github.com/danbyte-net/danbyte-outpost.', max_length=512),
        ),
    ]
