# Generated by Django 5.2.15 on 2026-07-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0038_alter_monitoringsettings_outpost_repo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('icmp', 'ICMP (ping)'), ('tcp', 'TCP port'), ('udp', 'UDP port'), ('http', 'HTTP(S)'), ('snmp', 'SNMP'), ('ssh', 'SSH'), ('telnet', 'Telnet'), ('exec', 'Script / exec')], max_length=32),
        ),
        migrations.AlterField(
            model_name='checkresult',
            name='kind',
            field=models.CharField(choices=[('icmp', 'ICMP (ping)'), ('tcp', 'TCP port'), ('udp', 'UDP port'), ('http', 'HTTP(S)'), ('snmp', 'SNMP'), ('ssh', 'SSH'), ('telnet', 'Telnet'), ('exec', 'Script / exec')], max_length=32),
        ),
        migrations.AlterField(
            model_name='checkstate',
            name='kind',
            field=models.CharField(choices=[('icmp', 'ICMP (ping)'), ('tcp', 'TCP port'), ('udp', 'UDP port'), ('http', 'HTTP(S)'), ('snmp', 'SNMP'), ('ssh', 'SSH'), ('telnet', 'Telnet'), ('exec', 'Script / exec')], max_length=32),
        ),
        migrations.AlterField(
            model_name='checktemplate',
            name='kind',
            field=models.CharField(choices=[('icmp', 'ICMP (ping)'), ('tcp', 'TCP port'), ('udp', 'UDP port'), ('http', 'HTTP(S)'), ('snmp', 'SNMP'), ('ssh', 'SSH'), ('telnet', 'Telnet'), ('exec', 'Script / exec')], max_length=32),
        ),
        migrations.AlterField(
            model_name='statetransition',
            name='kind',
            field=models.CharField(choices=[('icmp', 'ICMP (ping)'), ('tcp', 'TCP port'), ('udp', 'UDP port'), ('http', 'HTTP(S)'), ('snmp', 'SNMP'), ('ssh', 'SSH'), ('telnet', 'Telnet'), ('exec', 'Script / exec')], max_length=32),
        ),
    ]
