# Generated by Django 5.2.15 on 2026-07-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0039_alter_alert_kind_alter_checkresult_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesnmp',
            name='fdb',
            field=models.JSONField(blank=True, default=list, help_text='MAC-address table: [{mac, if_index}] from the bridge forwarding table (dot1dTpFdbPort + dot1dBasePortIfIndex).'),
        ),
    ]
