# Generated by Django 5.2.15 on 2026-07-24 13:58

import django.db.models.deletion
import monitoring.secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_natural_sort_collation'),
        ('core', '0031_deploymentsettings_rq_workers'),
        ('monitoring', '0040_devicesnmp_fdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedfishEndpoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(help_text='BMC address (IP or hostname).', max_length=255)),
                ('port', models.PositiveIntegerField(default=443)),
                ('verify_tls', models.BooleanField(default=False, help_text='BMCs almost always present self-signed certificates; enable only when yours carry a trusted chain.')),
                ('secret_params', monitoring.secrets.EncryptedJSONField(blank=True, default=dict, help_text='BMC credentials: {username, password}. Encrypted at rest; never returned by the API.')),
                ('enabled', models.BooleanField(default=True)),
                ('timeout_ms', models.PositiveIntegerField(default=8000)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Observed hardware: {drives: [...], processors: [...], memory: [...], psus: [...], fans: [...], system: {...}}.')),
                ('reachable', models.BooleanField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('polled_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redfish', to='api.device')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redfish_endpoints', to='core.tenant')),
            ],
            options={
                'ordering': ['device__name'],
            },
        ),
    ]
