# Generated by Django 5.2.15 on 2026-07-24 14:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_natural_sort_collation'),
        ('core', '0031_deploymentsettings_rq_workers'),
        ('monitoring', '0041_redfishendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesnmp',
            name='sensors',
            field=models.JSONField(blank=True, default=list, help_text='Last custom-sensor readings: [{sensor, name, raw, status}].'),
        ),
        migrations.CreateModel(
            name='SnmpSensor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('oid', models.CharField(help_text='Numeric OID — a table column base to WALK, or a scalar to GET.', max_length=255)),
                ('walk', models.BooleanField(default=True, help_text='Walk a table column (one reading per component) vs GET a single scalar.')),
                ('item_kind', models.CharField(choices=[('disk', 'Disk'), ('cpu', 'CPU'), ('ram', 'RAM'), ('psu', 'PSU'), ('fan', 'Fan'), ('gpu', 'GPU'), ('controller', 'Controller'), ('other', 'Other')], default='disk', max_length=16)),
                ('name_template', models.CharField(default='{kind} {index}', help_text='How each reading names/matches its inventory item; {index} = the walk index, {kind} = the item kind.', max_length=128)),
                ('value_map', models.JSONField(blank=True, default=dict, help_text='Raw SNMP value → status slug, e.g. {"3": "active", "4": "failed"}. Unmapped values leave the status unchanged.')),
                ('enabled', models.BooleanField(default=True)),
                ('device_type', models.ForeignKey(blank=True, help_text='Limit to one device type; blank applies to all.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snmp_sensors', to='api.devicetype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_sensors', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_snmpsensor_tenant_slug')],
            },
        ),
    ]
