# Generated by Django 5.2.15 on 2026-07-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0042_devicesnmp_sensors_snmpsensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='snmpprofilebinding',
            name='target',
            field=models.CharField(blank=True, default='', help_text="Poll this address instead of the device's own IPs (device scope only) — e.g. a BMC or a management address the agent listens on. Blank resolves management IP → primary IP → resolvable name.", max_length=255),
        ),
    ]
