# Generated by Django 5.2.15 on 2026-07-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0043_snmpprofilebinding_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='snmpsensor',
            name='absent_status',
            field=models.CharField(blank=True, default='', help_text="Status slug for items this sensor covers but the agent never reported — the empty bays a chassis template stamped. Blank leaves them alone. Only applied after a poll that actually returned readings, so a timeout can't mark real hardware missing.", max_length=64),
        ),
    ]
