# Generated by Django 5.2.15 on 2026-07-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0044_snmpsensor_absent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='snmpsensor',
            name='apply_mode',
            field=models.CharField(choices=[('drift', 'Surface as drift — you accept it'), ('auto', 'Apply automatically')], default='drift', help_text="What a reading does to the source of truth. 'drift' keeps readings observed-only and lists the difference for review — Danbyte's normal contract, and the only mode that can't overwrite a status you set. 'auto' writes straight through, for health you want acted on with no one watching.", max_length=8),
        ),
    ]
