# Generated by Django 5.2.15 on 2026-07-28 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_deploymentsettings_rq_workers'),
        ('monitoring', '0045_snmpsensor_apply_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('icmp', 'ICMP (ping)'), ('tcp', 'TCP port'), ('udp', 'UDP port'), ('http', 'HTTP(S)'), ('snmp', 'SNMP'), ('ssh', 'SSH'), ('telnet', 'Telnet'), ('exec', 'Script / exec'), ('tls_cert', 'TLS certificate')], max_length=32),
        ),
        migrations.AlterField(
            model_name='checkresult',
            name='kind',
            field=models.CharField(choices=[('icmp', 'ICMP (ping)'), ('tcp', 'TCP port'), ('udp', 'UDP port'), ('http', 'HTTP(S)'), ('snmp', 'SNMP'), ('ssh', 'SSH'), ('telnet', 'Telnet'), ('exec', 'Script / exec'), ('tls_cert', 'TLS certificate')], max_length=32),
        ),
        migrations.AlterField(
            model_name='checkstate',
            name='kind',
            field=models.CharField(choices=[('icmp', 'ICMP (ping)'), ('tcp', 'TCP port'), ('udp', 'UDP port'), ('http', 'HTTP(S)'), ('snmp', 'SNMP'), ('ssh', 'SSH'), ('telnet', 'Telnet'), ('exec', 'Script / exec'), ('tls_cert', 'TLS certificate')], max_length=32),
        ),
        migrations.AlterField(
            model_name='checktemplate',
            name='kind',
            field=models.CharField(choices=[('icmp', 'ICMP (ping)'), ('tcp', 'TCP port'), ('udp', 'UDP port'), ('http', 'HTTP(S)'), ('snmp', 'SNMP'), ('ssh', 'SSH'), ('telnet', 'Telnet'), ('exec', 'Script / exec'), ('tls_cert', 'TLS certificate')], max_length=32),
        ),
        migrations.AlterField(
            model_name='statetransition',
            name='kind',
            field=models.CharField(choices=[('icmp', 'ICMP (ping)'), ('tcp', 'TCP port'), ('udp', 'UDP port'), ('http', 'HTTP(S)'), ('snmp', 'SNMP'), ('ssh', 'SSH'), ('telnet', 'Telnet'), ('exec', 'Script / exec'), ('tls_cert', 'TLS certificate')], max_length=32),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint_sha256', models.CharField(help_text='SHA-256 of the DER encoding, lowercase hex. The identity of the certificate — the same cert seen anywhere is this same row.', max_length=64)),
                ('subject', models.CharField(blank=True, default='', max_length=1024)),
                ('subject_cn', models.CharField(blank=True, default='', max_length=255)),
                ('issuer', models.CharField(blank=True, default='', max_length=1024)),
                ('issuer_cn', models.CharField(blank=True, default='', max_length=255)),
                ('serial', models.CharField(blank=True, default='', help_text='Certificate serial number, lowercase hex.', max_length=128)),
                ('san_dns', models.JSONField(blank=True, default=list, help_text='dNSName subject alternative names, e.g. ["example.com", "*.example.com"].')),
                ('san_ip', models.JSONField(blank=True, default=list, help_text='iPAddress subject alternative names, as strings.')),
                ('not_before', models.DateTimeField()),
                ('not_after', models.DateTimeField(db_index=True)),
                ('public_key_algorithm', models.CharField(choices=[('rsa', 'RSA'), ('ec', 'ECDSA'), ('ed25519', 'Ed25519'), ('ed448', 'Ed448'), ('dsa', 'DSA'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('public_key_bits', models.PositiveIntegerField(blank=True, null=True)),
                ('signature_algorithm', models.CharField(blank=True, default='', max_length=64)),
                ('chain_depth', models.PositiveSmallIntegerField(default=0, help_text='Position in the presented chain when last observed — 0 is the end-entity (leaf) certificate, 1 its issuer, and so on.')),
                ('self_signed', models.BooleanField(default=False)),
                ('chain_verified', models.BooleanField(blank=True, help_text='Did the chain this certificate arrived in validate against the trust store? NULL = not known. Recorded, never enforced — Danbyte reports trust, it does not become one.', null=True)),
                ('last_seen', models.DateTimeField(blank=True, help_text='Most recent observation. ``created_at`` is the first.', null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.tenant')),
            ],
            options={
                'ordering': ['not_after', 'subject_cn'],
                'indexes': [models.Index(fields=['tenant', 'not_after'], name='monitoring__tenant__acd685_idx'), models.Index(fields=['tenant', 'subject_cn'], name='monitoring__tenant__95c315_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'fingerprint_sha256'), name='uniq_certificate_tenant_fingerprint')],
            },
        ),
    ]
