# Generated by Django 5.2.15 on 2026-07-28 15:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_site_time_zone'),
        ('core', '0031_deploymentsettings_rq_workers'),
        ('monitoring', '0046_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='chain_depth',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='chain_verified',
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='cert_binding_stale_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Days without observing an endpoint before its binding counts as stale. A stale binding stops alerting — nobody is served by a certificate we can no longer see — but is never deleted.'),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='cert_expiry_alerts_enabled',
            field=models.BooleanField(default=True, help_text='Raise alerts for endpoints serving a certificate that is close to expiry or already expired.'),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='cert_expiry_critical_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Days before expiry the alert becomes critical. An already expired certificate is a separate, worse state again.'),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='cert_expiry_warning_days',
            field=models.PositiveSmallIntegerField(default=30, help_text="Days before expiry a warning alert opens. Must be above your certificates' renewal lead time, or a freshly renewed short-lived certificate re-opens the alert immediately."),
        ),
        migrations.CreateModel(
            name='CertificateBinding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('port', models.PositiveIntegerField(default=443)),
                ('server_name', models.CharField(blank=True, default='', help_text="The SNI / hostname requested when the certificate was read. Part of the endpoint's identity: one IP:port can legitimately serve a different certificate per name.", max_length=255)),
                ('endpoint_key', models.CharField(db_index=True, help_text='Denormalised (IP, port, SNI) identity — stable across renewals, which is what expiry alerts are keyed on.', max_length=80)),
                ('chain_depth', models.PositiveSmallIntegerField(default=0, help_text='Position in the chain *this endpoint* presented — 0 is the end-entity (leaf) certificate, 1 its issuer, and so on.')),
                ('chain_verified', models.BooleanField(blank=True, help_text='Did the chain *this endpoint* presented validate against the trust store? NULL = not known. Recorded, never enforced.', null=True)),
                ('first_seen', models.DateTimeField(help_text='First time this endpoint was observed serving this certificate.')),
                ('last_seen', models.DateTimeField(db_index=True, help_text='Most recent observation. Going stale — not being deleted — is how an endpoint that stopped serving this certificate is recorded.')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='monitoring.certificate')),
                ('target_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_bindings', to='api.ipaddress')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_bindings', to='core.tenant')),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['tenant', 'endpoint_key', '-last_seen'], name='monitoring__tenant__077f11_idx'), models.Index(fields=['certificate', '-last_seen'], name='monitoring__certifi_ceaef9_idx'), models.Index(fields=['tenant', 'chain_depth', '-last_seen'], name='monitoring__tenant__2db8ca_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'certificate', 'target_ip', 'port', 'server_name'), name='uniq_certificate_binding_endpoint')],
            },
        ),
    ]
