# Generated by Django 5.2.15 on 2026-07-28 20:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


def mark_existing_observed(apps, schema_editor):
    """Every Certificate that exists before this migration was written by the
    collector, so it is observed. The new ``observed`` flag defaults to False for
    forward compatibility with uploaded rows; backfill the existing rows to True
    so their origin reads correctly."""
    Certificate = apps.get_model("monitoring", "Certificate")
    Certificate.objects.update(observed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_deploymentsettings_rq_workers'),
        ('monitoring', '0047_certificate_bindings_and_expiry_thresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Operator-chosen label for this certificate.', max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certificate',
            name='observed',
            field=models.BooleanField(default=False, help_text='Seen being served by a TLS endpoint (the collector wrote it).'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='pem',
            field=models.TextField(blank=True, default='', help_text='Public certificate PEM (uploaded certs only). Never a key.'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='uploaded',
            field=models.BooleanField(default=False, help_text='Declared by an operator via the upload API (public PEM stored).'),
        ),
        migrations.RunPython(mark_existing_observed, migrations.RunPython.noop),
        migrations.CreateModel(
            name='CertificateAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(help_text='e.g. api.device, api.ipaddress, api.virtualmachine, api.service.', max_length=64)),
                ('object_id', models.CharField(max_length=64)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='monitoring.certificate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_assignments', to='core.tenant')),
            ],
            options={
                'ordering': ['object_type', 'object_id'],
                'indexes': [models.Index(fields=['tenant', 'object_type', 'object_id'], name='monitoring__tenant__33e9f3_idx'), models.Index(fields=['certificate'], name='monitoring__certifi_4da1f8_idx')],
                'constraints': [models.UniqueConstraint(fields=('certificate', 'object_type', 'object_id'), name='uniq_certificate_assignment')],
            },
        ),
    ]
