# Generated by Django 5.2.15 on 2026-07-31 05:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_site_time_zone'),
        ('core', '0031_deploymentsettings_rq_workers'),
        ('monitoring', '0048_certificate_name_certificate_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHHostKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_type', models.CharField(help_text='OpenSSH algorithm name, e.g. ssh-ed25519, ssh-rsa, ecdsa-sha2-nistp256.', max_length=64)),
                ('public_key', models.TextField(help_text='The base64 public-key blob (the middle field of an OpenSSH line). Public data only — never a private key.')),
                ('fingerprint_sha256', models.CharField(help_text='OpenSSH SHA256:… fingerprint. The identity of the key — the same key seen anywhere is this same row.', max_length=64)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('bits', models.PositiveIntegerField(blank=True, null=True)),
                ('observed', models.BooleanField(default=False, help_text='Seen being presented by the device (the collector wrote it).')),
                ('uploaded', models.BooleanField(default=False, help_text='Declared by an operator as the expected host key.')),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_host_keys', to='api.device')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_host_keys', to='core.tenant')),
            ],
            options={
                'ordering': ['device_id', 'key_type'],
                'indexes': [models.Index(fields=['tenant', 'device'], name='monitoring__tenant__5f8824_idx'), models.Index(fields=['device', 'key_type'], name='monitoring__device__a79a72_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'fingerprint_sha256'), name='uniq_ssh_host_key_tenant_fp')],
            },
        ),
    ]
