# Generated by Django 5.2.15 on 2026-07-31 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0049_sshhostkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='authority_key_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_ca',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuer_certificate',
            field=models.ForeignKey(blank=True, help_text="The parent CA certificate in this tenant's inventory, if known.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='monitoring.certificate'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='subject_key_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
