# Generated by Django 5.2.15 on 2026-07-31 09:55

import django.db.models.deletion
import monitoring.secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_deploymentsettings_secrets_provider'),
        ('monitoring', '0050_certificate_authority_key_id_certificate_is_ca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredSecret',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(help_text='Opaque reference the owning feature uses to fetch this secret.', max_length=200)),
                ('value', monitoring.secrets.EncryptedJSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_secrets', to='core.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'ref'), name='uniq_stored_secret_tenant_ref')],
            },
        ),
    ]
