# Generated by Django 5.2.15 on 2026-07-31 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_deploymentsettings_secrets_provider'),
        ('monitoring', '0051_storedsecret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('common_name', models.CharField(max_length=255)),
                ('organization', models.CharField(blank=True, default='', max_length=255)),
                ('organizational_unit', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('state', models.CharField(blank=True, default='', max_length=128)),
                ('locality', models.CharField(blank=True, default='', max_length=128)),
                ('san_dns', models.JSONField(blank=True, default=list)),
                ('san_ip', models.JSONField(blank=True, default=list)),
                ('key_spec', models.CharField(choices=[('rsa-2048', 'RSA 2048'), ('rsa-3072', 'RSA 3072'), ('rsa-4096', 'RSA 4096'), ('ec-p256', 'ECDSA P-256'), ('ec-p384', 'ECDSA P-384'), ('ed25519', 'Ed25519')], default='rsa-2048', max_length=16)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], db_index=True, default='generated', max_length=12)),
                ('csr_pem', models.TextField(blank=True, default='')),
                ('key_ref', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_requests', to=settings.AUTH_USER_MODEL)),
                ('issued_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_requests', to='monitoring.certificate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='monitoring__tenant__325b1e_idx')],
            },
        ),
    ]
