# Generated by Django 5.2.15 on 2026-07-31 12:00

import django.db.models.deletion
import monitoring.secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_deploymentsettings_vault_addr_and_more'),
        ('monitoring', '0052_certificaterequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('acme', 'ACME')], default='acme', max_length=12)),
                ('enabled', models.BooleanField(default=True)),
                ('directory_url', models.URLField(help_text='ACME directory URL, e.g. https://acme-v02.api.letsencrypt.org/directory or https://stepca.danbyte.lan/acme/acme/directory.')),
                ('contact_email', models.CharField(blank=True, default='', max_length=255)),
                ('eab_kid', models.CharField(blank=True, default='', max_length=255)),
                ('verify_tls', models.BooleanField(default=True)),
                ('account_uri', models.CharField(blank=True, default='', max_length=512)),
                ('account_ref', models.CharField(blank=True, default='', max_length=200)),
                ('secrets', monitoring.secrets.EncryptedJSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuers', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuers', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcmeOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('processing', 'Processing'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('errored', 'Errored')], db_index=True, default='pending', max_length=12)),
                ('challenge_type', models.CharField(choices=[('dns-01', 'DNS-01'), ('http-01', 'HTTP-01')], default='dns-01', max_length=8)),
                ('identifiers', models.JSONField(blank=True, default=list)),
                ('order_url', models.CharField(blank=True, default='', max_length=512)),
                ('challenges', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acme_orders', to=settings.AUTH_USER_MODEL)),
                ('issued_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acme_orders', to='monitoring.certificate')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acme_orders', to='monitoring.certificaterequest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acme_orders', to='core.tenant')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='monitoring.issuer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='issuer',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_issuer_name'),
        ),
        migrations.AddIndex(
            model_name='acmeorder',
            index=models.Index(fields=['tenant', 'status'], name='monitoring__tenant__aba220_idx'),
        ),
    ]
