# Generated by Django 5.2.15 on 2026-07-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0053_issuer_acmeorder_issuer_uniq_issuer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='dns_provider',
            field=models.CharField(blank=True, choices=[('', 'Manual'), ('rfc2136', 'RFC2136 / TSIG')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='issuer',
            name='dns_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
