# Generated by Django 5.2.15 on 2026-07-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0054_issuer_dns_provider_issuer_dns_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuer',
            name='dns_provider',
            field=models.CharField(blank=True, choices=[('', 'Manual'), ('rfc2136', 'RFC2136 / TSIG'), ('gss-tsig', 'Windows AD DNS (GSS-TSIG)')], default='', max_length=16),
        ),
    ]
