# Generated by Django 5.2.16 on 2026-07-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_labeltemplate'),
        ('core', '0034_tenantsettings_onboarding_dismissed'),
        ('monitoring', '0055_alter_issuer_dns_provider'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sshhostkey',
            name='uniq_ssh_host_key_tenant_fp',
        ),
        migrations.AddConstraint(
            model_name='sshhostkey',
            constraint=models.UniqueConstraint(fields=('tenant', 'device', 'fingerprint_sha256'), name='uniq_ssh_host_key_device_fp'),
        ),
    ]
