# Generated by Django 5.2.16 on 2026-08-01 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_documentcategory_document_and_more'),
        ('core', '0034_tenantsettings_onboarding_dismissed'),
        ('monitoring', '0056_remove_sshhostkey_uniq_ssh_host_key_tenant_fp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCredential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('ssh_password', 'SSH password'), ('ssh_key', 'SSH key'), ('https_login', 'HTTPS login')], max_length=16)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('scheme', models.CharField(blank=True, default='', help_text='For https_login: http or https. Ignored for SSH kinds.', max_length=8)),
                ('secret_provider', models.CharField(choices=[('local', 'Local'), ('vault', 'Vault')], help_text='Which secret store holds the value referenced by secret_path.', max_length=8)),
                ('secret_path', models.CharField(help_text='Reference to the secret in the chosen store — an external path/ref Danbyte reads at use-time. The secret value is never stored here.', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='api.device')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_credentials', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'device'], name='monitoring__tenant__0b5400_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'device', 'name'), name='uniq_device_credential_tenant_device_name')],
            },
        ),
    ]
