# Generated by Django 5.2.16 on 2026-08-01 12:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_tenantsettings_onboarding_dismissed'),
        ('monitoring', '0057_devicecredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectProtocol',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('url_template', models.CharField(help_text='Launch URL with {placeholders}: {host}, {username}, {port}, {name}. E.g. ssh://{username}@{host} or telnet://{host}:{port}. The browser hands the resulting URL to the OS protocol handler.', max_length=500)),
                ('icon', models.CharField(blank=True, default='', help_text='Optional Lucide icon name for the menu entry.', max_length=32)),
                ('default_port', models.PositiveIntegerField(blank=True, help_text='Substituted for {port} when the device has no explicit port.', null=True)),
                ('weight', models.PositiveSmallIntegerField(default=1000, help_text='Lower sorts first in the Connect menu.')),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_protocols', to='core.tenant')),
            ],
            options={
                'ordering': ['weight', 'name'],
                'indexes': [models.Index(fields=['tenant', 'enabled'], name='monitoring__tenant__703b90_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_connect_protocol_tenant_name')],
            },
        ),
    ]
