# Generated by Django 5.2.16 on 2026-08-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_documentcategory_document_and_more'),
        ('monitoring', '0059_seed_connect_protocols'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectprotocol',
            name='device_types',
            field=models.ManyToManyField(blank=True, related_name='connect_protocols', to='api.devicetype'),
        ),
        migrations.AddField(
            model_name='connectprotocol',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='connect_protocols', to='api.devicerole'),
        ),
    ]
