# Generated by Django 5.2.16 on 2026-08-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0060_connectprotocol_device_types_connectprotocol_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecredential',
            name='secret_managed',
            field=models.BooleanField(default=True, help_text='True: Danbyte stores the secret in the active store under its own namespace (the operator types the value once). False: the operator references an existing external path they manage themselves.'),
        ),
        migrations.AlterField(
            model_name='devicecredential',
            name='secret_path',
            field=models.CharField(blank=True, default='', help_text='For a managed credential, the auto-assigned ref Danbyte wrote to. For an external credential, the operator-managed path to read. The secret value itself is never stored on this row.', max_length=200),
        ),
        migrations.AlterField(
            model_name='devicecredential',
            name='secret_provider',
            field=models.CharField(blank=True, choices=[('local', 'Local'), ('vault', 'Vault')], default='', help_text='Which secret store holds the value. For a managed credential this is stamped with the active provider at write-time.', max_length=8),
        ),
    ]
