# Generated by Django 5.2.16 on 2026-08-04 17:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_deploymentsettings_session_idle_timeout_minutes'),
        ('monitoring', '0061_devicecredential_secret_managed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedEndpoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(help_text='Hostname or IP to connect to.', max_length=255)),
                ('port', models.PositiveIntegerField(default=443)),
                ('server_name', models.CharField(blank=True, default='', help_text='SNI / server name to request; blank uses the host.', max_length=255)),
                ('interval_seconds', models.PositiveIntegerField(default=86400, help_text='How often to re-read the certificate.')),
                ('enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, default='', max_length=12)),
                ('last_detail', models.JSONField(blank=True, default=dict)),
                ('last_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitoring.certificate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_endpoints', to='core.tenant')),
            ],
            options={
                'ordering': ['host', 'port'],
                'indexes': [models.Index(fields=['tenant', 'enabled'], name='monitoring__tenant__3b5f88_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'host', 'port', 'server_name'), name='uniq_watched_endpoint')],
            },
        ),
    ]
