# Generated by Django 5.2.16 on 2026-08-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0062_watchedendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedendpoint',
            name='allow_self_signed',
            field=models.BooleanField(default=False, help_text='Treat a self-signed certificate as healthy (up) instead of degraded — for endpoints that are self-signed by design. Expiry and not-yet-valid still degrade.'),
        ),
    ]
