# Generated by Django 5.2.16 on 2026-08-04 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_documentcategory_document_and_more'),
        ('monitoring', '0063_watchedendpoint_allow_self_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationchannel',
            name='match_prefix',
            field=models.ForeignKey(blank=True, help_text='Only status changes for IPs inside this subnet; blank = all.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_channels', to='api.prefix'),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='send_status_changes',
            field=models.BooleanField(default=False, help_text='Send every status change for matching IPs, independent of alert rules.'),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='status_change_interval_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Batched mode: how often to send the mini-digest.'),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='status_change_last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='status_change_mode',
            field=models.CharField(choices=[('instant', 'Instant'), ('batched', 'Batched (mini-digest)')], default='batched', max_length=8),
        ),
    ]
