# Generated by Django 5.2.16 on 2026-08-04 20:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0037_deploymentsettings_cert_digest_enabled_and_more'),
        ('monitoring', '0064_notificationchannel_match_prefix_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationchannel',
            name='self_subscribable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mandatory', models.BooleanField(default=False, help_text='Admin/group-assigned — the subscriber cannot remove it.')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='monitoring.notificationchannel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to='auth.group')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'channel'], name='monitoring__tenant__4843a9_idx')],
                'constraints': [models.UniqueConstraint(fields=('channel', 'user'), name='uniq_channel_user_subscription'), models.UniqueConstraint(fields=('channel', 'group'), name='uniq_channel_group_subscription')],
            },
        ),
    ]
