# Generated by Django 5.2.16 on 2026-08-04 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_documentcategory_document_and_more'),
        ('monitoring', '0065_notificationchannel_self_subscribable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationchannel',
            name='auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='match_ip',
            field=models.ForeignKey(blank=True, help_text='Only notify for this single IP; blank = all.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_channels', to='api.ipaddress'),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='match_prefix',
            field=models.ForeignKey(blank=True, help_text='Only notify for IPs inside this subnet; blank = all.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_channels', to='api.prefix'),
        ),
    ]
