# Generated by Django 5.2.16 on 2026-08-04 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_documentcategory_document_and_more'),
        ('monitoring', '0066_notificationchannel_auto_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationchannel',
            name='match_device',
            field=models.ForeignKey(blank=True, help_text='Only notify for IPs assigned to this device; blank = all.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_channels', to='api.device'),
        ),
    ]
