# Generated by Django 5.2.16 on 2026-08-13 18:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_documentcategory_document_and_more'),
        ('core', '0038_saved_filter'),
        ('monitoring', '0067_notificationchannel_match_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('maintenance', 'Maintenance'), ('outage', 'Outage')], default='maintenance', max_length=12)),
                ('status', models.CharField(default='tentative', max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('external_ref', models.CharField(blank=True, default='', max_length=120)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('etr', models.DateTimeField(blank=True, null=True)),
                ('raw_email', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, help_text='The carrier this came from; empty for internal work.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_events', to='api.provider')),
                ('silence', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_event', to='monitoring.silence')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_events', to='core.tenant')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='EventImpact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(help_text='Model label, e.g. api.circuit.', max_length=64)),
                ('object_id', models.UUIDField()),
                ('object_site_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('level', models.CharField(choices=[('no_impact', 'No impact'), ('reduced_redundancy', 'Reduced redundancy'), ('degraded', 'Degraded'), ('outage', 'Outage')], default='outage', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_impacts', to='core.tenant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='monitoring.maintenanceevent')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenanceevent',
            index=models.Index(fields=['tenant', 'kind', 'status'], name='monitoring__tenant__f78dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceevent',
            index=models.Index(fields=['tenant', 'starts_at'], name='monitoring__tenant__fdcda6_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_ref', ''), _negated=True), fields=('tenant', 'provider', 'external_ref'), name='uniq_event_per_provider_ref'),
        ),
        migrations.AddIndex(
            model_name='eventimpact',
            index=models.Index(fields=['object_type', 'object_id'], name='monitoring__object__204f95_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventimpact',
            constraint=models.UniqueConstraint(fields=('event', 'object_type', 'object_id'), name='uniq_impact_per_event_object'),
        ),
    ]
