# Generated by Django 5.2.16 on 2026-08-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_documentcategory_document_and_more'),
        ('monitoring', '0068_maintenance_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='silence',
            name='match_devices',
            field=models.ManyToManyField(blank=True, related_name='silences', to='api.device'),
        ),
    ]
