# Generated by Django 5.2.16 on 2026-08-15 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_interface_is_uplink'),
        ('monitoring', '0070_event_status_from_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsettings',
            name='arp_source_device',
            field=models.ForeignKey(blank=True, help_text="Use this device's ARP table (e.g. the gateway firewall) for switch-link suggestions instead of each switch's own.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.device'),
        ),
    ]
