# Generated by Django 5.2.16 on 2026-08-17 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_virtualdisk_virtualswitch'),
        ('core', '0040_deploymentsettings_component_popover_fields'),
        ('monitoring', '0071_monitoringsettings_arp_source_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesnmp',
            name='vm',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snmp', to='api.virtualmachine'),
        ),
        migrations.AddField(
            model_name='snmpinterfacesample',
            name='vm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snmp_samples', to='api.virtualmachine'),
        ),
        migrations.AlterField(
            model_name='devicesnmp',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snmp', to='api.device'),
        ),
        migrations.AlterField(
            model_name='snmpinterfacesample',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snmp_samples', to='api.device'),
        ),
        migrations.AlterField(
            model_name='snmpprofilebinding',
            name='object_id',
            field=models.UUIDField(help_text='id of the device / role / type / vm / platform / cluster.'),
        ),
        migrations.AlterField(
            model_name='snmpprofilebinding',
            name='scope',
            field=models.CharField(choices=[('device', 'Device'), ('device_role', 'Device role'), ('device_type', 'Device type'), ('location', 'Location'), ('site', 'Site'), ('vm', 'Virtual machine'), ('platform', 'Platform'), ('cluster', 'Cluster')], max_length=16),
        ),
        migrations.AddIndex(
            model_name='snmpinterfacesample',
            index=models.Index(fields=['vm', 'if_index', 'sampled_at'], name='monitoring__vm_id_aa02f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicesnmp',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('device__isnull', False), ('vm__isnull', True)), models.Q(('device__isnull', True), ('vm__isnull', False)), _connector='OR'), name='devicesnmp_device_xor_vm'),
        ),
    ]
