# Generated by Django 5.2.16 on 2026-08-19 21:34

import django.db.models.deletion
import monitoring.secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0072_devicesnmp_vm_snmpinterfacesample_vm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='dedup_key',
            field=models.CharField(help_text='Stable key for the alerting condition - (IP, check). One firing alert per key.', max_length=120),
        ),
        migrations.AlterField(
            model_name='alert',
            name='flapping',
            field=models.BooleanField(default=False, help_text='Condition is opening/clearing repeatedly - renotify is paused.'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='fingerprint_sha256',
            field=models.CharField(help_text='SHA-256 of the DER encoding, lowercase hex. The identity of the certificate - the same cert seen anywhere is this same row.', max_length=64),
        ),
        migrations.AlterField(
            model_name='certificatebinding',
            name='chain_depth',
            field=models.PositiveSmallIntegerField(default=0, help_text='Position in the chain *this endpoint* presented - 0 is the end-entity (leaf) certificate, 1 its issuer, and so on.'),
        ),
        migrations.AlterField(
            model_name='certificatebinding',
            name='endpoint_key',
            field=models.CharField(db_index=True, help_text='Denormalised (IP, port, SNI) identity - stable across renewals, which is what expiry alerts are keyed on.', max_length=80),
        ),
        migrations.AlterField(
            model_name='certificatebinding',
            name='last_seen',
            field=models.DateTimeField(db_index=True, help_text='Most recent observation. Going stale - not being deleted - is how an endpoint that stopped serving this certificate is recorded.'),
        ),
        migrations.AlterField(
            model_name='checkassignment',
            name='overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Per-assignment overrides of the template - recognised keys: interval_seconds, timeout_ms, rise, fall, params (shallow-merged).'),
        ),
        migrations.AlterField(
            model_name='checkassignment',
            name='schedule_mode',
            field=models.CharField(choices=[('follow_global', 'Follow global schedule'), ('custom_on', 'Custom - always on'), ('custom_off', 'Custom - off')], default='follow_global', max_length=16),
        ),
        migrations.AlterField(
            model_name='checkstate',
            name='engine',
            field=models.ForeignKey(blank=True, help_text="Which engine runs this check - resolved from the target's site/location at materialise time (null = the tenant's local engine).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_states', to='monitoring.monitoringengine'),
        ),
        migrations.AlterField(
            model_name='monitoringsettings',
            name='cert_binding_stale_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Days without observing an endpoint before its binding counts as stale. A stale binding stops alerting - nobody is served by a certificate we can no longer see - but is never deleted.'),
        ),
        migrations.AlterField(
            model_name='notificationsubscription',
            name='mandatory',
            field=models.BooleanField(default=False, help_text='Admin/group-assigned - the subscriber cannot remove it.'),
        ),
        migrations.AlterField(
            model_name='snmpprofile',
            name='secret_params',
            field=monitoring.secrets.EncryptedJSONField(blank=True, default=dict, help_text='Credentials - v2c community, or v3 auth_key / priv_key. Encrypted at rest; never returned by the API.'),
        ),
        migrations.AlterField(
            model_name='snmpprofilebinding',
            name='target',
            field=models.CharField(blank=True, default='', help_text="Poll this address instead of the device's own IPs (device scope only) - e.g. a BMC or a management address the agent listens on. Blank resolves management IP → primary IP → resolvable name.", max_length=255),
        ),
        migrations.AlterField(
            model_name='snmpsensor',
            name='absent_status',
            field=models.CharField(blank=True, default='', help_text="Status slug for items this sensor covers but the agent never reported - the empty bays a chassis template stamped. Blank leaves them alone. Only applied after a poll that actually returned readings, so a timeout can't mark real hardware missing.", max_length=64),
        ),
        migrations.AlterField(
            model_name='snmpsensor',
            name='apply_mode',
            field=models.CharField(choices=[('drift', 'Surface as drift - you accept it'), ('auto', 'Apply automatically')], default='drift', help_text="What a reading does to the source of truth. 'drift' keeps readings observed-only and lists the difference for review - Danbyte's normal contract, and the only mode that can't overwrite a status you set. 'auto' writes straight through, for health you want acted on with no one watching.", max_length=8),
        ),
        migrations.AlterField(
            model_name='snmpsensor',
            name='oid',
            field=models.CharField(help_text='Numeric OID - a table column base to WALK, or a scalar to GET.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sshhostkey',
            name='fingerprint_sha256',
            field=models.CharField(help_text='OpenSSH SHA256:… fingerprint. The identity of the key - the same key seen anywhere is this same row.', max_length=64),
        ),
        migrations.AlterField(
            model_name='sshhostkey',
            name='public_key',
            field=models.TextField(help_text='The base64 public-key blob (the middle field of an OpenSSH line). Public data only - never a private key.'),
        ),
        migrations.AlterField(
            model_name='watchedendpoint',
            name='allow_self_signed',
            field=models.BooleanField(default=False, help_text='Treat a self-signed certificate as healthy (up) instead of degraded - for endpoints that are self-signed by design. Expiry and not-yet-valid still degrade.'),
        ),
    ]
