# Generated by Django 5.2.16 on 2026-08-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0073_text_hyphens'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsettings',
            name='dns_resolvers',
            field=models.JSONField(blank=True, default=list, help_text="Nameservers to ask for PTR lookups, as IP addresses, tried in order. These are queried directly - the Danbyte host does not need DNS configured for this. Empty means use the host's own resolver."),
        ),
    ]
