# Generated by Django 5.2.16 on 2026-08-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0074_dns_resolvers'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringengine',
            name='dns_resolve_locally',
            field=models.BooleanField(default=False, help_text='Let this Outpost resolve PTR records itself, instead of the Danbyte server doing it. Use when the Outpost can see DNS the server cannot.'),
        ),
        migrations.AddField(
            model_name='monitoringengine',
            name='dns_resolvers',
            field=models.JSONField(blank=True, default=list, help_text="Nameservers this Outpost asks, as IP addresses, tried in order. Empty means the Outpost's own host resolver."),
        ),
    ]
