# Generated by Django 5.2.16 on 2026-08-20 13:48
# Hand-ordered: the M2M is added and the old single FK's value copied into it
# BEFORE the FK is dropped, so an existing "one ARP source" setting survives
# the upgrade as a one-element list (issue #39).

from django.db import migrations, models


def _copy_single_source(apps, schema_editor):
    MonitoringSettings = apps.get_model("monitoring", "MonitoringSettings")
    for row in MonitoringSettings.objects.exclude(arp_source_device=None):
        row.arp_source_devices.add(row.arp_source_device_id)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_text_hyphens'),
        ('monitoring', '0075_outpost_dns'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsettings',
            name='arp_source_devices',
            field=models.ManyToManyField(blank=True, help_text="Merge these devices' ARP tables (e.g. the gateway firewalls) for switch-link suggestions instead of each switch's own.", related_name='+', to='api.device'),
        ),
        migrations.RunPython(_copy_single_source, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='monitoringsettings',
            name='arp_source_device',
        ),
    ]
