# Generated by Django 5.2.16 on 2026-08-21 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_devicerole_icon'),
        ('core', '0043_text_hyphens'),
        ('monitoring', '0076_arp_source_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortUtilizationRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('condition', models.CharField(choices=[('above', 'Utilization at or above threshold'), ('below', 'Utilization at or below threshold'), ('no_ports', 'Device has no ports at all')], max_length=8)),
                ('threshold_pct', models.PositiveSmallIntegerField(blank=True, help_text='Percent used that trips the rule (above/below conditions).', null=True)),
                ('device', models.ForeignKey(blank=True, help_text='Only this device.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='port_utilization_rules', to='api.device')),
                ('device_type', models.ForeignKey(blank=True, help_text='Only devices of this type.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='port_utilization_rules', to='api.devicetype')),
                ('role', models.ForeignKey(blank=True, help_text='Only devices with this role.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='port_utilization_rules', to='api.devicerole')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_utilization_rules', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'enabled'], name='monitoring__tenant__edf604_idx')],
            },
        ),
    ]
