# Generated by Django 5.2.16 on 2026-08-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0077_portutilizationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsettings',
            name='snmp_import_not_present',
            field=models.BooleanField(default=False, help_text='Import interfaces the agent reports as notPresent (pre-allocated stack ports). Off = skip them on sync and drift.'),
        ),
    ]
