# Generated by Django 5.2.16 on 2026-08-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0078_snmp_import_not_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringengine',
            name='snmp_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='engine_offline_after_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
