# Generated by Django 5.2.16 on 2026-09-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0079_monitoringengine_snmp_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsettings',
            name='snmp_mac_from_fdb',
            field=models.BooleanField(default=False, help_text="Interface MAC drift/sync uses the MAC-table entry learned on the port (the attached device) instead of the port's own hardware MAC. Ports with several learned MACs are left alone."),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='snmp_skip_unrouted_vlans',
            field=models.BooleanField(default=False, help_text="Skip L2 VLAN pseudo-interfaces (Cisco's 'unrouted VLAN N' ifTable rows) - they are VLANs, not ports. Routed SVIs stay."),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='snmp_update_only',
            field=models.BooleanField(default=False, help_text='SNMP never ADDS interfaces - drift and sync only update fields on ports that already exist.'),
        ),
    ]
