# Generated by Django 5.2.16 on 2026-09-01 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_vminterface_parent'),
        ('core', '0045_hide_local_login'),
        ('monitoring', '0080_monitoringsettings_snmp_mac_from_fdb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsettings',
            name='snmp_default_vrf',
            field=models.ForeignKey(blank=True, help_text='VRF that SNMP-discovered addresses land in when neither the interface nor a device/role/type/site binding names one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.vrf'),
        ),
        migrations.CreateModel(
            name='SnmpVrfBinding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('device', 'Device'), ('device_role', 'Device role'), ('device_type', 'Device type'), ('site', 'Site')], max_length=16)),
                ('object_id', models.UUIDField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_vrf_bindings', to='core.tenant')),
                ('vrf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_vrf_bindings', to='api.vrf')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'scope', 'object_id'), name='uniq_snmpvrfbinding_scope_object')],
            },
        ),
    ]
