# Generated by Django 5.2.16 on 2026-09-10 13:21

import monitoring.secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0081_monitoringsettings_snmp_default_vrf_snmpvrfbinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationchannel',
            name='secrets',
            field=monitoring.secrets.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='kind',
            field=models.CharField(choices=[('webhook', 'Webhook'), ('email', 'Email'), ('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('discord', 'Discord'), ('pagerduty', 'PagerDuty'), ('telegram', 'Telegram')], max_length=12),
        ),
    ]
