# Generated by Django 5.2.16 on 2026-09-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0082_notificationchannel_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringengine',
            name='kind',
            field=models.CharField(default='remote', max_length=32),
        ),
    ]
