# Generated by Django 5.2.16 on 2026-09-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0083_alter_monitoringengine_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringenginebinding',
            name='object_id',
            field=models.UUIDField(help_text='id of the device / site / location / prefix.'),
        ),
        migrations.AlterField(
            model_name='monitoringenginebinding',
            name='scope',
            field=models.CharField(choices=[('device', 'Device'), ('site', 'Site'), ('location', 'Location'), ('prefix', 'Prefix')], max_length=16),
        ),
    ]
