# Generated by Django 5.2.16 on 2026-09-10 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_status_monitoring_state'),
        ('core', '0051_deploymentsettings_azure_authority_and_more'),
        ('monitoring', '0084_engine_binding_device_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringpolicy',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_policies', to='api.platform'),
        ),
        migrations.AddField(
            model_name='monitoringpolicy',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_policies', to='api.region'),
        ),
        migrations.AddField(
            model_name='monitoringpolicy',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_policies', to='api.site'),
        ),
        migrations.AlterField(
            model_name='monitoringpolicy',
            name='scope',
            field=models.CharField(choices=[('global', 'Global'), ('region', 'Region'), ('site', 'Site'), ('vrf', 'VRF'), ('platform', 'Platform'), ('device_type', 'Device type'), ('device_role', 'Device role'), ('device', 'Device'), ('prefix', 'Prefix')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='monitoringpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('site__isnull', False)), fields=('tenant', 'scope', 'site'), name='uniq_monitoringpolicy_site'),
        ),
        migrations.AddConstraint(
            model_name='monitoringpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('region__isnull', False)), fields=('tenant', 'scope', 'region'), name='uniq_monitoringpolicy_region'),
        ),
        migrations.AddConstraint(
            model_name='monitoringpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('platform__isnull', False)), fields=('tenant', 'scope', 'platform'), name='uniq_monitoringpolicy_platform'),
        ),
    ]
