# Generated by Django 5.2.16 on 2026-09-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0086_policy_target_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringpolicy',
            name='match_name',
            field=models.CharField(blank=True, default='', help_text="Glob the device name must match, e.g. 'core-*'. Empty = any.", max_length=200),
        ),
        migrations.AddField(
            model_name='monitoringpolicy',
            name='match_tags',
            field=models.JSONField(blank=True, default=list, help_text='Tag slugs the device must carry - all of them. Empty = any.'),
        ),
    ]
