# Generated by Django 5.2.16 on 2026-09-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0087_policy_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringpolicy',
            name='match_interface',
            field=models.CharField(blank=True, default='', help_text="Glob the address's interface name must match, e.g. 'Gi0/0/*'. Empty = any. An address bound to no interface never matches.", max_length=200),
        ),
    ]
