# Generated by Django 5.2.16 on 2026-09-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0088_policy_match_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkstate',
            name='last_detail',
            field=models.JSONField(blank=True, default=dict, help_text="The latest result's protocol payload, denormalised. A list page wanting the open-problem count or which protocols an external system can reach a host on must not scan the history table for it - the same reason status and latency live here."),
        ),
    ]
