# Generated by Django 5.2.16 on 2026-09-12 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_status_monitoring_state'),
        ('core', '0051_deploymentsettings_azure_authority_and_more'),
        ('monitoring', '0091_result_transition_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkstate',
            name='flap_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkstate',
            name='flap_cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkstate',
            name='flap_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkstate',
            name='flapping_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='auto_clear_flapping',
            field=models.BooleanField(default=False, help_text='Clear a flapping state on its own once the check has been quiet for the settle time. Off keeps it until an operator confirms.'),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='auto_clear_flapping_after_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Quiet minutes before a flapping state clears itself.'),
        ),
        migrations.AddIndex(
            model_name='checkstate',
            index=models.Index(fields=['tenant', 'flapping_since'], name='monitoring__tenant__114cf6_idx'),
        ),
    ]
