# Generated by Django 5.2.16 on 2026-09-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0092_flapping_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkstate',
            name='fast_owned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkstate',
            name='fast_window',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='checkstate',
            name='interval_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkstate',
            name='last_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checktemplate',
            name='interval_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Fast-lane interval in milliseconds (200-59999). Empty = the check runs on the normal minute beat at interval_seconds.', null=True),
        ),
        migrations.AddField(
            model_name='checktemplate',
            name='record_every_seconds',
            field=models.PositiveIntegerField(default=60, help_text='Fast lane: how often one aggregated result is recorded (min/avg/max latency and loss over the window). Status changes are always recorded at once.'),
        ),
        migrations.AddField(
            model_name='monitoringengine',
            name='agent_fast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='fast_lane_max_checks',
            field=models.PositiveIntegerField(default=500, help_text='How many sub-minute checks the fast lane runs for this tenant (0 = none; the rest run at their fallback interval).'),
        ),
        migrations.AlterField(
            model_name='checktemplate',
            name='interval_seconds',
            field=models.PositiveIntegerField(default=300, help_text='How often the check runs, in seconds. With a fast interval set this is the fallback cadence when no fast lane can run it.'),
        ),
    ]
