# Generated by Django 5.2.16 on 2026-09-23 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0177_document_random_path'),
        ('core', '0054_housekeeping_settings'),
        ('monitoring', '0093_fast_lane'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsettings',
            name='spike_factor',
            field=models.FloatField(default=3.0, help_text="A probe slower than this many times its check's 7-day median latency counts as a spike."),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='spike_floor_ms',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CheckRollupDaily',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=32)),
                ('bucket', models.DateTimeField()),
                ('up_s', models.FloatField(default=0)),
                ('down_s', models.FloatField(default=0)),
                ('degraded_s', models.FloatField(default=0)),
                ('stale_s', models.FloatField(default=0)),
                ('unknown_s', models.FloatField(default=0)),
                ('incidents', models.PositiveIntegerField(default=0)),
                ('samples', models.PositiveIntegerField(default=0)),
                ('lat_min', models.FloatField(null=True)),
                ('lat_avg', models.FloatField(null=True)),
                ('lat_p50', models.FloatField(null=True)),
                ('lat_p95', models.FloatField(null=True)),
                ('lat_p99', models.FloatField(null=True)),
                ('lat_max', models.FloatField(null=True)),
                ('spikes', models.PositiveIntegerField(default=0)),
                ('closed', models.BooleanField(default=False)),
                ('target_ip', models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.ipaddress')),
                ('template', models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitoring.checktemplate')),
                ('tenant', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'bucket'], name='monitoring__tenant__0a3279_idx'), models.Index(fields=['target_ip', 'template', '-bucket'], name='monitoring__target__f1e8e3_idx')],
                'constraints': [models.UniqueConstraint(fields=('target_ip', 'template', 'bucket'), name='uniq_rollupdaily_ip_template_bucket')],
            },
        ),
        migrations.CreateModel(
            name='CheckRollupHourly',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=32)),
                ('bucket', models.DateTimeField()),
                ('up_s', models.FloatField(default=0)),
                ('down_s', models.FloatField(default=0)),
                ('degraded_s', models.FloatField(default=0)),
                ('stale_s', models.FloatField(default=0)),
                ('unknown_s', models.FloatField(default=0)),
                ('incidents', models.PositiveIntegerField(default=0)),
                ('samples', models.PositiveIntegerField(default=0)),
                ('lat_min', models.FloatField(null=True)),
                ('lat_avg', models.FloatField(null=True)),
                ('lat_p50', models.FloatField(null=True)),
                ('lat_p95', models.FloatField(null=True)),
                ('lat_p99', models.FloatField(null=True)),
                ('lat_max', models.FloatField(null=True)),
                ('spikes', models.PositiveIntegerField(default=0)),
                ('closed', models.BooleanField(default=False)),
                ('target_ip', models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.ipaddress')),
                ('template', models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitoring.checktemplate')),
                ('tenant', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'bucket'], name='monitoring__tenant__629dee_idx'), models.Index(fields=['target_ip', 'template', '-bucket'], name='monitoring__target__36a48f_idx')],
                'constraints': [models.UniqueConstraint(fields=('target_ip', 'template', 'bucket'), name='uniq_rolluphourly_ip_template_bucket')],
            },
        ),
    ]
