# Generated by Django 5.2.16 on 2026-09-23 20:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0177_document_random_path'),
        ('core', '0054_housekeeping_settings'),
        ('monitoring', '0094_check_rollups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('dates', models.JSONField(blank=True, default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_calendars', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SlaAgreement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('customer_name', models.CharField(blank=True, default='', max_length=150)),
                ('target_pct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('warning_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('period', models.CharField(choices=[('month', 'Calendar month'), ('quarter', 'Calendar quarter'), ('year', 'Calendar year'), ('rolling_7', 'Last 7 days'), ('rolling_30', 'Last 30 days'), ('rolling_90', 'Last 90 days')], default='month', max_length=12)),
                ('timezone', models.CharField(blank=True, default='', max_length=64)),
                ('service_hours', models.JSONField(blank=True, default=dict)),
                ('count_degraded_as', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='up', max_length=10)),
                ('count_stale_as', models.CharField(choices=[('unmeasured', 'Not measured'), ('down', 'Down')], default='unmeasured', max_length=10)),
                ('count_unknown_as', models.CharField(choices=[('unmeasured', 'Not measured'), ('down', 'Down')], default='unmeasured', max_length=10)),
                ('exclude_maintenance', models.BooleanField(default=True)),
                ('min_outage_seconds', models.PositiveIntegerField(default=0)),
                ('aggregation', models.CharField(choices=[('mean', 'Average of members'), ('worst', 'Worst member')], default='mean', max_length=10)),
                ('latency_objectives', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_agreements', to='api.contact')),
                ('holiday_calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='monitoring.holidaycalendar')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_agreements', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SlaAgreementRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('rules', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='monitoring.slaagreement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['agreement', '-number'],
            },
        ),
        migrations.CreateModel(
            name='SlaCheckGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('position', models.PositiveIntegerField(default=0)),
                ('target', models.CharField(choices=[('primary', 'Primary address'), ('all', 'Every address')], default='primary', max_length=10)),
                ('combine', models.CharField(choices=[('all', 'All must pass'), ('weighted', 'Weighted')], default='all', max_length=10)),
                ('weight', models.FloatField(default=1.0)),
                ('use_selector', models.BooleanField(default=False)),
                ('match_tags', models.JSONField(blank=True, default=list)),
                ('match_name', models.CharField(blank=True, default='', max_length=200)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_groups', to='monitoring.slaagreement')),
                ('match_device_types', models.ManyToManyField(blank=True, related_name='+', to='api.devicetype')),
                ('match_platforms', models.ManyToManyField(blank=True, related_name='+', to='api.platform')),
                ('match_roles', models.ManyToManyField(blank=True, related_name='+', to='api.devicerole')),
                ('match_sites', models.ManyToManyField(blank=True, related_name='+', to='api.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['agreement', 'position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SlaCheckItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counts', models.BooleanField(default=True)),
                ('weight', models.FloatField(default=1.0)),
                ('required', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='monitoring.slacheckgroup')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='monitoring.checktemplate')),
            ],
            options={
                'ordering': ['group', 'position'],
            },
        ),
        migrations.CreateModel(
            name='SlaMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=40)),
                ('object_id', models.UUIDField()),
                ('redundancy_group', models.CharField(blank=True, default='', max_length=100)),
                ('excluded', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='monitoring.slaagreement')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='monitoring.slacheckgroup')),
                ('object_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['agreement', 'group', 'object_type'],
            },
        ),
        migrations.CreateModel(
            name='SlaExclusion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.TextField()),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='monitoring.slaagreement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='monitoring.slamember')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='SlaPeriodResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_key', models.CharField(max_length=16)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('frozen', 'Frozen'), ('rolling', 'Rolling')], default='open', max_length=8)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('figures', models.JSONField(default=dict)),
                ('units', models.JSONField(default=list)),
                ('incidents', models.JSONField(default=list)),
                ('days', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitoring.slaagreement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['agreement', '-period_start'],
            },
        ),
        migrations.AddConstraint(
            model_name='holidaycalendar',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_holiday_calendar_name'),
        ),
        migrations.AddConstraint(
            model_name='slaagreement',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_sla_agreement_name'),
        ),
        migrations.AddConstraint(
            model_name='slaagreementrevision',
            constraint=models.UniqueConstraint(fields=('agreement', 'number'), name='uniq_sla_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='slacheckgroup',
            constraint=models.UniqueConstraint(fields=('agreement', 'name'), name='uniq_sla_group_name'),
        ),
        migrations.AddConstraint(
            model_name='slacheckitem',
            constraint=models.UniqueConstraint(fields=('group', 'template'), name='uniq_sla_item_template'),
        ),
        migrations.AddIndex(
            model_name='slamember',
            index=models.Index(fields=['tenant', 'object_type', 'object_id'], name='monitoring__tenant__b1884d_idx'),
        ),
        migrations.AddConstraint(
            model_name='slamember',
            constraint=models.UniqueConstraint(fields=('agreement', 'group', 'object_type', 'object_id'), name='uniq_sla_member'),
        ),
        migrations.AddConstraint(
            model_name='slaperiodresult',
            constraint=models.UniqueConstraint(fields=('agreement', 'period_key'), name='uniq_sla_period_result'),
        ),
    ]
