# Generated by Django 5.2.16 on 2026-09-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0095_sla'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsettings',
            name='availability_frame',
            field=models.CharField(choices=[('24h', '24 hours'), ('7d', '7 days'), ('30d', '30 days'), ('90d', '90 days'), ('mtd', 'Month to date'), ('qtd', 'Quarter to date'), ('ytd', 'Year to date')], default='30d', max_length=4),
        ),
    ]
