# Generated by Django 5.2.16 on 2026-09-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0096_availability_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaagreement',
            name='alert_burn_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slaagreement',
            name='alert_coverage_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='slaagreement',
            name='notify_channels',
            field=models.ManyToManyField(blank=True, related_name='sla_agreements', to='monitoring.notificationchannel'),
        ),
        migrations.AddField(
            model_name='slaagreement',
            name='report_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('both', 'PDF and CSV')], default='pdf', max_length=4),
        ),
        migrations.AddField(
            model_name='slaagreement',
            name='report_recipients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='slaperiodresult',
            name='alerts_sent',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='slaperiodresult',
            name='report_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
