# Generated by Django 5.2.16 on 2026-09-24 13:17

from django.db import migrations, models


def classify_existing(apps, schema_editor):
    """An agreement with a contact was for that contact, one with a name for
    that name; the rest belong to their tenant."""
    SlaAgreement = apps.get_model("monitoring", "SlaAgreement")
    SlaAgreement.objects.filter(customer__isnull=False).update(provided_for="contact")
    SlaAgreement.objects.filter(customer__isnull=True).exclude(customer_name="").update(
        provided_for="name"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0177_document_random_path'),
        ('monitoring', '0097_sla_alerts_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaagreement',
            name='provided_for',
            field=models.CharField(choices=[('tenant', 'This tenant'), ('sites', 'Sites'), ('contact', 'A contact'), ('name', 'A name')], default='tenant', max_length=8),
        ),
        migrations.AddField(
            model_name='slaagreement',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='sla_agreements', to='api.site'),
        ),
        migrations.RunPython(classify_existing, migrations.RunPython.noop),
    ]
