# Generated by Django 5.2.16 on 2026-09-24 15:33

import monitoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0098_sla_provided_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaagreement',
            name='burn_alerts',
            field=models.JSONField(blank=True, default=monitoring.models.default_burn_alerts),
        ),
        migrations.AddField(
            model_name='slaagreement',
            name='burn_state',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
