# Generated by Django 5.2.16 on 2026-09-24 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0177_document_random_path'),
        ('monitoring', '0099_sla_burn_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='slamember',
            name='monitor_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.ipaddress'),
        ),
        migrations.AlterField(
            model_name='slaagreement',
            name='aggregation',
            field=models.CharField(choices=[('mean', 'Average of members'), ('worst', 'Worst member'), ('all', 'All must be up')], default='mean', max_length=10),
        ),
    ]
