# Generated by Django 5.2.16 on 2026-09-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0100_sla_circuits_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaagreement',
            name='credit_tiers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='slaagreement',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='slaagreement',
            name='period_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
