# Generated by Django 5.2.16 on 2026-09-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0102_rollup_latency_histogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaagreement',
            name='objectives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='slaagreement',
            name='objectives_in_state',
            field=models.BooleanField(default=False),
        ),
    ]
