# Generated by Django 5.2.16 on 2026-10-01 06:17

from django.db import migrations, models
from django.db.models import F


def carry_incidents(apps, schema_editor):
    # Rows rolled before this counted stale as an incident too - which is
    # exactly what blind_incidents means. Their `incidents` stays as it was
    # until the bucket is rolled again.
    for name in ("CheckRollupHourly", "CheckRollupDaily"):
        apps.get_model("monitoring", name).objects.update(blind_incidents=F("incidents"))


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0103_sla_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkrollupdaily',
            name='blind_incidents',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='checkrolluphourly',
            name='blind_incidents',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.RunPython(carry_incidents, migrations.RunPython.noop),
    ]
