# Generated by Django 5.2.16 on 2026-10-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0191_floor_tile_cabinet'),
        ('core', '0057_tenantsettings_default_topology_view'),
        ('monitoring', '0105_rollup_daily_spikes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='snmpinterfacesample',
            index=models.Index(fields=['sampled_at'], name='monitoring__sampled_a3658b_idx'),
        ),
    ]
