# Generated by Django 5.2.16 on 2026-10-03 11:24
"""MAC tracking (#284): the learned-MAC and ARP sighting tables, the per-read
summary on DeviceSnmp and the tenant's MAC-tracking settings.

No data step: the tables fill on each device's next poll, and until then a
device's pre-0.17 JSON tables keep answering (``mac_tables.legacy_state``).
Every new column on an existing table has a database default or is nullable,
so processes still on the previous release keep inserting.
"""

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0194_interface_never_uplink'),
        ('core', '0058_deploymentsettings_port_count_virtual'),
        ('monitoring', '0107_interface_virtual_from_snmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesnmp',
            name='fdb_meta',
            field=models.JSONField(blank=True, db_default=models.Value({}, models.JSONField()), default=dict, help_text='How the last MAC-table read went: source, complete, truncated, VLAN and port mapping, drop counts, error.'),
        ),
        migrations.AddField(
            model_name='devicesnmp',
            name='fdb_polled_at',
            field=models.DateTimeField(blank=True, help_text='The last complete MAC-table read.', null=True),
        ),
        migrations.AddField(
            model_name='devicesnmp',
            name='mac_ports',
            field=models.JSONField(blank=True, db_default=models.Value({}, models.JSONField()), default=dict, help_text='Per-port summary of the last read: {port_key: {if_index, name, count, lldp, lag}}. Uplinks are classified from it on read.'),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='mac_port_display_limit',
            field=models.PositiveSmallIntegerField(db_default=4, default=4, help_text="Learned MACs listed per port before '+N more'. 0 = all.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(64)]),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='mac_retention_days',
            field=models.PositiveSmallIntegerField(db_default=30, default=30, help_text='Learned MACs and ARP entries unseen for longer than this are forgotten.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='mac_uplink_lldp',
            field=models.BooleanField(db_default=True, default=True, help_text='A port whose LLDP neighbour is a switch counts as an uplink.'),
        ),
        migrations.AddField(
            model_name='monitoringsettings',
            name='mac_uplink_threshold',
            field=models.PositiveIntegerField(db_default=4, default=4, help_text='A port that learns more distinct MACs than this counts as an uplink. 0 turns the count rule off.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4096)]),
        ),
        migrations.CreateModel(
            name='ArpSighting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('if_index', models.CharField(blank=True, default='', max_length=16)),
                ('ip', models.GenericIPAddressField()),
                ('mac', models.CharField(max_length=17)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('gone_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arp_sightings', to='api.device')),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arp_sightings', to='api.interface')),
                ('tenant', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('vm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arp_sightings', to='api.virtualmachine')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'mac'], name='arpsighting_tenant_mac'), models.Index(condition=models.Q(('gone_at__isnull', True)), fields=['tenant', 'ip'], name='arpsighting_present_ip'), models.Index(condition=models.Q(('gone_at__isnull', False)), fields=['tenant', 'gone_at'], name='arpsighting_gone')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('device__isnull', False), ('vm__isnull', True)), models.Q(('device__isnull', True), ('vm__isnull', False)), _connector='OR'), name='arpsighting_device_xor_vm'), models.UniqueConstraint(condition=models.Q(('device__isnull', False), ('gone_at__isnull', True)), fields=('device', 'ip', 'mac'), name='uniq_arpsighting_device_present'), models.UniqueConstraint(condition=models.Q(('gone_at__isnull', True), ('vm__isnull', False)), fields=('vm', 'ip', 'mac'), name='uniq_arpsighting_vm_present')],
            },
        ),
        migrations.CreateModel(
            name='MacSighting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('port_key', models.CharField(max_length=128)),
                ('port_name', models.CharField(blank=True, default='', max_length=128)),
                ('if_index', models.CharField(blank=True, default='', max_length=16)),
                ('vlan_vid', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fdb_id', models.PositiveIntegerField(blank=True, null=True)),
                ('mac', models.CharField(max_length=17)),
                ('status', models.CharField(blank=True, default='', max_length=8)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('gone_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mac_sightings', to='api.device')),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mac_sightings', to='api.interface')),
                ('polled_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mac_sightings_polled', to='api.device')),
                ('tenant', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'mac'], name='macsighting_tenant_mac'), models.Index(condition=models.Q(('gone_at__isnull', False)), fields=['tenant', 'gone_at'], name='macsighting_gone')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('gone_at__isnull', True)), fields=('polled_device', 'port_key', 'vlan_vid', 'mac'), name='uniq_macsighting_present', nulls_distinct=False)],
            },
        ),
    ]
