# Generated by Django 5.2.16 on 2026-10-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0108_mac_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringsettings',
            name='availability_frame',
            field=models.CharField(choices=[('24h', '24 hours'), ('7d', '7 days'), ('30d', '30 days'), ('90d', '90 days'), ('mtd', 'Month to date'), ('qtd', 'Quarter to date'), ('ytd', 'Year to date')], db_default='30d', default='30d', max_length=4),
        ),
        migrations.AlterField(
            model_name='monitoringsettings',
            name='spike_factor',
            field=models.FloatField(db_default=3.0, default=3.0, help_text="A probe slower than this many times its check's 7-day median latency counts as a spike."),
        ),
        migrations.AlterField(
            model_name='monitoringsettings',
            name='spike_floor_ms',
            field=models.JSONField(blank=True, db_default=models.Value({}, models.JSONField()), default=dict),
        ),
    ]
