# Generated by Django 5.2.16 on 2026-10-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0110_restore_opening_transitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsettings',
            name='snmp_poll_interval_minutes',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Off'), (15, '15 minutes'), (30, '30 minutes'), (60, '1 hour')], db_default=0, default=0, help_text='Poll every device the core polls this often. 0 = off.'),
        ),
    ]
