# Generated by Django 5.2.16 on 2026-10-10 07:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_upgrade_db_defaults'),
        ('monitoring', '0111_monitoringsettings_snmp_poll_interval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaIncidentCause',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_causes', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SlaIncidentFollowUp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=200)),
                ('started_at', models.DateTimeField()),
                ('ticket_url', models.URLField(blank=True, default='', max_length=500)),
                ('note', models.TextField(blank=True, default='')),
                ('disputed', models.BooleanField(default=False)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_follow_ups', to='monitoring.slaagreement')),
                ('cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='monitoring.slaincidentcause')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['agreement', '-started_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='slaincidentcause',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_sla_cause_name'),
        ),
        migrations.AddConstraint(
            model_name='slaincidentfollowup',
            constraint=models.UniqueConstraint(fields=('agreement', 'unit', 'started_at'), name='uniq_sla_incident_follow_up'),
        ),
    ]
