# Generated by Django 5.2.16 on 2026-10-10 07:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_upgrade_db_defaults'),
        ('monitoring', '0112_sla_incident_follow_up'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaReportSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=8)),
                ('weekday', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)])),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('hour', models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MaxValueValidator(23)])),
                ('period', models.CharField(choices=[('current', 'This period'), ('previous', 'Last period')], default='previous', max_length=8)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('report_format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('both', 'PDF and CSV')], default='pdf', max_length=4)),
                ('enabled', models.BooleanField(default=True)),
                ('report_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='', editable=False)),
                ('last_attempt_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('failures', models.PositiveIntegerField(default=0, editable=False)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='monitoring.slaagreement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.tenant')),
            ],
            options={
                'ordering': ['agreement', 'frequency', 'created_at'],
            },
        ),
    ]
