# Generated by Django 5.2.16 on 2026-10-10 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_upgrade_db_defaults'),
        ('monitoring', '0113_sla_report_schedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('target_pct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('warning_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('period', models.CharField(choices=[('month', 'Calendar month'), ('quarter', 'Calendar quarter'), ('year', 'Calendar year'), ('rolling_7', 'Last 7 days'), ('rolling_30', 'Last 30 days'), ('rolling_90', 'Last 90 days')], default='month', max_length=12)),
                ('timezone', models.CharField(blank=True, default='', max_length=64)),
                ('service_hours', models.JSONField(blank=True, default=dict)),
                ('count_degraded_as', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='up', max_length=10)),
                ('count_stale_as', models.CharField(choices=[('unmeasured', 'Not measured'), ('down', 'Down')], default='unmeasured', max_length=10)),
                ('count_unknown_as', models.CharField(choices=[('unmeasured', 'Not measured'), ('down', 'Down')], default='unmeasured', max_length=10)),
                ('exclude_maintenance', models.BooleanField(default=True)),
                ('min_outage_seconds', models.PositiveIntegerField(default=0)),
                ('aggregation', models.CharField(choices=[('mean', 'Average of members'), ('worst', 'Worst member'), ('all', 'All must be up')], default='mean', max_length=10)),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('objectives_in_state', models.BooleanField(default=False)),
                ('credit_tiers', models.JSONField(blank=True, default=list)),
                ('period_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('holiday_calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_templates', to='monitoring.holidaycalendar')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_templates', to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='slaagreement',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='monitoring.slatemplate'),
        ),
        migrations.AddConstraint(
            model_name='slatemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_sla_template_name'),
        ),
    ]
