#!/usr/bin/env python3
"""One-off generator for the dashboard world-map widget's dot grid.

Rasterizes a Natural Earth land GeoJSON onto an equirectangular grid and
emits frontend/src/components/dashboard/world-dots.ts — a single SVG path
string (one dot per land cell), so the widget ships zero runtime geo deps.

Usage:
    python scripts/gen_world_dots.py path/to/ne_110m_land.geojson
"""
import json
import sys

from PIL import Image, ImageDraw

W, H = 200, 95  # grid columns/rows (equirectangular, lat clamped ±~67°)
LAT_TOP, LAT_BOTTOM = 75.0, -60.0


def project(lng: float, lat: float) -> tuple[float, float]:
    x = (lng + 180.0) / 360.0 * W
    y = (LAT_TOP - lat) / (LAT_TOP - LAT_BOTTOM) * H
    return x, y


def main(path: str) -> None:
    gj = json.load(open(path))
    img = Image.new("1", (W * 4, H * 4), 0)  # 4x supersample
    draw = ImageDraw.Draw(img)
    for feat in gj["features"]:
        geom = feat["geometry"]
        polys = (
            geom["coordinates"]
            if geom["type"] == "MultiPolygon"
            else [geom["coordinates"]]
        )
        for poly in polys:
            ring = poly[0]
            pts = [
                tuple(v * 4 for v in project(lng, lat)) for lng, lat in ring
            ]
            if len(pts) >= 3:
                draw.polygon(pts, fill=1)
    dots = []
    px = img.load()
    for gy in range(H):
        for gx in range(W):
            # A cell is land if the supersampled center block is mostly set.
            hits = sum(
                px[gx * 4 + ox, gy * 4 + oy] for ox in (1, 2) for oy in (1, 2)
            )
            if hits >= 3:
                dots.append((gx, gy))
    # One path: tiny move+lineto per dot (rendered with round linecaps).
    d = "".join(f"M{x} {y}h0" for x, y in dots)
    out = (
        "// GENERATED by scripts/gen_world_dots.py from Natural Earth 110m\n"
        "// land polygons (public domain). Do not edit by hand.\n"
        f"export const WORLD_W = {W}\n"
        f"export const WORLD_H = {H}\n"
        f"export const LAT_TOP = {LAT_TOP}\n"
        f"export const LAT_BOTTOM = {LAT_BOTTOM}\n"
        f'export const WORLD_DOTS_PATH = "{d}"\n'
    )
    dest = "frontend/src/components/dashboard/world-dots.ts"
    with open(dest, "w") as f:
        f.write(out)
    print(f"{len(dots)} dots → {dest}")


if __name__ == "__main__":
    main(sys.argv[1])
